// Package soup was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package soup

import (
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
)

var xHeaderContains func(string, string) bool

// Parses @header to see if it contains the token @token (matched
// case-insensitively).
//
// Note that this can't be used with lists that have qvalues.
func HeaderContains(HeaderVar string, TokenVar string) bool {
	core.LazyRegister(&xHeaderContains, "SOUP", "soup_header_contains", false)

	cret := xHeaderContains(HeaderVar, TokenVar)
	return cret
}

var xHeaderFreeList func(*glib.SList)

// Frees @list.
func HeaderFreeList(ListVar *glib.SList) {
	core.LazyRegister(&xHeaderFreeList, "SOUP", "soup_header_free_list", false)

	xHeaderFreeList(ListVar)
}

var xHeaderFreeParamList func(*glib.HashTable)

// Frees @param_list.
func HeaderFreeParamList(ParamListVar *glib.HashTable) {
	core.LazyRegister(&xHeaderFreeParamList, "SOUP", "soup_header_free_param_list", false)

	xHeaderFreeParamList(ParamListVar)
}

var xHeaderGStringAppendParam func(*glib.String, string, uintptr)

// Appends something like `name=value` to @string, taking care to quote @value
// if needed, and if so, to escape any quotes or backslashes in @value.
//
// Alternatively, if @value is a non-ASCII UTF-8 string, it will be
// appended using RFC5987 syntax. Although in theory this is supposed
// to work anywhere in HTTP that uses this style of parameter, in
// reality, it can only be used portably with the Content-Disposition
// "filename" parameter.
//
// If @value is %NULL, this will just append @name to @string.
func HeaderGStringAppendParam(StringVar *glib.String, NameVar string, ValueVar *string) {
	core.LazyRegister(&xHeaderGStringAppendParam, "SOUP", "soup_header_g_string_append_param", false)

	ValueVarPtr := core.GStrdupNullable(ValueVar)
	defer core.GFreeNullable(ValueVarPtr)

	xHeaderGStringAppendParam(StringVar, NameVar, ValueVarPtr)
}

var xHeaderGStringAppendParamQuoted func(*glib.String, string, string)

// Appends something like `name="value"` to
// @string, taking care to escape any quotes or backslashes in @value.
//
// If @value is (non-ASCII) UTF-8, this will instead use RFC 5987
// encoding, just like [func@header_g_string_append_param].
func HeaderGStringAppendParamQuoted(StringVar *glib.String, NameVar string, ValueVar string) {
	core.LazyRegister(&xHeaderGStringAppendParamQuoted, "SOUP", "soup_header_g_string_append_param_quoted", false)

	xHeaderGStringAppendParamQuoted(StringVar, NameVar, ValueVar)
}

var xHeaderParseList func(string) uintptr

// Parses a header whose content is described by RFC2616 as `#something`.
//
// "something" does not itself contain commas, except as part of quoted-strings.
func HeaderParseList(HeaderVar string) *glib.SList {
	core.LazyRegister(&xHeaderParseList, "SOUP", "soup_header_parse_list", false)

	cret := xHeaderParseList(HeaderVar)
	if cret == 0 {
		return nil
	}
	return (*glib.SList)(unsafe.Pointer(cret))
}

var xHeaderParseParamList func(string) uintptr

// Parses a header which is a comma-delimited list of something like:
// `token [ "=" ( token | quoted-string ) ]`.
//
// Tokens that don't have an associated value will still be added to
// the resulting hash table, but with a %NULL value.
//
// This also handles RFC5987 encoding (which in HTTP is mostly used
// for giving UTF8-encoded filenames in the Content-Disposition
// header).
func HeaderParseParamList(HeaderVar string) *glib.HashTable {
	core.LazyRegister(&xHeaderParseParamList, "SOUP", "soup_header_parse_param_list", false)

	cret := xHeaderParseParamList(HeaderVar)
	if cret == 0 {
		return nil
	}
	return (*glib.HashTable)(unsafe.Pointer(cret))
}

var xHeaderParseParamListStrict func(string) uintptr

// A strict version of [func@header_parse_param_list]
// that bails out if there are duplicate parameters.
//
// Note that this function will treat RFC5987-encoded
// parameters as duplicated if an ASCII version is also
// present. For header fields that might contain
// RFC5987-encoded parameters, use
// [func@header_parse_param_list] instead.
func HeaderParseParamListStrict(HeaderVar string) *glib.HashTable {
	core.LazyRegister(&xHeaderParseParamListStrict, "SOUP", "soup_header_parse_param_list_strict", false)

	cret := xHeaderParseParamListStrict(HeaderVar)
	if cret == 0 {
		return nil
	}
	return (*glib.HashTable)(unsafe.Pointer(cret))
}

var xHeaderParseQualityList func(string, **glib.SList) uintptr

// Parses a header whose content is a list of items with optional
// "qvalue"s (eg, Accept, Accept-Charset, Accept-Encoding,
// Accept-Language, TE).
//
// If @unacceptable is not %NULL, then on return, it will contain the
// items with qvalue 0. Either way, those items will be removed from
// the main list.
func HeaderParseQualityList(HeaderVar string, UnacceptableVar **glib.SList) *glib.SList {
	core.LazyRegister(&xHeaderParseQualityList, "SOUP", "soup_header_parse_quality_list", false)

	cret := xHeaderParseQualityList(HeaderVar, UnacceptableVar)
	if cret == 0 {
		return nil
	}
	return (*glib.SList)(unsafe.Pointer(cret))
}

var xHeaderParseSemiParamList func(string) uintptr

// Parses a header which is a semicolon-delimited list of something
// like: `token [ "=" ( token | quoted-string ) ]`.
//
// Tokens that don't have an associated value will still be added to
// the resulting hash table, but with a %NULL value.
//
// This also handles RFC5987 encoding (which in HTTP is mostly used
// for giving UTF8-encoded filenames in the Content-Disposition
// header).
func HeaderParseSemiParamList(HeaderVar string) *glib.HashTable {
	core.LazyRegister(&xHeaderParseSemiParamList, "SOUP", "soup_header_parse_semi_param_list", false)

	cret := xHeaderParseSemiParamList(HeaderVar)
	if cret == 0 {
		return nil
	}
	return (*glib.HashTable)(unsafe.Pointer(cret))
}

var xHeaderParseSemiParamListStrict func(string) uintptr

// A strict version of [func@header_parse_semi_param_list]
// that bails out if there are duplicate parameters.
//
// Note that this function will treat RFC5987-encoded
// parameters as duplicated if an ASCII version is also
// present. For header fields that might contain
// RFC5987-encoded parameters, use
// [func@header_parse_semi_param_list] instead.
func HeaderParseSemiParamListStrict(HeaderVar string) *glib.HashTable {
	core.LazyRegister(&xHeaderParseSemiParamListStrict, "SOUP", "soup_header_parse_semi_param_list_strict", false)

	cret := xHeaderParseSemiParamListStrict(HeaderVar)
	if cret == 0 {
		return nil
	}
	return (*glib.HashTable)(unsafe.Pointer(cret))
}

var xHeadersParse func(string, int, *MessageHeaders) bool

// Parses the headers of an HTTP request or response in @str and
// stores the results in @dest.
//
// Beware that @dest may be modified even on failure.
//
// This is a low-level method; normally you would use
// [func@headers_parse_request] or [func@headers_parse_response].
func HeadersParse(StrVar string, LenVar int, DestVar *MessageHeaders) bool {
	core.LazyRegister(&xHeadersParse, "SOUP", "soup_headers_parse", false)

	cret := xHeadersParse(StrVar, LenVar, DestVar)
	return cret
}

var xHeadersParseRequest func(string, int, *MessageHeaders, *string, *string, *HTTPVersion) uint

// Parses the headers of an HTTP request in @str and stores the
// results in @req_method, @req_path, @ver, and @req_headers.
//
// Beware that @req_headers may be modified even on failure.
func HeadersParseRequest(StrVar string, LenVar int, ReqHeadersVar *MessageHeaders, ReqMethodVar *string, ReqPathVar *string, VerVar *HTTPVersion) uint {
	core.LazyRegister(&xHeadersParseRequest, "SOUP", "soup_headers_parse_request", false)

	cret := xHeadersParseRequest(StrVar, LenVar, ReqHeadersVar, ReqMethodVar, ReqPathVar, VerVar)
	return cret
}

var xHeadersParseResponse func(string, int, *MessageHeaders, *HTTPVersion, *uint, *string) bool

// Parses the headers of an HTTP response in @str and stores the
// results in @ver, @status_code, @reason_phrase, and @headers.
//
// Beware that @headers may be modified even on failure.
func HeadersParseResponse(StrVar string, LenVar int, HeadersVar *MessageHeaders, VerVar *HTTPVersion, StatusCodeVar *uint, ReasonPhraseVar *string) bool {
	core.LazyRegister(&xHeadersParseResponse, "SOUP", "soup_headers_parse_response", false)

	cret := xHeadersParseResponse(StrVar, LenVar, HeadersVar, VerVar, StatusCodeVar, ReasonPhraseVar)
	return cret
}

var xHeadersParseStatusLine func(string, *HTTPVersion, *uint, *string) bool

// Parses the HTTP Status-Line string in @status_line into @ver,
// @status_code, and @reason_phrase.
//
// @status_line must be terminated by either "\0" or "\r\n".
func HeadersParseStatusLine(StatusLineVar string, VerVar *HTTPVersion, StatusCodeVar *uint, ReasonPhraseVar *string) bool {
	core.LazyRegister(&xHeadersParseStatusLine, "SOUP", "soup_headers_parse_status_line", false)

	cret := xHeadersParseStatusLine(StatusLineVar, VerVar, StatusCodeVar, ReasonPhraseVar)
	return cret
}

func init() {
	core.SetPackageName("SOUP", "libsoup-3.0")
	core.SetSharedLibraries("SOUP", []string{"libsoup-3.0.so.0", "libsoup-3.0.0.dylib"})
}
