// Package soup was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package soup

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type ContentSnifferClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *ContentSnifferClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ContentSnifferClassNewFromInternalPtr(ptr uintptr) *ContentSnifferClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ContentSnifferClass)(rawPtr)
}

// Sniffs the mime type of messages.
//
// A [class@ContentSniffer] tries to detect the actual content type of
// the files that are being downloaded by looking at some of the data
// before the [class@Message] emits its [signal@Message::got-headers] signal.
// [class@ContentSniffer] implements [iface@SessionFeature], so you can add
// content sniffing to a session with [method@Session.add_feature] or
// [method@Session.add_feature_by_type].
type ContentSniffer struct {
	gobject.Object
}

var xContentSnifferGLibType func() types.GType

func ContentSnifferGLibType() types.GType {
	core.LazyRegister(&xContentSnifferGLibType, "SOUP", "soup_content_sniffer_get_type", false)
	return xContentSnifferGLibType()
}

func ContentSnifferNewFromInternalPtr(ptr uintptr) *ContentSniffer {
	cls := &ContentSniffer{}
	cls.Ptr = ptr
	return cls
}

var xNewContentSniffer func() uintptr

// Creates a new [class@ContentSniffer].
func NewContentSniffer() *ContentSniffer {
	core.LazyRegister(&xNewContentSniffer, "SOUP", "soup_content_sniffer_new", false)
	var cls *ContentSniffer

	cret := xNewContentSniffer()

	if cret == 0 {
		return nil
	}
	cls = &ContentSniffer{}
	cls.Ptr = cret
	return cls
}

var xContentSnifferSniff func(uintptr, uintptr, *glib.Bytes, **glib.HashTable) string

// Sniffs @buffer to determine its Content-Type.
//
// The result may also be influenced by the Content-Type declared in @msg's
// response headers.
func (x *ContentSniffer) Sniff(MsgVar *Message, BufferVar *glib.Bytes, ParamsVar **glib.HashTable) string {
	core.LazyRegister(&xContentSnifferSniff, "SOUP", "soup_content_sniffer_sniff", false)

	cret := xContentSnifferSniff(x.GoPointer(), MsgVar.GoPointer(), BufferVar, ParamsVar)
	return cret
}

func (c *ContentSniffer) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *ContentSniffer) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("SOUP", "libsoup-3.0")
	core.SetSharedLibraries("SOUP", []string{"libsoup-3.0.so.0", "libsoup-3.0.0.dylib"})
}
