// Package soup was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package soup

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type WebsocketExtensionDeflateClass struct {
	_ structs.HostLayout

	ParentClass WebsocketExtensionClass
}

func (x *WebsocketExtensionDeflateClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func WebsocketExtensionDeflateClassNewFromInternalPtr(ptr uintptr) *WebsocketExtensionDeflateClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*WebsocketExtensionDeflateClass)(rawPtr)
}

// A SoupWebsocketExtensionDeflate is a [class@WebsocketExtension]
// implementing permessage-deflate (RFC 7692).
//
// This extension is used by default in a [class@Session] when [class@WebsocketExtensionManager]
// feature is present, and always used by [class@Server].
type WebsocketExtensionDeflate struct {
	WebsocketExtension
}

var xWebsocketExtensionDeflateGLibType func() types.GType

func WebsocketExtensionDeflateGLibType() types.GType {
	core.LazyRegister(&xWebsocketExtensionDeflateGLibType, "SOUP", "soup_websocket_extension_deflate_get_type", false)
	return xWebsocketExtensionDeflateGLibType()
}

func WebsocketExtensionDeflateNewFromInternalPtr(ptr uintptr) *WebsocketExtensionDeflate {
	cls := &WebsocketExtensionDeflate{}
	cls.Ptr = ptr
	return cls
}

func (c *WebsocketExtensionDeflate) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *WebsocketExtensionDeflate) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("SOUP", "libsoup-3.0")
	core.SetSharedLibraries("SOUP", []string{"libsoup-3.0.so.0", "libsoup-3.0.0.dylib"})
}
