// Package soup was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package soup

import (
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// HTTP "Basic" authentication.
//
// [class@Session]s support this by default; if you want to disable
// support for it, call [method@Session.remove_feature_by_type],
// passing %SOUP_TYPE_AUTH_BASIC.
type AuthBasic struct {
	Auth
}

var xAuthBasicGLibType func() types.GType

func AuthBasicGLibType() types.GType {
	core.LazyRegister(&xAuthBasicGLibType, "SOUP", "soup_auth_basic_get_type", false)
	return xAuthBasicGLibType()
}

func AuthBasicNewFromInternalPtr(ptr uintptr) *AuthBasic {
	cls := &AuthBasic{}
	cls.Ptr = ptr
	return cls
}

func (c *AuthBasic) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *AuthBasic) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("SOUP", "libsoup-3.0")
	core.SetSharedLibraries("SOUP", []string{"libsoup-3.0.so.0", "libsoup-3.0.0.dylib"})
}
