// Package soup was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package soup

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type ContentDecoderClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *ContentDecoderClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ContentDecoderClassNewFromInternalPtr(ptr uintptr) *ContentDecoderClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ContentDecoderClass)(rawPtr)
}

// Handles decoding of HTTP messages.
//
// [class@ContentDecoder] handles adding the "Accept-Encoding" header on
// outgoing messages, and processing the "Content-Encoding" header on
// incoming ones. Currently it supports the "gzip", "deflate", and "br"
// content codings.
//
// A [class@ContentDecoder] will automatically be
// added to the session by default. (You can use
// [method@Session.remove_feature_by_type] if you don't
// want this.)
//
// If [class@ContentDecoder] successfully decodes the Content-Encoding,
// the message body will contain the decoded data; however, the message headers
// will be unchanged (and so "Content-Encoding" will still be present,
// "Content-Length" will describe the original encoded length, etc).
//
// If "Content-Encoding" contains any encoding types that
// [class@ContentDecoder] doesn't recognize, then none of the encodings
// will be decoded.
//
// (Note that currently there is no way to (automatically) use
// Content-Encoding when sending a request body, or to pick specific
// encoding types to support.)
type ContentDecoder struct {
	gobject.Object
}

var xContentDecoderGLibType func() types.GType

func ContentDecoderGLibType() types.GType {
	core.LazyRegister(&xContentDecoderGLibType, "SOUP", "soup_content_decoder_get_type", false)
	return xContentDecoderGLibType()
}

func ContentDecoderNewFromInternalPtr(ptr uintptr) *ContentDecoder {
	cls := &ContentDecoder{}
	cls.Ptr = ptr
	return cls
}

func (c *ContentDecoder) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *ContentDecoder) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("SOUP", "libsoup-3.0")
	core.SetSharedLibraries("SOUP", []string{"libsoup-3.0.so.0", "libsoup-3.0.0.dylib"})
}
