// Package soup was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package soup

import (
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// HTTP-based NTLM authentication.
//
// [class@Session]s do not support this type by default; if you want to
// enable support for it, call [method@Session.add_feature_by_type],
// passing %SOUP_TYPE_AUTH_NTLM.
type AuthNTLM struct {
	Auth
}

var xAuthNTLMGLibType func() types.GType

func AuthNTLMGLibType() types.GType {
	core.LazyRegister(&xAuthNTLMGLibType, "SOUP", "soup_auth_ntlm_get_type", false)
	return xAuthNTLMGLibType()
}

func AuthNTLMNewFromInternalPtr(ptr uintptr) *AuthNTLM {
	cls := &AuthNTLM{}
	cls.Ptr = ptr
	return cls
}

func (c *AuthNTLM) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *AuthNTLM) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("SOUP", "libsoup-3.0")
	core.SetSharedLibraries("SOUP", []string{"libsoup-3.0.so.0", "libsoup-3.0.0.dylib"})
}
