// Package soup was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package soup

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type WebsocketExtensionManagerClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *WebsocketExtensionManagerClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func WebsocketExtensionManagerClassNewFromInternalPtr(ptr uintptr) *WebsocketExtensionManagerClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*WebsocketExtensionManagerClass)(rawPtr)
}

// SoupWebsocketExtensionManager is the [iface@SessionFeature] that handles WebSockets
// extensions for a [class@Session].
//
// A [class@WebsocketExtensionManager] is added to the session by default, and normally
// you don't need to worry about it at all. However, if you want to
// disable WebSocket extensions, you can remove the feature from the
// session with [method@Session.remove_feature_by_type] or disable it on
// individual requests with [method@Message.disable_feature].
type WebsocketExtensionManager struct {
	gobject.Object
}

var xWebsocketExtensionManagerGLibType func() types.GType

func WebsocketExtensionManagerGLibType() types.GType {
	core.LazyRegister(&xWebsocketExtensionManagerGLibType, "SOUP", "soup_websocket_extension_manager_get_type", false)
	return xWebsocketExtensionManagerGLibType()
}

func WebsocketExtensionManagerNewFromInternalPtr(ptr uintptr) *WebsocketExtensionManager {
	cls := &WebsocketExtensionManager{}
	cls.Ptr = ptr
	return cls
}

func (c *WebsocketExtensionManager) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *WebsocketExtensionManager) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("SOUP", "libsoup-3.0")
	core.SetSharedLibraries("SOUP", []string{"libsoup-3.0.so.0", "libsoup-3.0.0.dylib"})
}
