// Package soup was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package soup

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gio"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type ServerMessageClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *ServerMessageClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ServerMessageClassNewFromInternalPtr(ptr uintptr) *ServerMessageClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ServerMessageClass)(rawPtr)
}

// An HTTP server request and response pair.
//
// A [class@ServerMessage] represents an HTTP message that is being sent or
// received on a [class@Server].
//
// [class@Server] will create [class@ServerMessage]s automatically for
// incoming requests, which your application will receive via handlers.
//
// Note that libsoup's terminology here does not quite match the HTTP
// specification: in RFC 2616, an "HTTP-message" is *either* a Request, *or* a
// Response. In libsoup, a [class@ServerMessage] combines both the request and the
// response.
type ServerMessage struct {
	gobject.Object
}

var xServerMessageGLibType func() types.GType

func ServerMessageGLibType() types.GType {
	core.LazyRegister(&xServerMessageGLibType, "SOUP", "soup_server_message_get_type", false)
	return xServerMessageGLibType()
}

func ServerMessageNewFromInternalPtr(ptr uintptr) *ServerMessage {
	cls := &ServerMessage{}
	cls.Ptr = ptr
	return cls
}

var xServerMessageGetHttpVersion func(uintptr) HTTPVersion

// Get the HTTP version of @msg.
func (x *ServerMessage) GetHttpVersion() HTTPVersion {
	core.LazyRegister(&xServerMessageGetHttpVersion, "SOUP", "soup_server_message_get_http_version", false)

	cret := xServerMessageGetHttpVersion(x.GoPointer())
	return cret
}

var xServerMessageGetLocalAddress func(uintptr) uintptr

// Retrieves the [class@Gio.SocketAddress] associated with the local end
// of a connection.
func (x *ServerMessage) GetLocalAddress() *gio.SocketAddress {
	core.LazyRegister(&xServerMessageGetLocalAddress, "SOUP", "soup_server_message_get_local_address", false)
	var cls *gio.SocketAddress

	cret := xServerMessageGetLocalAddress(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &gio.SocketAddress{}
	cls.Ptr = cret
	return cls
}

var xServerMessageGetMethod func(uintptr) string

// Get the HTTP method of @msg.
func (x *ServerMessage) GetMethod() string {
	core.LazyRegister(&xServerMessageGetMethod, "SOUP", "soup_server_message_get_method", false)

	cret := xServerMessageGetMethod(x.GoPointer())
	return cret
}

var xServerMessageGetReasonPhrase func(uintptr) string

// Get the HTTP reason phrase of @msg.
func (x *ServerMessage) GetReasonPhrase() string {
	core.LazyRegister(&xServerMessageGetReasonPhrase, "SOUP", "soup_server_message_get_reason_phrase", false)

	cret := xServerMessageGetReasonPhrase(x.GoPointer())
	return cret
}

var xServerMessageGetRemoteAddress func(uintptr) uintptr

// Retrieves the [class@Gio.SocketAddress] associated with the remote end
// of a connection.
func (x *ServerMessage) GetRemoteAddress() *gio.SocketAddress {
	core.LazyRegister(&xServerMessageGetRemoteAddress, "SOUP", "soup_server_message_get_remote_address", false)
	var cls *gio.SocketAddress

	cret := xServerMessageGetRemoteAddress(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &gio.SocketAddress{}
	cls.Ptr = cret
	return cls
}

var xServerMessageGetRemoteHost func(uintptr) string

// Retrieves the IP address associated with the remote end of a
// connection.
func (x *ServerMessage) GetRemoteHost() string {
	core.LazyRegister(&xServerMessageGetRemoteHost, "SOUP", "soup_server_message_get_remote_host", false)

	cret := xServerMessageGetRemoteHost(x.GoPointer())
	return cret
}

var xServerMessageGetRequestBody func(uintptr) uintptr

// Get the request body of @msg.
func (x *ServerMessage) GetRequestBody() *MessageBody {
	core.LazyRegister(&xServerMessageGetRequestBody, "SOUP", "soup_server_message_get_request_body", false)

	cret := xServerMessageGetRequestBody(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*MessageBody)(unsafe.Pointer(cret))
}

var xServerMessageGetRequestHeaders func(uintptr) uintptr

// Get the request headers of @msg.
func (x *ServerMessage) GetRequestHeaders() *MessageHeaders {
	core.LazyRegister(&xServerMessageGetRequestHeaders, "SOUP", "soup_server_message_get_request_headers", false)

	cret := xServerMessageGetRequestHeaders(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*MessageHeaders)(unsafe.Pointer(cret))
}

var xServerMessageGetResponseBody func(uintptr) uintptr

// Get the response body of @msg.
func (x *ServerMessage) GetResponseBody() *MessageBody {
	core.LazyRegister(&xServerMessageGetResponseBody, "SOUP", "soup_server_message_get_response_body", false)

	cret := xServerMessageGetResponseBody(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*MessageBody)(unsafe.Pointer(cret))
}

var xServerMessageGetResponseHeaders func(uintptr) uintptr

// Get the response headers of @msg.
func (x *ServerMessage) GetResponseHeaders() *MessageHeaders {
	core.LazyRegister(&xServerMessageGetResponseHeaders, "SOUP", "soup_server_message_get_response_headers", false)

	cret := xServerMessageGetResponseHeaders(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*MessageHeaders)(unsafe.Pointer(cret))
}

var xServerMessageGetSocket func(uintptr) uintptr

// Retrieves the [class@Gio.Socket] that @msg is associated with.
//
// If you are using this method to observe when multiple requests are
// made on the same persistent HTTP connection (eg, as the ntlm-test
// test program does), you will need to pay attention to socket
// destruction as well (eg, by using weak references), so that you do
// not get fooled when the allocator reuses the memory address of a
// previously-destroyed socket to represent a new socket.
func (x *ServerMessage) GetSocket() *gio.Socket {
	core.LazyRegister(&xServerMessageGetSocket, "SOUP", "soup_server_message_get_socket", false)
	var cls *gio.Socket

	cret := xServerMessageGetSocket(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &gio.Socket{}
	cls.Ptr = cret
	return cls
}

var xServerMessageGetStatus func(uintptr) uint

// Get the HTTP status code of @msg.
func (x *ServerMessage) GetStatus() uint {
	core.LazyRegister(&xServerMessageGetStatus, "SOUP", "soup_server_message_get_status", false)

	cret := xServerMessageGetStatus(x.GoPointer())
	return cret
}

var xServerMessageGetTlsPeerCertificate func(uintptr) uintptr

// Gets the peer's #GTlsCertificate associated with @msg's connection.
// Note that this is not set yet during the emission of
// SoupServerMessage::accept-certificate signal.
func (x *ServerMessage) GetTlsPeerCertificate() *gio.TlsCertificate {
	core.LazyRegister(&xServerMessageGetTlsPeerCertificate, "SOUP", "soup_server_message_get_tls_peer_certificate", false)
	var cls *gio.TlsCertificate

	cret := xServerMessageGetTlsPeerCertificate(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &gio.TlsCertificate{}
	cls.Ptr = cret
	return cls
}

var xServerMessageGetTlsPeerCertificateErrors func(uintptr) gio.TlsCertificateFlags

// Gets the errors associated with validating @msg's TLS peer certificate.
// Note that this is not set yet during the emission of
// SoupServerMessage::accept-certificate signal.
func (x *ServerMessage) GetTlsPeerCertificateErrors() gio.TlsCertificateFlags {
	core.LazyRegister(&xServerMessageGetTlsPeerCertificateErrors, "SOUP", "soup_server_message_get_tls_peer_certificate_errors", false)

	cret := xServerMessageGetTlsPeerCertificateErrors(x.GoPointer())
	return cret
}

var xServerMessageGetUri func(uintptr) uintptr

// Get @msg's URI.
func (x *ServerMessage) GetUri() *glib.Uri {
	core.LazyRegister(&xServerMessageGetUri, "SOUP", "soup_server_message_get_uri", false)

	cret := xServerMessageGetUri(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*glib.Uri)(unsafe.Pointer(cret))
}

var xServerMessageIsOptionsPing func(uintptr) bool

// Gets if @msg represents an OPTIONS message with the path `*`.
func (x *ServerMessage) IsOptionsPing() bool {
	core.LazyRegister(&xServerMessageIsOptionsPing, "SOUP", "soup_server_message_is_options_ping", false)

	cret := xServerMessageIsOptionsPing(x.GoPointer())
	return cret
}

var xServerMessagePause func(uintptr)

// Pauses I/O on @msg.
//
// This can be used when you need to return from the server handler without
// having the full response ready yet. Use [method@ServerMessage.unpause] to
// resume I/O.
func (x *ServerMessage) Pause() {
	core.LazyRegister(&xServerMessagePause, "SOUP", "soup_server_message_pause", false)

	xServerMessagePause(x.GoPointer())
}

var xServerMessageSetHttpVersion func(uintptr, HTTPVersion)

// Set the HTTP version of @msg.
func (x *ServerMessage) SetHttpVersion(VersionVar HTTPVersion) {
	core.LazyRegister(&xServerMessageSetHttpVersion, "SOUP", "soup_server_message_set_http_version", false)

	xServerMessageSetHttpVersion(x.GoPointer(), VersionVar)
}

var xServerMessageSetRedirect func(uintptr, uint, string)

// Sets @msg's status_code to @status_code and adds a Location header
// pointing to @redirect_uri. Use this from a [class@Server] when you
// want to redirect the client to another URI.
//
// @redirect_uri can be a relative URI, in which case it is
// interpreted relative to @msg's current URI. In particular, if
// @redirect_uri is just a path, it will replace the path
// *and query* of @msg's URI.
func (x *ServerMessage) SetRedirect(StatusCodeVar uint, RedirectUriVar string) {
	core.LazyRegister(&xServerMessageSetRedirect, "SOUP", "soup_server_message_set_redirect", false)

	xServerMessageSetRedirect(x.GoPointer(), StatusCodeVar, RedirectUriVar)
}

var xServerMessageSetResponse func(uintptr, uintptr, MemoryUse, uintptr, uint)

// Convenience function to set the response body of a [class@ServerMessage]. If
// @content_type is %NULL, the response body must be empty as well.
func (x *ServerMessage) SetResponse(ContentTypeVar *string, RespUseVar MemoryUse, RespBodyVar *string, RespLengthVar uint) {
	core.LazyRegister(&xServerMessageSetResponse, "SOUP", "soup_server_message_set_response", false)

	ContentTypeVarPtr := core.GStrdupNullable(ContentTypeVar)
	defer core.GFreeNullable(ContentTypeVarPtr)

	RespBodyVarPtr := core.GStrdupNullable(RespBodyVar)
	defer core.GFreeNullable(RespBodyVarPtr)

	xServerMessageSetResponse(x.GoPointer(), ContentTypeVarPtr, RespUseVar, RespBodyVarPtr, RespLengthVar)
}

var xServerMessageSetStatus func(uintptr, uint, uintptr)

// Sets @msg's status code to @status_code.
//
// If @status_code is a known value and @reason_phrase is %NULL, the
// reason_phrase will be set automatically.
func (x *ServerMessage) SetStatus(StatusCodeVar uint, ReasonPhraseVar *string) {
	core.LazyRegister(&xServerMessageSetStatus, "SOUP", "soup_server_message_set_status", false)

	ReasonPhraseVarPtr := core.GStrdupNullable(ReasonPhraseVar)
	defer core.GFreeNullable(ReasonPhraseVarPtr)

	xServerMessageSetStatus(x.GoPointer(), StatusCodeVar, ReasonPhraseVarPtr)
}

var xServerMessageStealConnection func(uintptr) uintptr

// "Steals" the HTTP connection associated with @msg from its [class@Server]. This
// happens immediately, regardless of the current state of the connection; if
// the response to @msg has not yet finished being sent, then it will be
// discarded; you can steal the connection from a
// [signal@ServerMessage::wrote-informational] or
// [signal@ServerMessage::wrote-body] signal handler if you need to wait for
// part or all of the response to be sent.
//
// Note that when calling this function from C, @msg will most
// likely be freed as a side effect.
func (x *ServerMessage) StealConnection() *gio.IOStream {
	core.LazyRegister(&xServerMessageStealConnection, "SOUP", "soup_server_message_steal_connection", false)
	var cls *gio.IOStream

	cret := xServerMessageStealConnection(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &gio.IOStream{}
	cls.Ptr = cret
	return cls
}

var xServerMessageUnpause func(uintptr)

// Resumes I/O on @msg.
//
// Use this to resume after calling [method@ServerMessage.pause], or after
// adding a new chunk to a chunked response. I/O won't actually resume until you
// return to the main loop.
func (x *ServerMessage) Unpause() {
	core.LazyRegister(&xServerMessageUnpause, "SOUP", "soup_server_message_unpause", false)

	xServerMessageUnpause(x.GoPointer())
}

func (c *ServerMessage) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *ServerMessage) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// Emitted during the @msg's connection TLS handshake
// after client TLS certificate has been received.
// You can return %TRUE to accept @tls_certificate despite
// @tls_errors.
func (x *ServerMessage) ConnectAcceptCertificate(cb *func(ServerMessage, uintptr, gio.TlsCertificateFlags) bool) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("soup.ServerMessage.AcceptCertificate", func(clsPtr uintptr, TlsPeerCertificateVarp uintptr, TlsPeerErrorsVarp gio.TlsCertificateFlags, signalData uintptr) bool {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			var zero bool
			return zero
		}
		cb, ok := handler.(*func(ServerMessage, uintptr, gio.TlsCertificateFlags) bool)
		if !ok || cb == nil || *cb == nil {
			var zero bool
			return zero
		}
		fa := ServerMessage{}
		fa.Ptr = clsPtr
		cbFn := *cb

		return cbFn(fa, TlsPeerCertificateVarp, TlsPeerErrorsVarp)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "accept-certificate", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted when the @msg's socket is connected and the TLS handshake completed.
func (x *ServerMessage) ConnectConnected(cb *func(ServerMessage)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("soup.ServerMessage.Connected", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(ServerMessage))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := ServerMessage{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "connected", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted when the @msg's socket is disconnected.
func (x *ServerMessage) ConnectDisconnected(cb *func(ServerMessage)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("soup.ServerMessage.Disconnected", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(ServerMessage))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := ServerMessage{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "disconnected", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted when all HTTP processing is finished for a message.
// (After [signal@ServerMessage::wrote-body]).
func (x *ServerMessage) ConnectFinished(cb *func(ServerMessage)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("soup.ServerMessage.Finished", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(ServerMessage))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := ServerMessage{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "finished", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted after receiving the complete request body.
func (x *ServerMessage) ConnectGotBody(cb *func(ServerMessage)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("soup.ServerMessage.GotBody", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(ServerMessage))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := ServerMessage{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "got-body", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted after receiving a chunk of a message body.
//
// Note that "chunk" in this context means any subpiece of the body, not
// necessarily the specific HTTP 1.1 chunks sent by the other side.
func (x *ServerMessage) ConnectGotChunk(cb *func(ServerMessage, uintptr)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("soup.ServerMessage.GotChunk", func(clsPtr uintptr, ChunkVarp uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(ServerMessage, uintptr))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := ServerMessage{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa, ChunkVarp)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "got-chunk", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted after receiving the Request-Line and request headers.
func (x *ServerMessage) ConnectGotHeaders(cb *func(ServerMessage)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("soup.ServerMessage.GotHeaders", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(ServerMessage))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := ServerMessage{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "got-headers", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted immediately after writing the complete response body for a
// message.
func (x *ServerMessage) ConnectWroteBody(cb *func(ServerMessage)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("soup.ServerMessage.WroteBody", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(ServerMessage))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := ServerMessage{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "wrote-body", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted immediately after writing a portion of the message
// body to the network.
func (x *ServerMessage) ConnectWroteBodyData(cb *func(ServerMessage, uint)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("soup.ServerMessage.WroteBodyData", func(clsPtr uintptr, ChunkSizeVarp uint, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(ServerMessage, uint))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := ServerMessage{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa, ChunkSizeVarp)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "wrote-body-data", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted immediately after writing a body chunk for a message.
//
// Note that this signal is not parallel to
// [signal@ServerMessage::got-chunk]; it is emitted only when a complete
// chunk (added with [method@MessageBody.append] or
// [method@MessageBody.append_bytes] has been written. To get
// more useful continuous progress information, use
// [signal@ServerMessage::wrote-body-data].
func (x *ServerMessage) ConnectWroteChunk(cb *func(ServerMessage)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("soup.ServerMessage.WroteChunk", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(ServerMessage))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := ServerMessage{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "wrote-chunk", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted immediately after writing the response headers for a
// message.
func (x *ServerMessage) ConnectWroteHeaders(cb *func(ServerMessage)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("soup.ServerMessage.WroteHeaders", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(ServerMessage))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := ServerMessage{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "wrote-headers", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted immediately after writing a 1xx (Informational) response.
func (x *ServerMessage) ConnectWroteInformational(cb *func(ServerMessage)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("soup.ServerMessage.WroteInformational", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(ServerMessage))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := ServerMessage{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "wrote-informational", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

func init() {
	core.SetPackageName("SOUP", "libsoup-3.0")
	core.SetSharedLibraries("SOUP", []string{"libsoup-3.0.so.0", "libsoup-3.0.0.dylib"})
}
