// Package soup was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package soup

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// Callback used by [class@AuthDomainBasic] for authentication purposes.
//
// The application should verify that @username and @password and valid
// and return %TRUE or %FALSE.
//
// If you are maintaining your own password database (rather than
// using the password to authenticate against some other system like
// PAM or a remote server), you should make sure you know what you are
// doing. In particular, don't store cleartext passwords, or
// easily-computed hashes of cleartext passwords, even if you don't
// care that much about the security of your server, because users
// will frequently use the same password for multiple sites, and so
// compromising any site with a cleartext (or easily-cracked) password
// database may give attackers access to other more-interesting sites
// as well.
type AuthDomainBasicAuthCallback func(uintptr, uintptr, string, string, uintptr) bool

type AuthDomainBasicClass struct {
	_ structs.HostLayout

	ParentClass AuthDomainClass
}

func (x *AuthDomainBasicClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func AuthDomainBasicClassNewFromInternalPtr(ptr uintptr) *AuthDomainBasicClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*AuthDomainBasicClass)(rawPtr)
}

// Server-side "Basic" authentication.
//
// [class@AuthDomainBasic] handles the server side of HTTP "Basic" (ie,
// cleartext password) authentication.
type AuthDomainBasic struct {
	AuthDomain
}

var xAuthDomainBasicGLibType func() types.GType

func AuthDomainBasicGLibType() types.GType {
	core.LazyRegister(&xAuthDomainBasicGLibType, "SOUP", "soup_auth_domain_basic_get_type", false)
	return xAuthDomainBasicGLibType()
}

func AuthDomainBasicNewFromInternalPtr(ptr uintptr) *AuthDomainBasic {
	cls := &AuthDomainBasic{}
	cls.Ptr = ptr
	return cls
}

var xNewAuthDomainBasic func(string, ...interface{}) uintptr

// Creates a [class@AuthDomainBasic].
//
// You must set the [property@AuthDomain:realm] property, to indicate the realm
// name to be returned with the authentication challenge to the client. Other
// parameters are optional.
func NewAuthDomainBasic(Optname1Var string, varArgs ...interface{}) *AuthDomainBasic {
	core.LazyRegister(&xNewAuthDomainBasic, "SOUP", "soup_auth_domain_basic_new", false)
	var cls *AuthDomainBasic

	cret := xNewAuthDomainBasic(Optname1Var, varArgs...)

	if cret == 0 {
		return nil
	}
	cls = &AuthDomainBasic{}
	cls.Ptr = cret
	return cls
}

var xAuthDomainBasicSetAuthCallback func(uintptr, uintptr, uintptr, uintptr)

// Sets the callback that @domain will use to authenticate incoming
// requests.
//
// For each request containing authorization, @domain will invoke the callback,
// and then either accept or reject the request based on @callback's return
// value.
//
// You can also set the auth callback by setting the
// [property@AuthDomainBasic:auth-callback] and
// [property@AuthDomainBasic:auth-data] properties, which can also be used to
// set the callback at construct time.
func (x *AuthDomainBasic) SetAuthCallback(CallbackVar *AuthDomainBasicAuthCallback, UserDataVar uintptr, DnotifyVar *glib.DestroyNotify) {
	core.LazyRegister(&xAuthDomainBasicSetAuthCallback, "SOUP", "soup_auth_domain_basic_set_auth_callback", false)

	xAuthDomainBasicSetAuthCallback(x.GoPointer(), glib.NewCallback(CallbackVar), UserDataVar, glib.NewCallbackNullable(DnotifyVar))
}

func (c *AuthDomainBasic) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *AuthDomainBasic) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyAuthData sets the "auth-data" property.
// The data to pass to the [callback@AuthDomainBasicAuthCallback].
func (x *AuthDomainBasic) SetPropertyAuthData(value uintptr) {
	var v gobject.Value
	v.Init(gobject.TypePointerVal)
	v.SetPointer(value)
	x.SetProperty("auth-data", &v)
}

// GetPropertyAuthData gets the "auth-data" property.
// The data to pass to the [callback@AuthDomainBasicAuthCallback].
func (x *AuthDomainBasic) GetPropertyAuthData() uintptr {
	var v gobject.Value
	x.GetProperty("auth-data", &v)
	return v.GetPointer()
}

func init() {
	core.SetPackageName("SOUP", "libsoup-3.0")
	core.SetSharedLibraries("SOUP", []string{"libsoup-3.0.so.0", "libsoup-3.0.0.dylib"})
}
