// Package soup was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package soup

import (
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// HTTP "Digest" authentication.
//
// [class@Session]s support this by default; if you want to disable
// support for it, call [method@Session.remove_feature_by_type]
// passing %SOUP_TYPE_AUTH_DIGEST.
type AuthDigest struct {
	Auth
}

var xAuthDigestGLibType func() types.GType

func AuthDigestGLibType() types.GType {
	core.LazyRegister(&xAuthDigestGLibType, "SOUP", "soup_auth_digest_get_type", false)
	return xAuthDigestGLibType()
}

func AuthDigestNewFromInternalPtr(ptr uintptr) *AuthDigest {
	cls := &AuthDigest{}
	cls.Ptr = ptr
	return cls
}

func (c *AuthDigest) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *AuthDigest) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("SOUP", "libsoup-3.0")
	core.SetSharedLibraries("SOUP", []string{"libsoup-3.0.so.0", "libsoup-3.0.0.dylib"})
}
