// Package soup was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package soup

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type CacheClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass

	xGetCacheability uintptr

	Padding [4]uintptr
}

func (x *CacheClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func CacheClassNewFromInternalPtr(ptr uintptr) *CacheClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*CacheClass)(rawPtr)
}

// OverrideGetCacheability sets the "get_cacheability" callback function.
func (x *CacheClass) OverrideGetCacheability(cb func(*Cache, *Message) Cacheability) {
	if cb == nil {
		x.xGetCacheability = 0
	} else {
		x.xGetCacheability = purego.NewCallback(func(CacheVarp uintptr, MsgVarp uintptr) Cacheability {
			return cb(CacheNewFromInternalPtr(CacheVarp), MessageNewFromInternalPtr(MsgVarp))
		})
	}
}

// GetGetCacheability gets the "get_cacheability" callback function.
func (x *CacheClass) GetGetCacheability() func(*Cache, *Message) Cacheability {
	if x.xGetCacheability == 0 {
		return nil
	}
	var rawCallback func(CacheVarp uintptr, MsgVarp uintptr) Cacheability
	purego.RegisterFunc(&rawCallback, x.xGetCacheability)
	return func(CacheVar *Cache, MsgVar *Message) Cacheability {
		return rawCallback(CacheVar.GoPointer(), MsgVar.GoPointer())
	}
}

// Indicates if a message should or shouldn't be cached.
type Cacheability int

var xCacheabilityGLibType func() types.GType

func CacheabilityGLibType() types.GType {
	core.LazyRegister(&xCacheabilityGLibType, "SOUP", "soup_cacheability_get_type", false)
	return xCacheabilityGLibType()
}

const (

	// The message should be cached
	CacheCacheableValue Cacheability = 1
	// The message shouldn't be cached
	CacheUncacheableValue Cacheability = 2
	// The messages cache should be invalidated
	CacheInvalidatesValue Cacheability = 4
	// The messages cache should be updated
	CacheValidatesValue Cacheability = 8
)

// The type of cache; this affects what kinds of responses will be
// saved.
type CacheType int

var xCacheTypeGLibType func() types.GType

func CacheTypeGLibType() types.GType {
	core.LazyRegister(&xCacheTypeGLibType, "SOUP", "soup_cache_type_get_type", false)
	return xCacheTypeGLibType()
}

const (

	// a single-user cache
	CacheSingleUserValue CacheType = 0
	// a shared cache
	CacheSharedValue CacheType = 1
)

// File-based cache for HTTP resources.
type Cache struct {
	gobject.Object
}

var xCacheGLibType func() types.GType

func CacheGLibType() types.GType {
	core.LazyRegister(&xCacheGLibType, "SOUP", "soup_cache_get_type", false)
	return xCacheGLibType()
}

func CacheNewFromInternalPtr(ptr uintptr) *Cache {
	cls := &Cache{}
	cls.Ptr = ptr
	return cls
}

var xNewCache func(uintptr, CacheType) uintptr

// Creates a new #SoupCache.
func NewCache(CacheDirVar *string, CacheTypeVar CacheType) *Cache {
	core.LazyRegister(&xNewCache, "SOUP", "soup_cache_new", false)
	var cls *Cache

	CacheDirVarPtr := core.GStrdupNullable(CacheDirVar)
	defer core.GFreeNullable(CacheDirVarPtr)

	cret := xNewCache(CacheDirVarPtr, CacheTypeVar)

	if cret == 0 {
		return nil
	}
	cls = &Cache{}
	cls.Ptr = cret
	return cls
}

var xCacheClear func(uintptr)

// Will remove all entries in the @cache plus all the cache files.
//
// This is not thread safe and must be called only from the thread that created the [class@Cache]
func (x *Cache) Clear() {
	core.LazyRegister(&xCacheClear, "SOUP", "soup_cache_clear", false)

	xCacheClear(x.GoPointer())
}

var xCacheDump func(uintptr)

// Synchronously writes the cache index out to disk.
//
// Contrast with [method@Cache.flush], which writes pending cache *entries* to
// disk.
//
// You must call this before exiting if you want your cache data to
// persist between sessions.
//
// This is not thread safe and must be called only from the thread that created the [class@Cache]
func (x *Cache) Dump() {
	core.LazyRegister(&xCacheDump, "SOUP", "soup_cache_dump", false)

	xCacheDump(x.GoPointer())
}

var xCacheFlush func(uintptr)

// Forces all pending writes in the @cache to be
// committed to disk.
//
// For doing so it will iterate the [struct@GLib.MainContext] associated with
// @cache's session as long as needed.
//
// Contrast with [method@Cache.dump], which writes out the cache index file.
func (x *Cache) Flush() {
	core.LazyRegister(&xCacheFlush, "SOUP", "soup_cache_flush", false)

	xCacheFlush(x.GoPointer())
}

var xCacheGetMaxSize func(uintptr) uint

// Gets the maximum size of the cache.
func (x *Cache) GetMaxSize() uint {
	core.LazyRegister(&xCacheGetMaxSize, "SOUP", "soup_cache_get_max_size", false)

	cret := xCacheGetMaxSize(x.GoPointer())
	return cret
}

var xCacheLoad func(uintptr)

// Loads the contents of @cache's index into memory.
//
// This is not thread safe and must be called only from the thread that created the [class@Cache]
func (x *Cache) Load() {
	core.LazyRegister(&xCacheLoad, "SOUP", "soup_cache_load", false)

	xCacheLoad(x.GoPointer())
}

var xCacheSetMaxSize func(uintptr, uint)

// Sets the maximum size of the cache.
func (x *Cache) SetMaxSize(MaxSizeVar uint) {
	core.LazyRegister(&xCacheSetMaxSize, "SOUP", "soup_cache_set_max_size", false)

	xCacheSetMaxSize(x.GoPointer(), MaxSizeVar)
}

func (c *Cache) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *Cache) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyCacheDir sets the "cache-dir" property.
// The directory to store the cache files.
func (x *Cache) SetPropertyCacheDir(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(&value)
	x.SetProperty("cache-dir", &v)
}

// GetPropertyCacheDir gets the "cache-dir" property.
// The directory to store the cache files.
func (x *Cache) GetPropertyCacheDir() string {
	var v gobject.Value
	x.GetProperty("cache-dir", &v)
	return v.GetString()
}

func init() {
	core.SetPackageName("SOUP", "libsoup-3.0")
	core.SetSharedLibraries("SOUP", []string{"libsoup-3.0.so.0", "libsoup-3.0.0.dylib"})
}
