// Package soup was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package soup

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// The interface implemented by [iface@SessionFeature]s.
type SessionFeatureInterface struct {
	_ structs.HostLayout
}

func (x *SessionFeatureInterface) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func SessionFeatureInterfaceNewFromInternalPtr(ptr uintptr) *SessionFeatureInterface {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*SessionFeatureInterface)(rawPtr)
}

// Interface for miscellaneous [class@Session] features.
//
// [iface@SessionFeature] is the interface used by classes that extend
// the functionality of a [class@Session]. Some features like HTTP
// authentication handling are implemented internally via
// [iface@SessionFeature]s. Other features can be added to the session
// by the application. (Eg, [class@Logger], [class@CookieJar].)
//
// See [method@Session.add_feature], etc, to add a feature to a session.
type SessionFeature interface {
	GoPointer() uintptr
	SetGoPointer(uintptr)
}

var xSessionFeatureGLibType func() types.GType

func SessionFeatureGLibType() types.GType {
	core.LazyRegister(&xSessionFeatureGLibType, "SOUP", "soup_session_feature_get_type", false)
	return xSessionFeatureGLibType()
}

type SessionFeatureBase struct {
	Ptr uintptr
}

func (x *SessionFeatureBase) GoPointer() uintptr {
	if x == nil {
		return 0
	}
	return x.Ptr
}

func (x *SessionFeatureBase) SetGoPointer(ptr uintptr) {
	x.Ptr = ptr
}

func init() {
	core.SetPackageName("SOUP", "libsoup-3.0")
	core.SetSharedLibraries("SOUP", []string{"libsoup-3.0.so.0", "libsoup-3.0.0.dylib"})
}
