// Package webkitwebprocessextension was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package webkitwebprocessextension

// Enum values used to denote the stock actions for
// #WebKitContextMenuItem&lt;!-- --&gt;s
type ContextMenuAction int

const (

	// No action, used by separator menu items.
	WebkitContextMenuActionNoActionValue ContextMenuAction = 0
	// Open current link.
	WebkitContextMenuActionOpenLinkValue ContextMenuAction = 1
	// Open current link in a new window.
	WebkitContextMenuActionOpenLinkInNewWindowValue ContextMenuAction = 2
	// Download link destination.
	WebkitContextMenuActionDownloadLinkToDiskValue ContextMenuAction = 3
	// Copy link location to the clipboard.
	WebkitContextMenuActionCopyLinkToClipboardValue ContextMenuAction = 4
	// Open current image in a new window.
	WebkitContextMenuActionOpenImageInNewWindowValue ContextMenuAction = 5
	// Download current image.
	WebkitContextMenuActionDownloadImageToDiskValue ContextMenuAction = 6
	// Copy current image to the clipboard.
	WebkitContextMenuActionCopyImageToClipboardValue ContextMenuAction = 7
	// Copy current image location to the clipboard.
	WebkitContextMenuActionCopyImageUrlToClipboardValue ContextMenuAction = 8
	// Open current frame in a new window.
	WebkitContextMenuActionOpenFrameInNewWindowValue ContextMenuAction = 9
	// Load the previous history item.
	WebkitContextMenuActionGoBackValue ContextMenuAction = 10
	// Load the next history item.
	WebkitContextMenuActionGoForwardValue ContextMenuAction = 11
	// Stop any ongoing loading operation.
	WebkitContextMenuActionStopValue ContextMenuAction = 12
	// Reload the contents of current view.
	WebkitContextMenuActionReloadValue ContextMenuAction = 13
	// Copy current selection the clipboard.
	WebkitContextMenuActionCopyValue ContextMenuAction = 14
	// Cut current selection to the clipboard.
	WebkitContextMenuActionCutValue ContextMenuAction = 15
	// Paste clipboard contents.
	WebkitContextMenuActionPasteValue ContextMenuAction = 16
	// Delete current selection.
	WebkitContextMenuActionDeleteValue ContextMenuAction = 17
	// Select all text.
	WebkitContextMenuActionSelectAllValue ContextMenuAction = 18
	// Input methods menu.
	WebkitContextMenuActionInputMethodsValue ContextMenuAction = 19
	// Unicode menu.
	WebkitContextMenuActionUnicodeValue ContextMenuAction = 20
	// A proposed replacement for a misspelled word.
	WebkitContextMenuActionSpellingGuessValue ContextMenuAction = 21
	// An indicator that spellchecking found no proposed replacements.
	WebkitContextMenuActionNoGuessesFoundValue ContextMenuAction = 22
	// Causes the spellchecker to ignore the word for this session.
	WebkitContextMenuActionIgnoreSpellingValue ContextMenuAction = 23
	// Causes the spellchecker to add the word to the dictionary.
	WebkitContextMenuActionLearnSpellingValue ContextMenuAction = 24
	// Ignore grammar.
	WebkitContextMenuActionIgnoreGrammarValue ContextMenuAction = 25
	// Font options menu.
	WebkitContextMenuActionFontMenuValue ContextMenuAction = 26
	// Bold.
	WebkitContextMenuActionBoldValue ContextMenuAction = 27
	// Italic.
	WebkitContextMenuActionItalicValue ContextMenuAction = 28
	// Underline.
	WebkitContextMenuActionUnderlineValue ContextMenuAction = 29
	// Outline.
	WebkitContextMenuActionOutlineValue ContextMenuAction = 30
	// Open current element in the inspector.
	WebkitContextMenuActionInspectElementValue ContextMenuAction = 31
	// Open current video element in a new window.
	WebkitContextMenuActionOpenVideoInNewWindowValue ContextMenuAction = 32
	// Open current audio element in a new window.
	WebkitContextMenuActionOpenAudioInNewWindowValue ContextMenuAction = 33
	// Copy video link location in to the clipboard.
	WebkitContextMenuActionCopyVideoLinkToClipboardValue ContextMenuAction = 34
	// Copy audio link location in to the clipboard.
	WebkitContextMenuActionCopyAudioLinkToClipboardValue ContextMenuAction = 35
	// Enable or disable media controls.
	WebkitContextMenuActionToggleMediaControlsValue ContextMenuAction = 36
	// Enable or disable media loop.
	WebkitContextMenuActionToggleMediaLoopValue ContextMenuAction = 37
	// Show current video element in fullscreen mode.
	WebkitContextMenuActionEnterVideoFullscreenValue ContextMenuAction = 38
	// Play current media element.
	WebkitContextMenuActionMediaPlayValue ContextMenuAction = 39
	// Pause current media element.
	WebkitContextMenuActionMediaPauseValue ContextMenuAction = 40
	// Mute current media element.
	WebkitContextMenuActionMediaMuteValue ContextMenuAction = 41
	// Download video to disk. Since 2.2
	WebkitContextMenuActionDownloadVideoToDiskValue ContextMenuAction = 42
	// Download audio to disk. Since 2.2
	WebkitContextMenuActionDownloadAudioToDiskValue ContextMenuAction = 43
	// Insert an emoji. Since 2.26
	WebkitContextMenuActionInsertEmojiValue ContextMenuAction = 44
	// Paste clipboard contents as plain text. Since 2.30
	WebkitContextMenuActionPasteAsPlainTextValue ContextMenuAction = 45
	// Custom action defined by applications.
	WebkitContextMenuActionCustomValue ContextMenuAction = 10000
)
