// Package webkitwebprocessextension was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkitwebprocessextension

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk-webkit/javascriptcore"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type FrameClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *FrameClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func FrameClassNewFromInternalPtr(ptr uintptr) *FrameClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*FrameClass)(rawPtr)
}

// A web page frame.
//
// Each `WebKitWebPage` has at least one main frame, and can have any number
// of subframes.
type Frame struct {
	gobject.Object
}

var xFrameGLibType func() types.GType

func FrameGLibType() types.GType {
	core.LazyRegister(&xFrameGLibType, "WEBKITWEBPROCESSEXTENSION", "webkit_frame_get_type", false)
	return xFrameGLibType()
}

func FrameNewFromInternalPtr(ptr uintptr) *Frame {
	cls := &Frame{}
	cls.Ptr = ptr
	return cls
}

var xFrameGetId func(uintptr) uint64

// Gets the process-unique identifier of this #WebKitFrame. No other
// frame in the same web process will have the same ID; however, frames
// in other web processes may.
func (x *Frame) GetId() uint64 {
	core.LazyRegister(&xFrameGetId, "WEBKITWEBPROCESSEXTENSION", "webkit_frame_get_id", false)

	cret := xFrameGetId(x.GoPointer())
	return cret
}

var xFrameGetJsContext func(uintptr) uintptr

// Get the JavaScript execution context of @frame. Use this function to bridge
// between the WebKit and JavaScriptCore APIs.
func (x *Frame) GetJsContext() *javascriptcore.Context {
	core.LazyRegister(&xFrameGetJsContext, "WEBKITWEBPROCESSEXTENSION", "webkit_frame_get_js_context", false)
	var cls *javascriptcore.Context

	cret := xFrameGetJsContext(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &javascriptcore.Context{}
	cls.Ptr = cret
	return cls
}

var xFrameGetJsContextForScriptWorld func(uintptr, uintptr) uintptr

// Get the JavaScript execution context of @frame for the given #WebKitScriptWorld.
func (x *Frame) GetJsContextForScriptWorld(WorldVar *ScriptWorld) *javascriptcore.Context {
	core.LazyRegister(&xFrameGetJsContextForScriptWorld, "WEBKITWEBPROCESSEXTENSION", "webkit_frame_get_js_context_for_script_world", false)
	var cls *javascriptcore.Context

	cret := xFrameGetJsContextForScriptWorld(x.GoPointer(), WorldVar.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &javascriptcore.Context{}
	cls.Ptr = cret
	return cls
}

var xFrameGetUri func(uintptr) string

// Gets the current active URI of @frame.
func (x *Frame) GetUri() string {
	core.LazyRegister(&xFrameGetUri, "WEBKITWEBPROCESSEXTENSION", "webkit_frame_get_uri", false)

	cret := xFrameGetUri(x.GoPointer())
	return cret
}

var xFrameIsMainFrame func(uintptr) bool

// Gets whether @frame is the main frame of a #WebKitWebPage
func (x *Frame) IsMainFrame() bool {
	core.LazyRegister(&xFrameIsMainFrame, "WEBKITWEBPROCESSEXTENSION", "webkit_frame_is_main_frame", false)

	cret := xFrameIsMainFrame(x.GoPointer())
	return cret
}

func (c *Frame) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *Frame) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("WEBKITWEBPROCESSEXTENSION", "webkitgtk-web-process-extension-6.0")
	core.SetSharedLibraries("WEBKITWEBPROCESSEXTENSION", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})
}
