// Package webkitwebprocessextension was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package webkitwebprocessextension

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type ScriptWorldClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *ScriptWorldClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

type ScriptWorld struct {
	gobject.Object
}

var xScriptWorldGLibType func() types.GType

func ScriptWorldGLibType() types.GType {
	return xScriptWorldGLibType()
}

func ScriptWorldNewFromInternalPtr(ptr uintptr) *ScriptWorld {
	cls := &ScriptWorld{}
	cls.Ptr = ptr
	return cls
}

var xNewScriptWorld func() uintptr

// Creates a new isolated #WebKitScriptWorld. Scripts executed in
// isolated worlds have access to the DOM but not to other variable
// or functions created by the page.
// The #WebKitScriptWorld is created with a generated unique name. Use
// webkit_script_world_new_with_name() if you want to create it with a
// custom name.
// You can get the JavaScript execution context of a #WebKitScriptWorld
// for a given #WebKitFrame with webkit_frame_get_javascript_context_for_script_world().
func NewScriptWorld() *ScriptWorld {
	var cls *ScriptWorld

	cret := xNewScriptWorld()

	if cret == 0 {
		return nil
	}
	cls = &ScriptWorld{}
	cls.Ptr = cret
	return cls
}

var xNewScriptWorldWithName func(string) uintptr

// Creates a new isolated #WebKitScriptWorld with a name. Scripts executed in
// isolated worlds have access to the DOM but not to other variable
// or functions created by the page.
// You can get the JavaScript execution context of a #WebKitScriptWorld
// for a given #WebKitFrame with webkit_frame_get_javascript_context_for_script_world().
func NewScriptWorldWithName(NameVar string) *ScriptWorld {
	var cls *ScriptWorld

	cret := xNewScriptWorldWithName(NameVar)

	if cret == 0 {
		return nil
	}
	cls = &ScriptWorld{}
	cls.Ptr = cret
	return cls
}

var xScriptWorldGetName func(uintptr) string

// Get the name of a #WebKitScriptWorld.
func (x *ScriptWorld) GetName() string {

	cret := xScriptWorldGetName(x.GoPointer())

	return cret
}

func (c *ScriptWorld) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *ScriptWorld) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// Emitted when the JavaScript window object in a #WebKitScriptWorld has been
// cleared. This is the preferred place to set custom properties on the window
// object using the JavaScriptCore API. You can get the window object of @frame
// from the JavaScript execution context of @world that is returned by
// webkit_frame_get_js_context_for_script_world().
func (x *ScriptWorld) ConnectWindowObjectCleared(cb *func(ScriptWorld, uintptr, uintptr)) uint {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		handlerID := gobject.SignalConnect(x.GoPointer(), "window-object-cleared", cbRefPtr)
		glib.SaveHandlerMapping(handlerID, cbPtr)
		return handlerID
	}

	fcb := func(clsPtr uintptr, PageVarp uintptr, FrameVarp uintptr) {
		fa := ScriptWorld{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa, PageVarp, FrameVarp)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallbackWithClosure(cbPtr, cbRefPtr, cb)
	handlerID := gobject.SignalConnect(x.GoPointer(), "window-object-cleared", cbRefPtr)
	glib.SaveHandlerMapping(handlerID, cbPtr)
	return handlerID
}

var xScriptWorldGetDefault func() uintptr

// Get the default #WebKitScriptWorld. This is the normal script world
// where all scripts are executed by default.
// You can get the JavaScript execution context of a #WebKitScriptWorld
// for a given #WebKitFrame with webkit_frame_get_javascript_context_for_script_world().
func ScriptWorldGetDefault() *ScriptWorld {
	var cls *ScriptWorld

	cret := xScriptWorldGetDefault()

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &ScriptWorld{}
	cls.Ptr = cret
	return cls
}

func init() {
	core.SetPackageName("WEBKITWEBPROCESSEXTENSION", "webkitgtk-web-process-extension-6.0")
	core.SetSharedLibraries("WEBKITWEBPROCESSEXTENSION", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("WEBKITWEBPROCESSEXTENSION") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xScriptWorldGLibType, libs, "webkit_script_world_get_type")

	core.PuregoSafeRegister(&xNewScriptWorld, libs, "webkit_script_world_new")
	core.PuregoSafeRegister(&xNewScriptWorldWithName, libs, "webkit_script_world_new_with_name")

	core.PuregoSafeRegister(&xScriptWorldGetName, libs, "webkit_script_world_get_name")

	core.PuregoSafeRegister(&xScriptWorldGetDefault, libs, "webkit_script_world_get_default")

}
