// Package webkitwebprocessextension was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package webkitwebprocessextension

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type URIResponseClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *URIResponseClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// Represents an URI response.
//
// A #WebKitURIResponse contains information such as the URI, the
// status code, the content length, the mime type, the HTTP status or
// the suggested filename.
type URIResponse struct {
	gobject.Object
}

var xURIResponseGLibType func() types.GType

func URIResponseGLibType() types.GType {
	return xURIResponseGLibType()
}

func URIResponseNewFromInternalPtr(ptr uintptr) *URIResponse {
	cls := &URIResponse{}
	cls.Ptr = ptr
	return cls
}

var xURIResponseGetContentLength func(uintptr) uint64

// Get the expected content length of the #WebKitURIResponse.
//
// It can be 0 if the server provided an incorrect or missing Content-Length.
func (x *URIResponse) GetContentLength() uint64 {

	cret := xURIResponseGetContentLength(x.GoPointer())
	return cret
}

var xURIResponseGetHttpHeaders func(uintptr) uintptr

// Get the HTTP headers of a #WebKitURIResponse as a #SoupMessageHeaders.
func (x *URIResponse) GetHttpHeaders() uintptr {

	cret := xURIResponseGetHttpHeaders(x.GoPointer())
	return cret
}

var xURIResponseGetMimeType func(uintptr) string

// Gets the MIME type of the response.
func (x *URIResponse) GetMimeType() string {

	cret := xURIResponseGetMimeType(x.GoPointer())
	return cret
}

var xURIResponseGetStatusCode func(uintptr) uint

// Get the status code of the #WebKitURIResponse.
//
// Get the status code of the #WebKitURIResponse as returned by
// the server. It will normally be a #SoupKnownStatusCode, for
// example %SOUP_STATUS_OK, though the server can respond with any
// unsigned integer.
func (x *URIResponse) GetStatusCode() uint {

	cret := xURIResponseGetStatusCode(x.GoPointer())
	return cret
}

var xURIResponseGetSuggestedFilename func(uintptr) string

// Get the suggested filename for @response.
//
// Get the suggested filename for @response, as specified by
// the 'Content-Disposition' HTTP header, or %NULL if it's not
// present.
func (x *URIResponse) GetSuggestedFilename() string {

	cret := xURIResponseGetSuggestedFilename(x.GoPointer())
	return cret
}

var xURIResponseGetUri func(uintptr) string

// Gets the URI which resulted in the response.
func (x *URIResponse) GetUri() string {

	cret := xURIResponseGetUri(x.GoPointer())
	return cret
}

func (c *URIResponse) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *URIResponse) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("WEBKITWEBPROCESSEXTENSION", "webkitgtk-web-process-extension-6.0")
	core.SetSharedLibraries("WEBKITWEBPROCESSEXTENSION", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("WEBKITWEBPROCESSEXTENSION") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xURIResponseGLibType, libs, "webkit_uri_response_get_type")

	core.PuregoSafeRegister(&xURIResponseGetContentLength, libs, "webkit_uri_response_get_content_length")
	core.PuregoSafeRegister(&xURIResponseGetHttpHeaders, libs, "webkit_uri_response_get_http_headers")
	core.PuregoSafeRegister(&xURIResponseGetMimeType, libs, "webkit_uri_response_get_mime_type")
	core.PuregoSafeRegister(&xURIResponseGetStatusCode, libs, "webkit_uri_response_get_status_code")
	core.PuregoSafeRegister(&xURIResponseGetSuggestedFilename, libs, "webkit_uri_response_get_suggested_filename")
	core.PuregoSafeRegister(&xURIResponseGetUri, libs, "webkit_uri_response_get_uri")

}
