// Package webkitwebprocessextension was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkitwebprocessextension

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk-webkit/javascriptcore"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type WebHitTestResultClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *WebHitTestResultClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func WebHitTestResultClassNewFromInternalPtr(ptr uintptr) *WebHitTestResultClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*WebHitTestResultClass)(rawPtr)
}

// Result of a Hit Test (Web Process Extensions).
//
// WebKitWebHitTestResult extends #WebKitHitTestResult to provide information
// about the #WebKitDOMNode in the coordinates of the Hit Test.
type WebHitTestResult struct {
	gobject.Object
}

var xWebHitTestResultGLibType func() types.GType

func WebHitTestResultGLibType() types.GType {
	core.LazyRegister(&xWebHitTestResultGLibType, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_get_type", false)
	return xWebHitTestResultGLibType()
}

func WebHitTestResultNewFromInternalPtr(ptr uintptr) *WebHitTestResult {
	cls := &WebHitTestResult{}
	cls.Ptr = ptr
	return cls
}

var xWebHitTestResultContextIsEditable func(uintptr) bool

// Check whether there is an editable element at the hit test position.
//
// Checks whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_EDITABLE flag is present in
// the context flags.
func (x *WebHitTestResult) ContextIsEditable() bool {
	core.LazyRegister(&xWebHitTestResultContextIsEditable, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_context_is_editable", false)

	cret := xWebHitTestResultContextIsEditable(x.GoPointer())
	return cret
}

var xWebHitTestResultContextIsImage func(uintptr) bool

// Check whether there is an image element at the hit test position.
//
// Checks whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_IMAGE flag is present in
// the context flags.
func (x *WebHitTestResult) ContextIsImage() bool {
	core.LazyRegister(&xWebHitTestResultContextIsImage, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_context_is_image", false)

	cret := xWebHitTestResultContextIsImage(x.GoPointer())
	return cret
}

var xWebHitTestResultContextIsLink func(uintptr) bool

// Check whether there is a link element at the hit test position.
//
// Checks whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_LINK flag is present in
// the context flags.
func (x *WebHitTestResult) ContextIsLink() bool {
	core.LazyRegister(&xWebHitTestResultContextIsLink, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_context_is_link", false)

	cret := xWebHitTestResultContextIsLink(x.GoPointer())
	return cret
}

var xWebHitTestResultContextIsMedia func(uintptr) bool

// Check whether there is a media element at the hit test position.
//
// Checks whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_MEDIA flag is present in
// the context flags.
func (x *WebHitTestResult) ContextIsMedia() bool {
	core.LazyRegister(&xWebHitTestResultContextIsMedia, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_context_is_media", false)

	cret := xWebHitTestResultContextIsMedia(x.GoPointer())
	return cret
}

var xWebHitTestResultContextIsScrollbar func(uintptr) bool

// Check whether there is a scrollbar at the hit test position.
//
// Checks whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_SCROLLBAR flag is present in
// the context flags.
func (x *WebHitTestResult) ContextIsScrollbar() bool {
	core.LazyRegister(&xWebHitTestResultContextIsScrollbar, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_context_is_scrollbar", false)

	cret := xWebHitTestResultContextIsScrollbar(x.GoPointer())
	return cret
}

var xWebHitTestResultContextIsSelection func(uintptr) bool

// Check whether there is a selected element at the hit test position.
//
// Checks whether %WEBKIT_HIT_TEST_RESULT_CONTEXT_SELECTION flag is present in
// the context flags.
func (x *WebHitTestResult) ContextIsSelection() bool {
	core.LazyRegister(&xWebHitTestResultContextIsSelection, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_context_is_selection", false)

	cret := xWebHitTestResultContextIsSelection(x.GoPointer())
	return cret
}

var xWebHitTestResultGetContext func(uintptr) uint

// Gets the the context flags for the hit test result.
func (x *WebHitTestResult) GetContext() uint {
	core.LazyRegister(&xWebHitTestResultGetContext, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_get_context", false)

	cret := xWebHitTestResultGetContext(x.GoPointer())
	return cret
}

var xWebHitTestResultGetImageUri func(uintptr) string

// Obtains the URI associated with the image element at the hit test position.
func (x *WebHitTestResult) GetImageUri() string {
	core.LazyRegister(&xWebHitTestResultGetImageUri, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_get_image_uri", false)

	cret := xWebHitTestResultGetImageUri(x.GoPointer())
	return cret
}

var xWebHitTestResultGetJsNode func(uintptr, uintptr) uintptr

// Get the #JSCValue for the DOM node in @world at the coordinates of the Hit Test.
func (x *WebHitTestResult) GetJsNode(WorldVar *ScriptWorld) *javascriptcore.Value {
	core.LazyRegister(&xWebHitTestResultGetJsNode, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_get_js_node", false)
	var cls *javascriptcore.Value

	cret := xWebHitTestResultGetJsNode(x.GoPointer(), WorldVar.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &javascriptcore.Value{}
	cls.Ptr = cret
	return cls
}

var xWebHitTestResultGetLinkLabel func(uintptr) string

// Obtains the label associated with the link element at the hit test position.
func (x *WebHitTestResult) GetLinkLabel() string {
	core.LazyRegister(&xWebHitTestResultGetLinkLabel, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_get_link_label", false)

	cret := xWebHitTestResultGetLinkLabel(x.GoPointer())
	return cret
}

var xWebHitTestResultGetLinkTitle func(uintptr) string

// Obtains the title associated with the link element at the hit test position.
func (x *WebHitTestResult) GetLinkTitle() string {
	core.LazyRegister(&xWebHitTestResultGetLinkTitle, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_get_link_title", false)

	cret := xWebHitTestResultGetLinkTitle(x.GoPointer())
	return cret
}

var xWebHitTestResultGetLinkUri func(uintptr) string

// Obtains the URI associated with the link element at the hit test position.
func (x *WebHitTestResult) GetLinkUri() string {
	core.LazyRegister(&xWebHitTestResultGetLinkUri, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_get_link_uri", false)

	cret := xWebHitTestResultGetLinkUri(x.GoPointer())
	return cret
}

var xWebHitTestResultGetMediaUri func(uintptr) string

// Obtains the URI associated with the media element at the hit test position.
func (x *WebHitTestResult) GetMediaUri() string {
	core.LazyRegister(&xWebHitTestResultGetMediaUri, "WEBKITWEBPROCESSEXTENSION", "webkit_web_hit_test_result_get_media_uri", false)

	cret := xWebHitTestResultGetMediaUri(x.GoPointer())
	return cret
}

func (c *WebHitTestResult) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *WebHitTestResult) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("WEBKITWEBPROCESSEXTENSION", "webkitgtk-web-process-extension-6.0")
	core.SetSharedLibraries("WEBKITWEBPROCESSEXTENSION", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})
}
