// Package webkitwebprocessextension was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package webkitwebprocessextension

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type ConsoleMessage struct {
	_ structs.HostLayout
}

var xConsoleMessageGLibType func() types.GType

func ConsoleMessageGLibType() types.GType {
	return xConsoleMessageGLibType()
}

func (x *ConsoleMessage) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xConsoleMessageCopy func(uintptr) uintptr

// Make a copy of @console_message.
func (x *ConsoleMessage) Copy() uintptr {

	cret := xConsoleMessageCopy(x.GoPointer())
	return cret
}

var xConsoleMessageFree func(uintptr)

// Free the #WebKitConsoleMessage
func (x *ConsoleMessage) Free() {

	xConsoleMessageFree(x.GoPointer())

}

var xConsoleMessageGetLevel func(uintptr) ConsoleMessageLevel

// Gets the log level of a #WebKitConsoleMessage
func (x *ConsoleMessage) GetLevel() ConsoleMessageLevel {

	cret := xConsoleMessageGetLevel(x.GoPointer())
	return cret
}

var xConsoleMessageGetLine func(uintptr) uint

// Gets the line number of a #WebKitConsoleMessage
func (x *ConsoleMessage) GetLine() uint {

	cret := xConsoleMessageGetLine(x.GoPointer())
	return cret
}

var xConsoleMessageGetSource func(uintptr) ConsoleMessageSource

// Gets the source of a #WebKitConsoleMessage
func (x *ConsoleMessage) GetSource() ConsoleMessageSource {

	cret := xConsoleMessageGetSource(x.GoPointer())
	return cret
}

var xConsoleMessageGetSourceId func(uintptr) string

// Gets the source identifier of a #WebKitConsoleMessage
func (x *ConsoleMessage) GetSourceId() string {

	cret := xConsoleMessageGetSourceId(x.GoPointer())
	return cret
}

var xConsoleMessageGetText func(uintptr) string

// Gets the text message of a #WebKitConsoleMessage
func (x *ConsoleMessage) GetText() string {

	cret := xConsoleMessageGetText(x.GoPointer())
	return cret
}

// Enum values used to denote the various levels of console messages.
type ConsoleMessageLevel int

var xConsoleMessageLevelGLibType func() types.GType

func ConsoleMessageLevelGLibType() types.GType {
	return xConsoleMessageLevelGLibType()
}

const (

	// Information message.
	WebkitConsoleMessageLevelInfoValue ConsoleMessageLevel = 0
	// Log message.
	WebkitConsoleMessageLevelLogValue ConsoleMessageLevel = 1
	// Warning message.
	WebkitConsoleMessageLevelWarningValue ConsoleMessageLevel = 2
	// Error message.
	WebkitConsoleMessageLevelErrorValue ConsoleMessageLevel = 3
	// Debug message.
	WebkitConsoleMessageLevelDebugValue ConsoleMessageLevel = 4
)

// Enum values used to denote the various sources of console messages.
type ConsoleMessageSource int

var xConsoleMessageSourceGLibType func() types.GType

func ConsoleMessageSourceGLibType() types.GType {
	return xConsoleMessageSourceGLibType()
}

const (

	// Message produced by JavaScript.
	WebkitConsoleMessageSourceJavascriptValue ConsoleMessageSource = 0
	// Network messages.
	WebkitConsoleMessageSourceNetworkValue ConsoleMessageSource = 1
	// Messages produced by console API.
	WebkitConsoleMessageSourceConsoleApiValue ConsoleMessageSource = 2
	// Security messages.
	WebkitConsoleMessageSourceSecurityValue ConsoleMessageSource = 3
	// Other messages.
	WebkitConsoleMessageSourceOtherValue ConsoleMessageSource = 4
)

func init() {
	core.SetPackageName("WEBKITWEBPROCESSEXTENSION", "webkitgtk-web-process-extension-6.0")
	core.SetSharedLibraries("WEBKITWEBPROCESSEXTENSION", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("WEBKITWEBPROCESSEXTENSION") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xConsoleMessageLevelGLibType, libs, "webkit_console_message_level_get_type")

	core.PuregoSafeRegister(&xConsoleMessageSourceGLibType, libs, "webkit_console_message_source_get_type")

	core.PuregoSafeRegister(&xConsoleMessageGLibType, libs, "webkit_console_message_get_type")

	core.PuregoSafeRegister(&xConsoleMessageCopy, libs, "webkit_console_message_copy")
	core.PuregoSafeRegister(&xConsoleMessageFree, libs, "webkit_console_message_free")
	core.PuregoSafeRegister(&xConsoleMessageGetLevel, libs, "webkit_console_message_get_level")
	core.PuregoSafeRegister(&xConsoleMessageGetLine, libs, "webkit_console_message_get_line")
	core.PuregoSafeRegister(&xConsoleMessageGetSource, libs, "webkit_console_message_get_source")
	core.PuregoSafeRegister(&xConsoleMessageGetSourceId, libs, "webkit_console_message_get_source_id")
	core.PuregoSafeRegister(&xConsoleMessageGetText, libs, "webkit_console_message_get_text")

}
