// Package webkitwebprocessextension was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkitwebprocessextension

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type ConsoleMessage struct {
	_ structs.HostLayout
}

var xConsoleMessageGLibType func() types.GType

func ConsoleMessageGLibType() types.GType {
	core.LazyRegister(&xConsoleMessageGLibType, "WEBKITWEBPROCESSEXTENSION", "webkit_console_message_get_type", false)
	return xConsoleMessageGLibType()
}

func (x *ConsoleMessage) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ConsoleMessageNewFromInternalPtr(ptr uintptr) *ConsoleMessage {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ConsoleMessage)(rawPtr)
}

var xConsoleMessageCopy func(uintptr) uintptr

// Make a copy of @console_message.
func (x *ConsoleMessage) Copy() *ConsoleMessage {
	core.LazyRegister(&xConsoleMessageCopy, "WEBKITWEBPROCESSEXTENSION", "webkit_console_message_copy", false)

	cret := xConsoleMessageCopy(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*ConsoleMessage)(unsafe.Pointer(cret))
}

var xConsoleMessageFree func(uintptr)

// Free the #WebKitConsoleMessage
func (x *ConsoleMessage) Free() {
	core.LazyRegister(&xConsoleMessageFree, "WEBKITWEBPROCESSEXTENSION", "webkit_console_message_free", false)

	xConsoleMessageFree(x.GoPointer())
}

var xConsoleMessageGetLevel func(uintptr) ConsoleMessageLevel

// Gets the log level of a #WebKitConsoleMessage
func (x *ConsoleMessage) GetLevel() ConsoleMessageLevel {
	core.LazyRegister(&xConsoleMessageGetLevel, "WEBKITWEBPROCESSEXTENSION", "webkit_console_message_get_level", false)

	cret := xConsoleMessageGetLevel(x.GoPointer())
	return cret
}

var xConsoleMessageGetLine func(uintptr) uint

// Gets the line number of a #WebKitConsoleMessage
func (x *ConsoleMessage) GetLine() uint {
	core.LazyRegister(&xConsoleMessageGetLine, "WEBKITWEBPROCESSEXTENSION", "webkit_console_message_get_line", false)

	cret := xConsoleMessageGetLine(x.GoPointer())
	return cret
}

var xConsoleMessageGetSource func(uintptr) ConsoleMessageSource

// Gets the source of a #WebKitConsoleMessage
func (x *ConsoleMessage) GetSource() ConsoleMessageSource {
	core.LazyRegister(&xConsoleMessageGetSource, "WEBKITWEBPROCESSEXTENSION", "webkit_console_message_get_source", false)

	cret := xConsoleMessageGetSource(x.GoPointer())
	return cret
}

var xConsoleMessageGetSourceId func(uintptr) string

// Gets the source identifier of a #WebKitConsoleMessage
func (x *ConsoleMessage) GetSourceId() string {
	core.LazyRegister(&xConsoleMessageGetSourceId, "WEBKITWEBPROCESSEXTENSION", "webkit_console_message_get_source_id", false)

	cret := xConsoleMessageGetSourceId(x.GoPointer())
	return cret
}

var xConsoleMessageGetText func(uintptr) string

// Gets the text message of a #WebKitConsoleMessage
func (x *ConsoleMessage) GetText() string {
	core.LazyRegister(&xConsoleMessageGetText, "WEBKITWEBPROCESSEXTENSION", "webkit_console_message_get_text", false)

	cret := xConsoleMessageGetText(x.GoPointer())
	return cret
}

// Enum values used to denote the various levels of console messages.
type ConsoleMessageLevel int

var xConsoleMessageLevelGLibType func() types.GType

func ConsoleMessageLevelGLibType() types.GType {
	core.LazyRegister(&xConsoleMessageLevelGLibType, "WEBKITWEBPROCESSEXTENSION", "webkit_console_message_level_get_type", false)
	return xConsoleMessageLevelGLibType()
}

const (

	// Information message.
	WebkitConsoleMessageLevelInfoValue ConsoleMessageLevel = 0
	// Log message.
	WebkitConsoleMessageLevelLogValue ConsoleMessageLevel = 1
	// Warning message.
	WebkitConsoleMessageLevelWarningValue ConsoleMessageLevel = 2
	// Error message.
	WebkitConsoleMessageLevelErrorValue ConsoleMessageLevel = 3
	// Debug message.
	WebkitConsoleMessageLevelDebugValue ConsoleMessageLevel = 4
)

// Enum values used to denote the various sources of console messages.
type ConsoleMessageSource int

var xConsoleMessageSourceGLibType func() types.GType

func ConsoleMessageSourceGLibType() types.GType {
	core.LazyRegister(&xConsoleMessageSourceGLibType, "WEBKITWEBPROCESSEXTENSION", "webkit_console_message_source_get_type", false)
	return xConsoleMessageSourceGLibType()
}

const (

	// Message produced by JavaScript.
	WebkitConsoleMessageSourceJavascriptValue ConsoleMessageSource = 0
	// Network messages.
	WebkitConsoleMessageSourceNetworkValue ConsoleMessageSource = 1
	// Messages produced by console API.
	WebkitConsoleMessageSourceConsoleApiValue ConsoleMessageSource = 2
	// Security messages.
	WebkitConsoleMessageSourceSecurityValue ConsoleMessageSource = 3
	// Other messages.
	WebkitConsoleMessageSourceOtherValue ConsoleMessageSource = 4
)

func init() {
	core.SetPackageName("WEBKITWEBPROCESSEXTENSION", "webkitgtk-web-process-extension-6.0")
	core.SetSharedLibraries("WEBKITWEBPROCESSEXTENSION", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})
}
