// Package webkitwebprocessextension was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package webkitwebprocessextension

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk-webkit/javascriptcore"
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/pkg/core"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type FrameClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *FrameClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// A web page frame.
//
// Each `WebKitWebPage` has at least one main frame, and can have any number
// of subframes.
type Frame struct {
	gobject.Object
}

var xFrameGLibType func() types.GType

func FrameGLibType() types.GType {
	return xFrameGLibType()
}

func FrameNewFromInternalPtr(ptr uintptr) *Frame {
	cls := &Frame{}
	cls.Ptr = ptr
	return cls
}

var xFrameGetId func(uintptr) uint64

// Gets the process-unique identifier of this #WebKitFrame. No other
// frame in the same web process will have the same ID; however, frames
// in other web processes may.
func (x *Frame) GetId() uint64 {

	cret := xFrameGetId(x.GoPointer())
	return cret
}

var xFrameGetJsContext func(uintptr) uintptr

// Get the JavaScript execution context of @frame. Use this function to bridge
// between the WebKit and JavaScriptCore APIs.
func (x *Frame) GetJsContext() *javascriptcore.Context {
	var cls *javascriptcore.Context

	cret := xFrameGetJsContext(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &javascriptcore.Context{}
	cls.Ptr = cret
	return cls
}

var xFrameGetJsContextForScriptWorld func(uintptr, uintptr) uintptr

// Get the JavaScript execution context of @frame for the given #WebKitScriptWorld.
func (x *Frame) GetJsContextForScriptWorld(WorldVar *ScriptWorld) *javascriptcore.Context {
	var cls *javascriptcore.Context

	cret := xFrameGetJsContextForScriptWorld(x.GoPointer(), WorldVar.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &javascriptcore.Context{}
	cls.Ptr = cret
	return cls
}

var xFrameGetUri func(uintptr) string

// Gets the current active URI of @frame.
func (x *Frame) GetUri() string {

	cret := xFrameGetUri(x.GoPointer())
	return cret
}

var xFrameIsMainFrame func(uintptr) bool

// Gets whether @frame is the main frame of a #WebKitWebPage
func (x *Frame) IsMainFrame() bool {

	cret := xFrameIsMainFrame(x.GoPointer())
	return cret
}

func (c *Frame) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *Frame) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("WEBKITWEBPROCESSEXTENSION", "webkitgtk-web-process-extension-6.0")
	core.SetSharedLibraries("WEBKITWEBPROCESSEXTENSION", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("WEBKITWEBPROCESSEXTENSION") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xFrameGLibType, libs, "webkit_frame_get_type")

	core.PuregoSafeRegister(&xFrameGetId, libs, "webkit_frame_get_id")
	core.PuregoSafeRegister(&xFrameGetJsContext, libs, "webkit_frame_get_js_context")
	core.PuregoSafeRegister(&xFrameGetJsContextForScriptWorld, libs, "webkit_frame_get_js_context_for_script_world")
	core.PuregoSafeRegister(&xFrameGetUri, libs, "webkit_frame_get_uri")
	core.PuregoSafeRegister(&xFrameIsMainFrame, libs, "webkit_frame_is_main_frame")

}
