// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// This query represents a user's choice to allow or deny access to "powerful features" of the
// platform, as specified in the [Permissions W3C
// Specification](https://w3c.github.io/permissions/).
//
// When signalled by the #WebKitWebView through the `query-permission-state` signal, the application
// has to eventually respond, via `webkit_permission_state_query_finish()`, whether it grants,
// denies or requests a dedicated permission prompt for the given query.
//
// When a #WebKitPermissionStateQuery is not handled by the user, the user-agent is instructed to
// `prompt` the user for the given permission.
type PermissionStateQuery struct {
	_ structs.HostLayout
}

var xPermissionStateQueryGLibType func() types.GType

func PermissionStateQueryGLibType() types.GType {
	core.LazyRegister(&xPermissionStateQueryGLibType, "WEBKIT", "webkit_permission_state_query_get_type", false)
	return xPermissionStateQueryGLibType()
}

func (x *PermissionStateQuery) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func PermissionStateQueryNewFromInternalPtr(ptr uintptr) *PermissionStateQuery {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*PermissionStateQuery)(rawPtr)
}

var xPermissionStateQueryFinish func(uintptr, PermissionState)

// Notify the web-engine of the selected permission state for the given query. This function should
// only be called as a response to the `WebKitWebView::query-permission-state` signal.
func (x *PermissionStateQuery) Finish(StateVar PermissionState) {
	core.LazyRegister(&xPermissionStateQueryFinish, "WEBKIT", "webkit_permission_state_query_finish", false)

	xPermissionStateQueryFinish(x.GoPointer(), StateVar)
}

var xPermissionStateQueryGetName func(uintptr) string

// Get the permission name for which access is being queried.
func (x *PermissionStateQuery) GetName() string {
	core.LazyRegister(&xPermissionStateQueryGetName, "WEBKIT", "webkit_permission_state_query_get_name", false)

	cret := xPermissionStateQueryGetName(x.GoPointer())
	return cret
}

var xPermissionStateQueryGetSecurityOrigin func(uintptr) uintptr

// Get the permission origin for which access is being queried.
func (x *PermissionStateQuery) GetSecurityOrigin() *SecurityOrigin {
	core.LazyRegister(&xPermissionStateQueryGetSecurityOrigin, "WEBKIT", "webkit_permission_state_query_get_security_origin", false)

	cret := xPermissionStateQueryGetSecurityOrigin(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*SecurityOrigin)(unsafe.Pointer(cret))
}

var xPermissionStateQueryRef func(uintptr) uintptr

// Atomically increments the reference count of @query by one.
//
// This function is MT-safe and may be called from any thread.
func (x *PermissionStateQuery) Ref() *PermissionStateQuery {
	core.LazyRegister(&xPermissionStateQueryRef, "WEBKIT", "webkit_permission_state_query_ref", false)

	cret := xPermissionStateQueryRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*PermissionStateQuery)(unsafe.Pointer(cret))
}

var xPermissionStateQueryUnref func(uintptr)

// Atomically decrements the reference count of @query by one.
//
// If the reference count drops to 0, all memory allocated by #WebKitPermissionStateQuery is
// released. This function is MT-safe and may be called from any thread.
func (x *PermissionStateQuery) Unref() {
	core.LazyRegister(&xPermissionStateQueryUnref, "WEBKIT", "webkit_permission_state_query_unref", false)

	xPermissionStateQueryUnref(x.GoPointer())
}

// Enum values representing query permission results.
type PermissionState int

var xPermissionStateGLibType func() types.GType

func PermissionStateGLibType() types.GType {
	core.LazyRegister(&xPermissionStateGLibType, "WEBKIT", "webkit_permission_state_get_type", false)
	return xPermissionStateGLibType()
}

const (

	// Access to the feature is granted.
	PermissionStateGrantedValue PermissionState = 0
	// Access to the feature is denied.
	PermissionStateDeniedValue PermissionState = 1
	// Access to the feature has to be requested via user prompt.
	PermissionStatePromptValue PermissionState = 2
)

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
}
