// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// Information about an application running in automation mode.
type ApplicationInfo struct {
	_ structs.HostLayout
}

var xApplicationInfoGLibType func() types.GType

func ApplicationInfoGLibType() types.GType {
	core.LazyRegister(&xApplicationInfoGLibType, "WEBKIT", "webkit_application_info_get_type", false)
	return xApplicationInfoGLibType()
}

func (x *ApplicationInfo) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ApplicationInfoNewFromInternalPtr(ptr uintptr) *ApplicationInfo {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ApplicationInfo)(rawPtr)
}

var xNewApplicationInfo func() uintptr

// Creates a new #WebKitApplicationInfo
func NewApplicationInfo() *ApplicationInfo {
	core.LazyRegister(&xNewApplicationInfo, "WEBKIT", "webkit_application_info_new", false)

	cret := xNewApplicationInfo()
	if cret == 0 {
		return nil
	}
	return (*ApplicationInfo)(unsafe.Pointer(cret))
}

var xApplicationInfoGetName func(uintptr) string

// Get the name of the application.
//
// If webkit_application_info_set_name() hasn't been
// called with a valid name, this returns g_get_prgname().
func (x *ApplicationInfo) GetName() string {
	core.LazyRegister(&xApplicationInfoGetName, "WEBKIT", "webkit_application_info_get_name", false)

	cret := xApplicationInfoGetName(x.GoPointer())
	return cret
}

var xApplicationInfoGetVersion func(uintptr, *uint64, *uint64, *uint64)

// Get the application version previously set with webkit_application_info_set_version().
func (x *ApplicationInfo) GetVersion(MajorVar *uint64, MinorVar *uint64, MicroVar *uint64) {
	core.LazyRegister(&xApplicationInfoGetVersion, "WEBKIT", "webkit_application_info_get_version", false)

	xApplicationInfoGetVersion(x.GoPointer(), MajorVar, MinorVar, MicroVar)
}

var xApplicationInfoRef func(uintptr) uintptr

// Atomically increments the reference count of @info by one.
//
// This
// function is MT-safe and may be called from any thread.
func (x *ApplicationInfo) Ref() *ApplicationInfo {
	core.LazyRegister(&xApplicationInfoRef, "WEBKIT", "webkit_application_info_ref", false)

	cret := xApplicationInfoRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*ApplicationInfo)(unsafe.Pointer(cret))
}

var xApplicationInfoSetName func(uintptr, string)

// Set the name of the application.
//
// If not provided, or %NULL is passed,
// g_get_prgname() will be used.
func (x *ApplicationInfo) SetName(NameVar string) {
	core.LazyRegister(&xApplicationInfoSetName, "WEBKIT", "webkit_application_info_set_name", false)

	xApplicationInfoSetName(x.GoPointer(), NameVar)
}

var xApplicationInfoSetVersion func(uintptr, uint64, uint64, uint64)

// Set the application version.
//
// If the application doesn't use the format
// major.minor.micro you can pass 0 as the micro to use major.minor, or pass
// 0 as both micro and minor to use only major number. Any other format must
// be converted to major.minor.micro so that it can be used in version comparisons.
func (x *ApplicationInfo) SetVersion(MajorVar uint64, MinorVar uint64, MicroVar uint64) {
	core.LazyRegister(&xApplicationInfoSetVersion, "WEBKIT", "webkit_application_info_set_version", false)

	xApplicationInfoSetVersion(x.GoPointer(), MajorVar, MinorVar, MicroVar)
}

var xApplicationInfoUnref func(uintptr)

// Atomically decrements the reference count of @info by one.
//
// If the
// reference count drops to 0, all memory allocated by the #WebKitApplicationInfo is
// released. This function is MT-safe and may be called from any
// thread.
func (x *ApplicationInfo) Unref() {
	core.LazyRegister(&xApplicationInfoUnref, "WEBKIT", "webkit_application_info_unref", false)

	xApplicationInfoUnref(x.GoPointer())
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
}
