// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import "github.com/bnema/puregotk/pkg/core"

const (
	// Like webkit_get_major_version(), but from the headers used at
	// application compile time, rather than from the library linked
	// against at application run time.
	MAJOR_VERSION int = 2
	// Like webkit_get_micro_version(), but from the headers used at
	// application compile time, rather than from the library linked
	// against at application run time.
	MICRO_VERSION int = 5
	// Like webkit_get_minor_version(), but from the headers used at
	// application compile time, rather than from the library linked
	// against at application run time.
	MINOR_VERSION int = 52
)

var xGetMajorVersion func() uint

// Returns the major version number of the WebKit library.
//
// (e.g. in WebKit version 1.8.3 this is 1.)
//
// This function is in the library, so it represents the WebKit library
// your code is running against. Contrast with the #WEBKIT_MAJOR_VERSION
// macro, which represents the major version of the WebKit headers you
// have included when compiling your code.
func GetMajorVersion() uint {
	core.LazyRegister(&xGetMajorVersion, "WEBKIT", "webkit_get_major_version", false)

	cret := xGetMajorVersion()
	return cret
}

var xGetMicroVersion func() uint

// Returns the micro version number of the WebKit library.
//
// (e.g. in WebKit version 1.8.3 this is 3.)
//
// This function is in the library, so it represents the WebKit library
// your code is running against. Contrast with the #WEBKIT_MICRO_VERSION
// macro, which represents the micro version of the WebKit headers you
// have included when compiling your code.
func GetMicroVersion() uint {
	core.LazyRegister(&xGetMicroVersion, "WEBKIT", "webkit_get_micro_version", false)

	cret := xGetMicroVersion()
	return cret
}

var xGetMinorVersion func() uint

// Returns the minor version number of the WebKit library.
//
// (e.g. in WebKit version 1.8.3 this is 8.)
//
// This function is in the library, so it represents the WebKit library
// your code is running against. Contrast with the #WEBKIT_MINOR_VERSION
// macro, which represents the minor version of the WebKit headers you
// have included when compiling your code.
func GetMinorVersion() uint {
	core.LazyRegister(&xGetMinorVersion, "WEBKIT", "webkit_get_minor_version", false)

	cret := xGetMinorVersion()
	return cret
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
}
