// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk-webkit/javascriptcore"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// A reply for a script message received.
// If no reply has been sent by the user, an automatically generated reply with
// undefined value with be sent.
type ScriptMessageReply struct {
	_ structs.HostLayout
}

var xScriptMessageReplyGLibType func() types.GType

func ScriptMessageReplyGLibType() types.GType {
	core.LazyRegister(&xScriptMessageReplyGLibType, "WEBKIT", "webkit_script_message_reply_get_type", false)
	return xScriptMessageReplyGLibType()
}

func (x *ScriptMessageReply) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ScriptMessageReplyNewFromInternalPtr(ptr uintptr) *ScriptMessageReply {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ScriptMessageReply)(rawPtr)
}

var xScriptMessageReplyRef func(uintptr) uintptr

// Atomically increments the reference count of @script_message_reply by one.
func (x *ScriptMessageReply) Ref() *ScriptMessageReply {
	core.LazyRegister(&xScriptMessageReplyRef, "WEBKIT", "webkit_script_message_reply_ref", false)

	cret := xScriptMessageReplyRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*ScriptMessageReply)(unsafe.Pointer(cret))
}

var xScriptMessageReplyReturnErrorMessage func(uintptr, string)

// Reply to a script message with an error message.
func (x *ScriptMessageReply) ReturnErrorMessage(ErrorMessageVar string) {
	core.LazyRegister(&xScriptMessageReplyReturnErrorMessage, "WEBKIT", "webkit_script_message_reply_return_error_message", false)

	xScriptMessageReplyReturnErrorMessage(x.GoPointer(), ErrorMessageVar)
}

var xScriptMessageReplyReturnValue func(uintptr, uintptr)

// Reply to a script message with a value.
//
// This function can be called twice for passing the reply value in.
func (x *ScriptMessageReply) ReturnValue(ReplyValueVar *javascriptcore.Value) {
	core.LazyRegister(&xScriptMessageReplyReturnValue, "WEBKIT", "webkit_script_message_reply_return_value", false)

	xScriptMessageReplyReturnValue(x.GoPointer(), ReplyValueVar.GoPointer())
}

var xScriptMessageReplyUnref func(uintptr)

// Atomically decrements the reference count of @script_message_reply by one.
//
// If the reference count drops to 0, all the memory allocated by the
// #WebKitScriptMessageReply is released. This function is MT-safe and may
// be called from any thread.
func (x *ScriptMessageReply) Unref() {
	core.LazyRegister(&xScriptMessageReplyUnref, "WEBKIT", "webkit_script_message_reply_unref", false)

	xScriptMessageReplyUnref(x.GoPointer())
}

type UserContentManagerClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *UserContentManagerClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func UserContentManagerClassNewFromInternalPtr(ptr uintptr) *UserContentManagerClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*UserContentManagerClass)(rawPtr)
}

// Manages user-defined content which affects web pages.
//
// Using a #WebKitUserContentManager user CSS style sheets can be set to
// be injected in the web pages loaded by a #WebKitWebView, by
// webkit_user_content_manager_add_style_sheet().
//
// To use a #WebKitUserContentManager, it must be created using
// webkit_user_content_manager_new(), and then used to construct
// a #WebKitWebView. User style sheets can be created with
// webkit_user_style_sheet_new().
//
// User style sheets can be added and removed at any time, but
// they will affect the web pages loaded afterwards.
type UserContentManager struct {
	gobject.Object
}

var xUserContentManagerGLibType func() types.GType

func UserContentManagerGLibType() types.GType {
	core.LazyRegister(&xUserContentManagerGLibType, "WEBKIT", "webkit_user_content_manager_get_type", false)
	return xUserContentManagerGLibType()
}

func UserContentManagerNewFromInternalPtr(ptr uintptr) *UserContentManager {
	cls := &UserContentManager{}
	cls.Ptr = ptr
	return cls
}

var xNewUserContentManager func() uintptr

// Creates a new user content manager.
func NewUserContentManager() *UserContentManager {
	core.LazyRegister(&xNewUserContentManager, "WEBKIT", "webkit_user_content_manager_new", false)
	var cls *UserContentManager

	cret := xNewUserContentManager()

	if cret == 0 {
		return nil
	}
	cls = &UserContentManager{}
	cls.Ptr = cret
	return cls
}

var xUserContentManagerAddFilter func(uintptr, *UserContentFilter)

// Adds a #WebKitUserContentFilter to the given #WebKitUserContentManager.
//
// The same #WebKitUserContentFilter can be reused with multiple
// #WebKitUserContentManager instances.
//
// Filters need to be saved and loaded from #WebKitUserContentFilterStore.
func (x *UserContentManager) AddFilter(FilterVar *UserContentFilter) {
	core.LazyRegister(&xUserContentManagerAddFilter, "WEBKIT", "webkit_user_content_manager_add_filter", false)

	xUserContentManagerAddFilter(x.GoPointer(), FilterVar)
}

var xUserContentManagerAddScript func(uintptr, *UserScript)

// Adds a #WebKitUserScript to the given #WebKitUserContentManager.
//
// The same #WebKitUserScript can be reused with multiple
// #WebKitUserContentManager instances.
func (x *UserContentManager) AddScript(ScriptVar *UserScript) {
	core.LazyRegister(&xUserContentManagerAddScript, "WEBKIT", "webkit_user_content_manager_add_script", false)

	xUserContentManagerAddScript(x.GoPointer(), ScriptVar)
}

var xUserContentManagerAddStyleSheet func(uintptr, *UserStyleSheet)

// Adds a #WebKitUserStyleSheet to the given #WebKitUserContentManager.
//
// The same #WebKitUserStyleSheet can be reused with multiple
// #WebKitUserContentManager instances.
func (x *UserContentManager) AddStyleSheet(StylesheetVar *UserStyleSheet) {
	core.LazyRegister(&xUserContentManagerAddStyleSheet, "WEBKIT", "webkit_user_content_manager_add_style_sheet", false)

	xUserContentManagerAddStyleSheet(x.GoPointer(), StylesheetVar)
}

var xUserContentManagerRegisterScriptMessageHandler func(uintptr, string, uintptr) bool

// Registers a new user script message handler in script world.
//
// After it is registered,
// scripts can use `window.webkit.messageHandlers.&lt;name&gt;.postMessage(value)`
// to send messages. Those messages are received by connecting handlers
// to the #WebKitUserContentManager::script-message-received signal. The
// handler name is used as the detail of the signal. To avoid race
// conditions between registering the handler name, and starting to
// receive the signals, it is recommended to connect to the signal
// *before* registering the handler name:
//
// ```c
// WebKitWebView *view = webkit_web_view_new ();
// WebKitUserContentManager *manager = webkit_web_view_get_user_content_manager ();
// g_signal_connect (manager, "script-message-received::foobar",
//
//	G_CALLBACK (handle_script_message), NULL);
//
// webkit_user_content_manager_register_script_message_handler (manager, "foobar", "world");
// ```
//
// Registering a script message handler will fail if the requested
// name has been already registered before.
//
// If %NULL is passed as the @world_name, the default world will be used.
//
// The registered handler can be unregistered by using
// webkit_user_content_manager_unregister_script_message_handler().
func (x *UserContentManager) RegisterScriptMessageHandler(NameVar string, WorldNameVar *string) bool {
	core.LazyRegister(&xUserContentManagerRegisterScriptMessageHandler, "WEBKIT", "webkit_user_content_manager_register_script_message_handler", false)

	WorldNameVarPtr := core.GStrdupNullable(WorldNameVar)
	defer core.GFreeNullable(WorldNameVarPtr)

	cret := xUserContentManagerRegisterScriptMessageHandler(x.GoPointer(), NameVar, WorldNameVarPtr)
	return cret
}

var xUserContentManagerRegisterScriptMessageHandlerWithReply func(uintptr, string, uintptr) bool

// Registers a new user script message handler in script world with name @world_name.
//
// Different from webkit_user_content_manager_register_script_message_handler(),
// when using this function to register the handler, the connected signal is
// script-message-with-reply-received, and a reply provided by the user is expected.
// Otherwise, the user will receive a default undefined value.
//
// If %NULL is passed as the @world_name, the default world will be used.
// See webkit_user_content_manager_register_script_message_handler() for full description.
//
// Registering a script message handler will fail if the requested
// name has been already registered before.
//
// The registered handler can be unregistered by using
// webkit_user_content_manager_unregister_script_message_handler().
func (x *UserContentManager) RegisterScriptMessageHandlerWithReply(NameVar string, WorldNameVar *string) bool {
	core.LazyRegister(&xUserContentManagerRegisterScriptMessageHandlerWithReply, "WEBKIT", "webkit_user_content_manager_register_script_message_handler_with_reply", false)

	WorldNameVarPtr := core.GStrdupNullable(WorldNameVar)
	defer core.GFreeNullable(WorldNameVarPtr)

	cret := xUserContentManagerRegisterScriptMessageHandlerWithReply(x.GoPointer(), NameVar, WorldNameVarPtr)
	return cret
}

var xUserContentManagerRemoveAllFilters func(uintptr)

// Removes all content filters from the given #WebKitUserContentManager.
func (x *UserContentManager) RemoveAllFilters() {
	core.LazyRegister(&xUserContentManagerRemoveAllFilters, "WEBKIT", "webkit_user_content_manager_remove_all_filters", false)

	xUserContentManagerRemoveAllFilters(x.GoPointer())
}

var xUserContentManagerRemoveAllScripts func(uintptr)

// Removes all user scripts from the given #WebKitUserContentManager
//
// See also webkit_user_content_manager_remove_script().
func (x *UserContentManager) RemoveAllScripts() {
	core.LazyRegister(&xUserContentManagerRemoveAllScripts, "WEBKIT", "webkit_user_content_manager_remove_all_scripts", false)

	xUserContentManagerRemoveAllScripts(x.GoPointer())
}

var xUserContentManagerRemoveAllStyleSheets func(uintptr)

// Removes all user style sheets from the given #WebKitUserContentManager.
func (x *UserContentManager) RemoveAllStyleSheets() {
	core.LazyRegister(&xUserContentManagerRemoveAllStyleSheets, "WEBKIT", "webkit_user_content_manager_remove_all_style_sheets", false)

	xUserContentManagerRemoveAllStyleSheets(x.GoPointer())
}

var xUserContentManagerRemoveFilter func(uintptr, *UserContentFilter)

// Removes a filter from the given #WebKitUserContentManager.
//
// Since 2.24
func (x *UserContentManager) RemoveFilter(FilterVar *UserContentFilter) {
	core.LazyRegister(&xUserContentManagerRemoveFilter, "WEBKIT", "webkit_user_content_manager_remove_filter", false)

	xUserContentManagerRemoveFilter(x.GoPointer(), FilterVar)
}

var xUserContentManagerRemoveFilterById func(uintptr, string)

// Removes a filter by the given identifier.
//
// Removes a filter from the given #WebKitUserContentManager given the
// identifier of a #WebKitUserContentFilter as returned by
// webkit_user_content_filter_get_identifier().
func (x *UserContentManager) RemoveFilterById(FilterIdVar string) {
	core.LazyRegister(&xUserContentManagerRemoveFilterById, "WEBKIT", "webkit_user_content_manager_remove_filter_by_id", false)

	xUserContentManagerRemoveFilterById(x.GoPointer(), FilterIdVar)
}

var xUserContentManagerRemoveScript func(uintptr, *UserScript)

// Removes a #WebKitUserScript from the given #WebKitUserContentManager.
//
// See also webkit_user_content_manager_remove_all_scripts().
func (x *UserContentManager) RemoveScript(ScriptVar *UserScript) {
	core.LazyRegister(&xUserContentManagerRemoveScript, "WEBKIT", "webkit_user_content_manager_remove_script", false)

	xUserContentManagerRemoveScript(x.GoPointer(), ScriptVar)
}

var xUserContentManagerRemoveStyleSheet func(uintptr, *UserStyleSheet)

// Removes a #WebKitUserStyleSheet from the given #WebKitUserContentManager.
//
// See also webkit_user_content_manager_remove_all_style_sheets().
func (x *UserContentManager) RemoveStyleSheet(StylesheetVar *UserStyleSheet) {
	core.LazyRegister(&xUserContentManagerRemoveStyleSheet, "WEBKIT", "webkit_user_content_manager_remove_style_sheet", false)

	xUserContentManagerRemoveStyleSheet(x.GoPointer(), StylesheetVar)
}

var xUserContentManagerUnregisterScriptMessageHandler func(uintptr, string, uintptr)

// Unregisters a previously registered message handler in script world with name @world_name.
// If %NULL is passed as the @world_name, the default world will be used.
//
// Note that this does *not* disconnect handlers for the
// #WebKitUserContentManager::script-message-received signal;
// they will be kept connected, but the signal will not be emitted
// unless the handler name is registered again.
//
// See also webkit_user_content_manager_register_script_message_handler().
func (x *UserContentManager) UnregisterScriptMessageHandler(NameVar string, WorldNameVar *string) {
	core.LazyRegister(&xUserContentManagerUnregisterScriptMessageHandler, "WEBKIT", "webkit_user_content_manager_unregister_script_message_handler", false)

	WorldNameVarPtr := core.GStrdupNullable(WorldNameVar)
	defer core.GFreeNullable(WorldNameVarPtr)

	xUserContentManagerUnregisterScriptMessageHandler(x.GoPointer(), NameVar, WorldNameVarPtr)
}

func (c *UserContentManager) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *UserContentManager) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// This signal is emitted when JavaScript in a web view calls
// &lt;code&gt;window.webkit.messageHandlers.&lt;name&gt;.postMessage()&lt;/code&gt;, after registering
// &lt;code&gt;&lt;name&gt;&lt;/code&gt; using
// webkit_user_content_manager_register_script_message_handler()
func (x *UserContentManager) ConnectScriptMessageReceived(cb *func(UserContentManager, uintptr)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.UserContentManager.ScriptMessageReceived", func(clsPtr uintptr, ValueVarp uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(UserContentManager, uintptr))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := UserContentManager{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa, ValueVarp)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "script-message-received", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// This signal is emitted when JavaScript in a web view calls
// &lt;code&gt;window.webkit.messageHandlers.&lt;name&gt;.postMessage()&lt;/code&gt;, after registering
// &lt;code&gt;&lt;name&gt;&lt;/code&gt; using
// webkit_user_content_manager_register_script_message_handler_with_reply()
//
// The given @reply can be used to send a return value with
// webkit_script_message_reply_return_value() or an error message with
// webkit_script_message_reply_return_error_message(). If none of them are
// called, an automatic reply with an undefined value will be sent.
//
// It is possible to handle the reply asynchronously, by simply calling
// g_object_ref() on the @reply and returning %TRUE.
func (x *UserContentManager) ConnectScriptMessageWithReplyReceived(cb *func(UserContentManager, uintptr, uintptr) bool) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.UserContentManager.ScriptMessageWithReplyReceived", func(clsPtr uintptr, ValueVarp uintptr, ReplyVarp uintptr, signalData uintptr) bool {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			var zero bool
			return zero
		}
		cb, ok := handler.(*func(UserContentManager, uintptr, uintptr) bool)
		if !ok || cb == nil || *cb == nil {
			var zero bool
			return zero
		}
		fa := UserContentManager{}
		fa.Ptr = clsPtr
		cbFn := *cb

		return cbFn(fa, ValueVarp, ReplyVarp)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "script-message-with-reply-received", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	UserContentManagerGLibType()
}
