// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type MediaKeySystemPermissionRequestClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *MediaKeySystemPermissionRequestClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func MediaKeySystemPermissionRequestClassNewFromInternalPtr(ptr uintptr) *MediaKeySystemPermissionRequestClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*MediaKeySystemPermissionRequestClass)(rawPtr)
}

var xMediaKeySystemPermissionGetName func(uintptr) string

// Get the key system for which access permission is being requested.
func MediaKeySystemPermissionGetName(RequestVar *MediaKeySystemPermissionRequest) string {
	core.LazyRegister(&xMediaKeySystemPermissionGetName, "WEBKIT", "webkit_media_key_system_permission_get_name", false)

	cret := xMediaKeySystemPermissionGetName(RequestVar.GoPointer())
	return cret
}

// A permission request for using an EME Content Decryption Module.
//
// WebKitMediaKeySystemPermissionRequest represents a request for permission to decide whether
// WebKit should use the given CDM to access protected media when requested through the
// MediaKeySystem API.
//
// When a WebKitMediaKeySystemPermissionRequest is not handled by the user,
// it is denied by default.
//
// When handling this permission request the application may perform additional installation of the
// requested CDM, unless it is already present on the host system.
type MediaKeySystemPermissionRequest struct {
	gobject.Object
}

var xMediaKeySystemPermissionRequestGLibType func() types.GType

func MediaKeySystemPermissionRequestGLibType() types.GType {
	core.LazyRegister(&xMediaKeySystemPermissionRequestGLibType, "WEBKIT", "webkit_media_key_system_permission_request_get_type", false)
	return xMediaKeySystemPermissionRequestGLibType()
}

func MediaKeySystemPermissionRequestNewFromInternalPtr(ptr uintptr) *MediaKeySystemPermissionRequest {
	cls := &MediaKeySystemPermissionRequest{}
	cls.Ptr = ptr
	return cls
}

func (c *MediaKeySystemPermissionRequest) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *MediaKeySystemPermissionRequest) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// Allow the action which triggered this request.
func (x *MediaKeySystemPermissionRequest) Allow() {
	XWebkitPermissionRequestAllow(x.GoPointer())
}

// Deny the action which triggered this request.
func (x *MediaKeySystemPermissionRequest) Deny() {
	XWebkitPermissionRequestDeny(x.GoPointer())
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	MediaKeySystemPermissionRequestGLibType()
}
