// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// A compiled set of rules which applied to resource loads.
type UserContentFilter struct {
	_ structs.HostLayout
}

var xUserContentFilterGLibType func() types.GType

func UserContentFilterGLibType() types.GType {
	core.LazyRegister(&xUserContentFilterGLibType, "WEBKIT", "webkit_user_content_filter_get_type", false)
	return xUserContentFilterGLibType()
}

func (x *UserContentFilter) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func UserContentFilterNewFromInternalPtr(ptr uintptr) *UserContentFilter {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*UserContentFilter)(rawPtr)
}

var xUserContentFilterGetIdentifier func(uintptr) string

// Obtain the identifier previously used to save the @user_content_filter.
//
// Obtain the identifier previously used to save the @user_content_filter in the
// #WebKitUserContentFilterStore.
func (x *UserContentFilter) GetIdentifier() string {
	core.LazyRegister(&xUserContentFilterGetIdentifier, "WEBKIT", "webkit_user_content_filter_get_identifier", false)

	cret := xUserContentFilterGetIdentifier(x.GoPointer())
	return cret
}

var xUserContentFilterRef func(uintptr) uintptr

// Atomically increments the reference count of @user_content_filter by one.
//
// This function is MT-safe and may be called from any thread.
func (x *UserContentFilter) Ref() *UserContentFilter {
	core.LazyRegister(&xUserContentFilterRef, "WEBKIT", "webkit_user_content_filter_ref", false)

	cret := xUserContentFilterRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*UserContentFilter)(unsafe.Pointer(cret))
}

var xUserContentFilterUnref func(uintptr)

// Atomically decrements the reference count of @user_content_filter by one.
//
// If the reference count drops to 0, all the memory allocated by the
// #WebKitUserContentFilter is released. This function is MT-safe and may
// be called from any thread.
func (x *UserContentFilter) Unref() {
	core.LazyRegister(&xUserContentFilterUnref, "WEBKIT", "webkit_user_content_filter_unref", false)

	xUserContentFilterUnref(x.GoPointer())
}

// A JavaScript snippet which can be injected in loaded pages.
type UserScript struct {
	_ structs.HostLayout
}

var xUserScriptGLibType func() types.GType

func UserScriptGLibType() types.GType {
	core.LazyRegister(&xUserScriptGLibType, "WEBKIT", "webkit_user_script_get_type", false)
	return xUserScriptGLibType()
}

func (x *UserScript) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func UserScriptNewFromInternalPtr(ptr uintptr) *UserScript {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*UserScript)(rawPtr)
}

var xNewUserScript func(string, UserContentInjectedFrames, UserScriptInjectionTime, []string, []string) uintptr

// Creates a new user script.
//
// Scripts can be applied to some URIs
// only by passing non-null values for @allow_list or @block_list. Passing a
// %NULL allow_list implies that all URIs are on the allow_list. The script
// is applied if an URI matches the allow_list and not the block_list.
// URI patterns must be of the form `[protocol]://[host]/[path]`, where the
// *host* and *path* components can contain the wildcard character (`*`) to
// represent zero or more other characters.
func NewUserScript(SourceVar string, InjectedFramesVar UserContentInjectedFrames, InjectionTimeVar UserScriptInjectionTime, AllowListVar []string, BlockListVar []string) *UserScript {
	core.LazyRegister(&xNewUserScript, "WEBKIT", "webkit_user_script_new", false)

	cret := xNewUserScript(SourceVar, InjectedFramesVar, InjectionTimeVar, AllowListVar, BlockListVar)
	if cret == 0 {
		return nil
	}
	return (*UserScript)(unsafe.Pointer(cret))
}

var xNewUserScriptForWorld func(string, UserContentInjectedFrames, UserScriptInjectionTime, string, []string, []string) uintptr

// Creates a new user script for script world with name @world_name.
//
// See webkit_user_script_new() for a full description.
func NewUserScriptForWorld(SourceVar string, InjectedFramesVar UserContentInjectedFrames, InjectionTimeVar UserScriptInjectionTime, WorldNameVar string, AllowListVar []string, BlockListVar []string) *UserScript {
	core.LazyRegister(&xNewUserScriptForWorld, "WEBKIT", "webkit_user_script_new_for_world", false)

	cret := xNewUserScriptForWorld(SourceVar, InjectedFramesVar, InjectionTimeVar, WorldNameVar, AllowListVar, BlockListVar)
	if cret == 0 {
		return nil
	}
	return (*UserScript)(unsafe.Pointer(cret))
}

var xUserScriptRef func(uintptr) uintptr

// Atomically increments the reference count of @user_script by one.
//
// This function is MT-safe and may be called from any thread.
func (x *UserScript) Ref() *UserScript {
	core.LazyRegister(&xUserScriptRef, "WEBKIT", "webkit_user_script_ref", false)

	cret := xUserScriptRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*UserScript)(unsafe.Pointer(cret))
}

var xUserScriptUnref func(uintptr)

// Atomically decrements the reference count of @user_script by one.
//
// If the reference count drops to 0, all memory allocated by
// #WebKitUserScript is released. This function is MT-safe and may be called
// from any thread.
func (x *UserScript) Unref() {
	core.LazyRegister(&xUserScriptUnref, "WEBKIT", "webkit_user_script_unref", false)

	xUserScriptUnref(x.GoPointer())
}

// A CSS style sheet which can be injected in loaded pages.
type UserStyleSheet struct {
	_ structs.HostLayout
}

var xUserStyleSheetGLibType func() types.GType

func UserStyleSheetGLibType() types.GType {
	core.LazyRegister(&xUserStyleSheetGLibType, "WEBKIT", "webkit_user_style_sheet_get_type", false)
	return xUserStyleSheetGLibType()
}

func (x *UserStyleSheet) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func UserStyleSheetNewFromInternalPtr(ptr uintptr) *UserStyleSheet {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*UserStyleSheet)(rawPtr)
}

var xNewUserStyleSheet func(string, UserContentInjectedFrames, UserStyleLevel, []string, []string) uintptr

// Creates a new user style sheet.
//
// Style sheets can be applied to some URIs
// only by passing non-null values for @allow_list or @block_list. Passing a
// %NULL allow_list implies that all URIs are on the allow_list. The style
// sheet is applied if an URI matches the allow_list and not the block_list.
// URI patterns must be of the form `[protocol]://[host]/[path]`, where the
// *host* and *path* components can contain the wildcard character (`*`) to
// represent zero or more other characters.
func NewUserStyleSheet(SourceVar string, InjectedFramesVar UserContentInjectedFrames, LevelVar UserStyleLevel, AllowListVar []string, BlockListVar []string) *UserStyleSheet {
	core.LazyRegister(&xNewUserStyleSheet, "WEBKIT", "webkit_user_style_sheet_new", false)

	cret := xNewUserStyleSheet(SourceVar, InjectedFramesVar, LevelVar, AllowListVar, BlockListVar)
	if cret == 0 {
		return nil
	}
	return (*UserStyleSheet)(unsafe.Pointer(cret))
}

var xNewUserStyleSheetForWorld func(string, UserContentInjectedFrames, UserStyleLevel, string, []string, []string) uintptr

// Creates a new user style sheet for script world.
//
// Creates a new user style sheet for script world with name @world_name.
// See webkit_user_style_sheet_new() for a full description.
func NewUserStyleSheetForWorld(SourceVar string, InjectedFramesVar UserContentInjectedFrames, LevelVar UserStyleLevel, WorldNameVar string, AllowListVar []string, BlockListVar []string) *UserStyleSheet {
	core.LazyRegister(&xNewUserStyleSheetForWorld, "WEBKIT", "webkit_user_style_sheet_new_for_world", false)

	cret := xNewUserStyleSheetForWorld(SourceVar, InjectedFramesVar, LevelVar, WorldNameVar, AllowListVar, BlockListVar)
	if cret == 0 {
		return nil
	}
	return (*UserStyleSheet)(unsafe.Pointer(cret))
}

var xUserStyleSheetRef func(uintptr) uintptr

// Atomically increments the reference count of @user_style_sheet by one.
//
// This function is MT-safe and may be called from any thread.
func (x *UserStyleSheet) Ref() *UserStyleSheet {
	core.LazyRegister(&xUserStyleSheetRef, "WEBKIT", "webkit_user_style_sheet_ref", false)

	cret := xUserStyleSheetRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*UserStyleSheet)(unsafe.Pointer(cret))
}

var xUserStyleSheetUnref func(uintptr)

// Atomically decrements the reference count of @user_style_sheet by one.
//
// If the reference count drops to 0, all memory allocated by
// #WebKitUserStyleSheet is released. This function is MT-safe and may be
// called from any thread.
func (x *UserStyleSheet) Unref() {
	core.LazyRegister(&xUserStyleSheetUnref, "WEBKIT", "webkit_user_style_sheet_unref", false)

	xUserStyleSheetUnref(x.GoPointer())
}

// Specifies in which frames user style sheets are to be inserted in.
type UserContentInjectedFrames int

var xUserContentInjectedFramesGLibType func() types.GType

func UserContentInjectedFramesGLibType() types.GType {
	core.LazyRegister(&xUserContentInjectedFramesGLibType, "WEBKIT", "webkit_user_content_injected_frames_get_type", false)
	return xUserContentInjectedFramesGLibType()
}

const (

	// Insert the user style
	//   sheet in all the frames loaded by the web view, including
	//   nested frames. This is the default.
	UserContentInjectAllFramesValue UserContentInjectedFrames = 0
	// Insert the user style
	//   sheet *only* in the top-level frame loaded by the web view,
	//   and *not* in the nested frames.
	UserContentInjectTopFrameValue UserContentInjectedFrames = 1
)

// Specifies at which place of documents an user script will be inserted.
type UserScriptInjectionTime int

var xUserScriptInjectionTimeGLibType func() types.GType

func UserScriptInjectionTimeGLibType() types.GType {
	core.LazyRegister(&xUserScriptInjectionTimeGLibType, "WEBKIT", "webkit_user_script_injection_time_get_type", false)
	return xUserScriptInjectionTimeGLibType()
}

const (

	// Insert the code of the user
	//   script at the beginning of loaded documents. This is the default.
	UserScriptInjectAtDocumentStartValue UserScriptInjectionTime = 0
	// Insert the code of the user
	//   script at the end of the loaded documents.
	UserScriptInjectAtDocumentEndValue UserScriptInjectionTime = 1
)

// Specifies how to treat an user style sheet.
type UserStyleLevel int

var xUserStyleLevelGLibType func() types.GType

func UserStyleLevelGLibType() types.GType {
	core.LazyRegister(&xUserStyleLevelGLibType, "WEBKIT", "webkit_user_style_level_get_type", false)
	return xUserStyleLevelGLibType()
}

const (

	// The style sheet is an user style sheet,
	//   its contents always override other style sheets. This is the default.
	UserStyleLevelUserValue UserStyleLevel = 0
	// The style sheet will be treated as if
	//   it was provided by the loaded documents. That means other user style
	//   sheets may still override it.
	UserStyleLevelAuthorValue UserStyleLevel = 1
)

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
}
