// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type GeolocationManagerClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *GeolocationManagerClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func GeolocationManagerClassNewFromInternalPtr(ptr uintptr) *GeolocationManagerClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*GeolocationManagerClass)(rawPtr)
}

// An opaque struct to provide position updates to a #WebKitGeolocationManager.
//
// WebKitGeolocationPosition is an opaque struct used to provide position updates to a
// #WebKitGeolocationManager using webkit_geolocation_manager_update_position().
type GeolocationPosition struct {
	_ structs.HostLayout
}

var xGeolocationPositionGLibType func() types.GType

func GeolocationPositionGLibType() types.GType {
	core.LazyRegister(&xGeolocationPositionGLibType, "WEBKIT", "webkit_geolocation_position_get_type", false)
	return xGeolocationPositionGLibType()
}

func (x *GeolocationPosition) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func GeolocationPositionNewFromInternalPtr(ptr uintptr) *GeolocationPosition {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*GeolocationPosition)(rawPtr)
}

var xNewGeolocationPosition func(float64, float64, float64) uintptr

// Create a new #WebKitGeolocationPosition.
func NewGeolocationPosition(LatitudeVar float64, LongitudeVar float64, AccuracyVar float64) *GeolocationPosition {
	core.LazyRegister(&xNewGeolocationPosition, "WEBKIT", "webkit_geolocation_position_new", false)

	cret := xNewGeolocationPosition(LatitudeVar, LongitudeVar, AccuracyVar)
	if cret == 0 {
		return nil
	}
	return (*GeolocationPosition)(unsafe.Pointer(cret))
}

var xGeolocationPositionCopy func(uintptr) uintptr

// Make a copy of the #WebKitGeolocationPosition.
func (x *GeolocationPosition) Copy() *GeolocationPosition {
	core.LazyRegister(&xGeolocationPositionCopy, "WEBKIT", "webkit_geolocation_position_copy", false)

	cret := xGeolocationPositionCopy(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*GeolocationPosition)(unsafe.Pointer(cret))
}

var xGeolocationPositionFree func(uintptr)

// Free the #WebKitGeolocationPosition
func (x *GeolocationPosition) Free() {
	core.LazyRegister(&xGeolocationPositionFree, "WEBKIT", "webkit_geolocation_position_free", false)

	xGeolocationPositionFree(x.GoPointer())
}

var xGeolocationPositionSetAltitude func(uintptr, float64)

// Set the @position altitude.
func (x *GeolocationPosition) SetAltitude(AltitudeVar float64) {
	core.LazyRegister(&xGeolocationPositionSetAltitude, "WEBKIT", "webkit_geolocation_position_set_altitude", false)

	xGeolocationPositionSetAltitude(x.GoPointer(), AltitudeVar)
}

var xGeolocationPositionSetAltitudeAccuracy func(uintptr, float64)

// Set the accuracy of @position altitude.
func (x *GeolocationPosition) SetAltitudeAccuracy(AltitudeAccuracyVar float64) {
	core.LazyRegister(&xGeolocationPositionSetAltitudeAccuracy, "WEBKIT", "webkit_geolocation_position_set_altitude_accuracy", false)

	xGeolocationPositionSetAltitudeAccuracy(x.GoPointer(), AltitudeAccuracyVar)
}

var xGeolocationPositionSetHeading func(uintptr, float64)

// Set the @position heading.
//
// Set the @position heading, as a positive angle between the direction of movement and the North
// direction, in clockwise direction.
func (x *GeolocationPosition) SetHeading(HeadingVar float64) {
	core.LazyRegister(&xGeolocationPositionSetHeading, "WEBKIT", "webkit_geolocation_position_set_heading", false)

	xGeolocationPositionSetHeading(x.GoPointer(), HeadingVar)
}

var xGeolocationPositionSetSpeed func(uintptr, float64)

// Set the @position speed.
func (x *GeolocationPosition) SetSpeed(SpeedVar float64) {
	core.LazyRegister(&xGeolocationPositionSetSpeed, "WEBKIT", "webkit_geolocation_position_set_speed", false)

	xGeolocationPositionSetSpeed(x.GoPointer(), SpeedVar)
}

var xGeolocationPositionSetTimestamp func(uintptr, uint64)

// Set the @position timestamp.
//
// By default it's the time when the @position was created.
func (x *GeolocationPosition) SetTimestamp(TimestampVar uint64) {
	core.LazyRegister(&xGeolocationPositionSetTimestamp, "WEBKIT", "webkit_geolocation_position_set_timestamp", false)

	xGeolocationPositionSetTimestamp(x.GoPointer(), TimestampVar)
}

// Geolocation manager.
//
// WebKitGeolocationManager provides API to get the geographical position of the user.
// Once a #WebKitGeolocationPermissionRequest is allowed, when WebKit needs to know the
// user location #WebKitGeolocationManager::start signal is emitted. If the signal is handled
// and returns %TRUE, the application is responsible for providing the position every time it's
// updated by calling webkit_geolocation_manager_update_position(). The signal #WebKitGeolocationManager::stop
// will be emitted when location updates are no longer needed.
type GeolocationManager struct {
	gobject.Object
}

var xGeolocationManagerGLibType func() types.GType

func GeolocationManagerGLibType() types.GType {
	core.LazyRegister(&xGeolocationManagerGLibType, "WEBKIT", "webkit_geolocation_manager_get_type", false)
	return xGeolocationManagerGLibType()
}

func GeolocationManagerNewFromInternalPtr(ptr uintptr) *GeolocationManager {
	cls := &GeolocationManager{}
	cls.Ptr = ptr
	return cls
}

var xGeolocationManagerFailed func(uintptr, string)

// Notify @manager that determining the position failed.
func (x *GeolocationManager) Failed(ErrorMessageVar string) {
	core.LazyRegister(&xGeolocationManagerFailed, "WEBKIT", "webkit_geolocation_manager_failed", false)

	xGeolocationManagerFailed(x.GoPointer(), ErrorMessageVar)
}

var xGeolocationManagerGetEnableHighAccuracy func(uintptr) bool

// Get whether high accuracy is enabled.
func (x *GeolocationManager) GetEnableHighAccuracy() bool {
	core.LazyRegister(&xGeolocationManagerGetEnableHighAccuracy, "WEBKIT", "webkit_geolocation_manager_get_enable_high_accuracy", false)

	cret := xGeolocationManagerGetEnableHighAccuracy(x.GoPointer())
	return cret
}

var xGeolocationManagerUpdatePosition func(uintptr, *GeolocationPosition)

// Notify @manager that position has been updated to @position.
func (x *GeolocationManager) UpdatePosition(PositionVar *GeolocationPosition) {
	core.LazyRegister(&xGeolocationManagerUpdatePosition, "WEBKIT", "webkit_geolocation_manager_update_position", false)

	xGeolocationManagerUpdatePosition(x.GoPointer(), PositionVar)
}

func (c *GeolocationManager) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *GeolocationManager) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// GetPropertyEnableHighAccuracy gets the "enable-high-accuracy" property.
// Whether high accuracy is enabled. This is a read-only property that will be
// set to %TRUE when a #WebKitGeolocationManager needs to get accurate position updates.
// You can connect to notify::enable-high-accuracy signal to monitor it.
func (x *GeolocationManager) GetPropertyEnableHighAccuracy() bool {
	var v gobject.Value
	x.GetProperty("enable-high-accuracy", &v)
	return v.GetBoolean()
}

// The signal is emitted to notify that @manager needs to start receiving
// position updates. After this signal is emitted the user should provide
// the updates using webkit_geolocation_manager_update_position() every time
// the position changes, or use webkit_geolocation_manager_failed() in case
// it isn't possible to determine the current position.
//
// If the signal is not handled, WebKit will try to determine the position
// using GeoClue if available.
func (x *GeolocationManager) ConnectStart(cb *func(GeolocationManager) bool) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.GeolocationManager.Start", func(clsPtr uintptr, signalData uintptr) bool {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			var zero bool
			return zero
		}
		cb, ok := handler.(*func(GeolocationManager) bool)
		if !ok || cb == nil || *cb == nil {
			var zero bool
			return zero
		}
		fa := GeolocationManager{}
		fa.Ptr = clsPtr
		cbFn := *cb

		return cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "start", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// The signal is emitted to notify that @manager doesn't need to receive
// position updates anymore.
func (x *GeolocationManager) ConnectStop(cb *func(GeolocationManager)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.GeolocationManager.Stop", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(GeolocationManager))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := GeolocationManager{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "stop", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	GeolocationManagerGLibType()
}
