// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// Enum values used to denote the various download errors.
type DownloadError int

var xDownloadErrorGLibType func() types.GType

func DownloadErrorGLibType() types.GType {
	core.LazyRegister(&xDownloadErrorGLibType, "WEBKIT", "webkit_download_error_get_type", false)
	return xDownloadErrorGLibType()
}

const (

	// Download failure due to network error
	DownloadErrorNetworkValue DownloadError = 499
	// Download was cancelled by user
	DownloadErrorCancelledByUserValue DownloadError = 400
	// Download failure due to destination error
	DownloadErrorDestinationValue DownloadError = 401
)

// Enum values used to denote errors happening when executing JavaScript
type JavascriptError int

var xJavascriptErrorGLibType func() types.GType

func JavascriptErrorGLibType() types.GType {
	core.LazyRegister(&xJavascriptErrorGLibType, "WEBKIT", "webkit_javascript_error_get_type", false)
	return xJavascriptErrorGLibType()
}

const (

	// An exception was raised in JavaScript execution
	JavascriptErrorScriptFailedValue JavascriptError = 699
	// An unsupported parameter has been used to call and async function from API. Since 2.40
	JavascriptErrorInvalidParameterValue JavascriptError = 600
	// The result of JavaScript execution could not be returned. Since 2.40
	JavascriptErrorInvalidResultValue JavascriptError = 601
)

// Enum values used to denote the various media errors.
type MediaError int

var xMediaErrorGLibType func() types.GType

func MediaErrorGLibType() types.GType {
	core.LazyRegister(&xMediaErrorGLibType, "WEBKIT", "webkit_media_error_get_type", false)
	return xMediaErrorGLibType()
}

const (

	// Preliminary load failure for media content types. A new load will be started to perform the media load. Since: 2.40
	MediaErrorWillHandleLoadValue MediaError = 204
)

// Enum values used to denote the various network errors.
type NetworkError int

var xNetworkErrorGLibType func() types.GType

func NetworkErrorGLibType() types.GType {
	core.LazyRegister(&xNetworkErrorGLibType, "WEBKIT", "webkit_network_error_get_type", false)
	return xNetworkErrorGLibType()
}

const (

	// Generic load failure
	NetworkErrorFailedValue NetworkError = 399
	// Load failure due to transport error
	NetworkErrorTransportValue NetworkError = 300
	// Load failure due to unknown protocol
	NetworkErrorUnknownProtocolValue NetworkError = 301
	// Load failure due to cancellation
	NetworkErrorCancelledValue NetworkError = 302
	// Load failure due to missing file
	NetworkErrorFileDoesNotExistValue NetworkError = 303
)

// Enum values used to denote the various policy errors.
type PolicyError int

var xPolicyErrorGLibType func() types.GType

func PolicyErrorGLibType() types.GType {
	core.LazyRegister(&xPolicyErrorGLibType, "WEBKIT", "webkit_policy_error_get_type", false)
	return xPolicyErrorGLibType()
}

const (

	// Generic load failure due to policy error
	PolicyErrorFailedValue PolicyError = 199
	// Load failure due to unsupported mime type
	PolicyErrorCannotShowMimeTypeValue PolicyError = 100
	// Load failure due to URI that can not be shown
	PolicyErrorCannotShowUriValue PolicyError = 101
	// Load failure due to frame load interruption by policy change
	PolicyErrorFrameLoadInterruptedByPolicyChangeValue PolicyError = 102
	// Load failure due to port restriction
	PolicyErrorCannotUseRestrictedPortValue PolicyError = 103
)

// Enum values used to denote the various print errors.
type PrintError int

var xPrintErrorGLibType func() types.GType

func PrintErrorGLibType() types.GType {
	core.LazyRegister(&xPrintErrorGLibType, "WEBKIT", "webkit_print_error_get_type", false)
	return xPrintErrorGLibType()
}

const (

	// Unspecified error during a print operation
	PrintErrorGeneralValue PrintError = 599
	// Selected printer cannot be found
	PrintErrorPrinterNotFoundValue PrintError = 500
	// Invalid page range
	PrintErrorInvalidPageRangeValue PrintError = 501
)

// Enum values used to denote errors happening when creating snapshots of #WebKitWebView
type SnapshotError int

var xSnapshotErrorGLibType func() types.GType

func SnapshotErrorGLibType() types.GType {
	core.LazyRegister(&xSnapshotErrorGLibType, "WEBKIT", "webkit_snapshot_error_get_type", false)
	return xSnapshotErrorGLibType()
}

const (

	// An error occurred when creating a webpage snapshot.
	SnapshotErrorFailedToCreateValue SnapshotError = 799
)

// Errors that can occur while compiling content filters.
type UserContentFilterError int

var xUserContentFilterErrorGLibType func() types.GType

func UserContentFilterErrorGLibType() types.GType {
	core.LazyRegister(&xUserContentFilterErrorGLibType, "WEBKIT", "webkit_user_content_filter_error_get_type", false)
	return xUserContentFilterErrorGLibType()
}

const (

	// The JSON source for a content filter is invalid.
	UserContentFilterErrorInvalidSourceValue UserContentFilterError = 0
	// The requested content filter could not be found.
	UserContentFilterErrorNotFoundValue UserContentFilterError = 1
)

// Enum values used to denote errors happening when parsing a #WebKitWebExtension
type WebExtensionError int

var xWebExtensionErrorGLibType func() types.GType

func WebExtensionErrorGLibType() types.GType {
	core.LazyRegister(&xWebExtensionErrorGLibType, "WEBKIT", "webkit_web_extension_error_get_type", false)
	return xWebExtensionErrorGLibType()
}

const (

	// An unknown error occured.
	WebExtensionErrorUnknownValue WebExtensionError = 899
	// A specified resource was not found on disk.
	WebExtensionErrorResourceNotFoundValue WebExtensionError = 800
	// A resource failed the bundle's code signature checks.
	WebExtensionErrorInvalidResourceCodeSignatureValue WebExtensionError = 801
	// An invalid `manifest.json` was encountered.
	WebExtensionErrorInvalidManifestValue WebExtensionError = 802
	// The manifest version is not supported.
	WebExtensionErrorUnsupportedManifestVersionValue WebExtensionError = 803
	// An invalid manifest entry was encountered.
	WebExtensionErrorInvalidManifestEntryValue WebExtensionError = 804
	// An invalid declarative net request entry was encountered.
	WebExtensionErrorInvalidDeclarativeNetRequestEntryValue WebExtensionError = 805
	// The extension specified background persistence that was not compatible with the platform or features requested.
	WebExtensionErrorInvalidBackgroundPersistenceValue WebExtensionError = 806
	// The archive file is invalid or corrupt.
	WebExtensionErrorInvalidArchiveValue WebExtensionError = 807
)

// Enum values used to denote errors happening when creating a #WebKitWebExtensionMatchPattern
type WebExtensionMatchPatternError int

var xWebExtensionMatchPatternErrorGLibType func() types.GType

func WebExtensionMatchPatternErrorGLibType() types.GType {
	core.LazyRegister(&xWebExtensionMatchPatternErrorGLibType, "WEBKIT", "webkit_web_extension_match_pattern_error_get_type", false)
	return xWebExtensionMatchPatternErrorGLibType()
}

const (

	// An unknown error occured.
	WebExtensionMatchPatternErrorUnknownValue WebExtensionMatchPatternError = 899
	// The scheme component was invalid.
	WebExtensionMatchPatternErrorInvalidSchemeValue WebExtensionMatchPatternError = 808
	// The host component was invalid.
	WebExtensionMatchPatternErrorInvalidHostValue WebExtensionMatchPatternError = 809
	// The path component was invalid.
	WebExtensionMatchPatternErrorInvalidPathValue WebExtensionMatchPatternError = 810
)

var xDownloadErrorQuark func() glib.Quark

// Gets the quark for the domain of download errors.
func DownloadErrorQuark() glib.Quark {
	core.LazyRegister(&xDownloadErrorQuark, "WEBKIT", "webkit_download_error_quark", false)

	cret := xDownloadErrorQuark()
	return cret
}

var xJavascriptErrorQuark func() glib.Quark

// Gets the quark for the domain of JavaScript errors.
func JavascriptErrorQuark() glib.Quark {
	core.LazyRegister(&xJavascriptErrorQuark, "WEBKIT", "webkit_javascript_error_quark", false)

	cret := xJavascriptErrorQuark()
	return cret
}

var xMediaErrorQuark func() glib.Quark

// Gets the quark for the domain of media errors.
func MediaErrorQuark() glib.Quark {
	core.LazyRegister(&xMediaErrorQuark, "WEBKIT", "webkit_media_error_quark", false)

	cret := xMediaErrorQuark()
	return cret
}

var xNetworkErrorQuark func() glib.Quark

// Gets the quark for the domain of networking errors.
func NetworkErrorQuark() glib.Quark {
	core.LazyRegister(&xNetworkErrorQuark, "WEBKIT", "webkit_network_error_quark", false)

	cret := xNetworkErrorQuark()
	return cret
}

var xPolicyErrorQuark func() glib.Quark

// Gets the quark for the domain of policy errors.
func PolicyErrorQuark() glib.Quark {
	core.LazyRegister(&xPolicyErrorQuark, "WEBKIT", "webkit_policy_error_quark", false)

	cret := xPolicyErrorQuark()
	return cret
}

var xPrintErrorQuark func() glib.Quark

// Gets the quark for the domain of printing errors.
func PrintErrorQuark() glib.Quark {
	core.LazyRegister(&xPrintErrorQuark, "WEBKIT", "webkit_print_error_quark", false)

	cret := xPrintErrorQuark()
	return cret
}

var xSnapshotErrorQuark func() glib.Quark

// Gets the quark for the domain of page snapshot errors.
func SnapshotErrorQuark() glib.Quark {
	core.LazyRegister(&xSnapshotErrorQuark, "WEBKIT", "webkit_snapshot_error_quark", false)

	cret := xSnapshotErrorQuark()
	return cret
}

var xUserContentFilterErrorQuark func() glib.Quark

// Gets the quark for the domain of user content filter errors.
func UserContentFilterErrorQuark() glib.Quark {
	core.LazyRegister(&xUserContentFilterErrorQuark, "WEBKIT", "webkit_user_content_filter_error_quark", false)

	cret := xUserContentFilterErrorQuark()
	return cret
}

var xWebExtensionErrorQuark func() glib.Quark

// Gets the quark for the domain of Web Extension errors.
func WebExtensionErrorQuark() glib.Quark {
	core.LazyRegister(&xWebExtensionErrorQuark, "WEBKIT", "webkit_web_extension_error_quark", false)

	cret := xWebExtensionErrorQuark()
	return cret
}

var xWebExtensionMatchPatternErrorQuark func() glib.Quark

// Gets the quark for the domain of Web Extension Match Pattern errors.
func WebExtensionMatchPatternErrorQuark() glib.Quark {
	core.LazyRegister(&xWebExtensionMatchPatternErrorQuark, "WEBKIT", "webkit_web_extension_match_pattern_error_quark", false)

	cret := xWebExtensionMatchPatternErrorQuark()
	return cret
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
}
