// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// Handles serialization of a web view's browsing state.
type WebViewSessionState struct {
	_ structs.HostLayout
}

var xWebViewSessionStateGLibType func() types.GType

func WebViewSessionStateGLibType() types.GType {
	core.LazyRegister(&xWebViewSessionStateGLibType, "WEBKIT", "webkit_web_view_session_state_get_type", false)
	return xWebViewSessionStateGLibType()
}

func (x *WebViewSessionState) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func WebViewSessionStateNewFromInternalPtr(ptr uintptr) *WebViewSessionState {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*WebViewSessionState)(rawPtr)
}

var xNewWebViewSessionState func(*glib.Bytes) uintptr

// Creates a new #WebKitWebViewSessionState from serialized data.
func NewWebViewSessionState(DataVar *glib.Bytes) *WebViewSessionState {
	core.LazyRegister(&xNewWebViewSessionState, "WEBKIT", "webkit_web_view_session_state_new", false)

	cret := xNewWebViewSessionState(DataVar)
	if cret == 0 {
		return nil
	}
	return (*WebViewSessionState)(unsafe.Pointer(cret))
}

var xWebViewSessionStateRef func(uintptr) uintptr

// Atomically increments the reference count of @state by one.
//
// This
// function is MT-safe and may be called from any thread.
func (x *WebViewSessionState) Ref() *WebViewSessionState {
	core.LazyRegister(&xWebViewSessionStateRef, "WEBKIT", "webkit_web_view_session_state_ref", false)

	cret := xWebViewSessionStateRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*WebViewSessionState)(unsafe.Pointer(cret))
}

var xWebViewSessionStateSerialize func(uintptr) uintptr

// Serializes a #WebKitWebViewSessionState.
func (x *WebViewSessionState) Serialize() *glib.Bytes {
	core.LazyRegister(&xWebViewSessionStateSerialize, "WEBKIT", "webkit_web_view_session_state_serialize", false)

	cret := xWebViewSessionStateSerialize(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*glib.Bytes)(unsafe.Pointer(cret))
}

var xWebViewSessionStateUnref func(uintptr)

// Atomically decrements the reference count of @state by one.
//
// If the
// reference count drops to 0, all memory allocated by the #WebKitWebViewSessionState is
// released. This function is MT-safe and may be called from any thread.
func (x *WebViewSessionState) Unref() {
	core.LazyRegister(&xWebViewSessionStateUnref, "WEBKIT", "webkit_web_view_session_state_unref", false)

	xWebViewSessionStateUnref(x.GoPointer())
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
}
