// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gdk"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type OptionMenuClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *OptionMenuClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func OptionMenuClassNewFromInternalPtr(ptr uintptr) *OptionMenuClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*OptionMenuClass)(rawPtr)
}

// Represents the dropdown menu of a `select` element in a #WebKitWebView.
//
// When a select element in a #WebKitWebView needs to display a dropdown menu, the signal
// #WebKitWebView::show-option-menu is emitted, providing a WebKitOptionMenu with the
// #WebKitOptionMenuItem&lt;!-- --&gt;s that should be displayed.
type OptionMenu struct {
	gobject.Object
}

var xOptionMenuGLibType func() types.GType

func OptionMenuGLibType() types.GType {
	core.LazyRegister(&xOptionMenuGLibType, "WEBKIT", "webkit_option_menu_get_type", false)
	return xOptionMenuGLibType()
}

func OptionMenuNewFromInternalPtr(ptr uintptr) *OptionMenu {
	cls := &OptionMenu{}
	cls.Ptr = ptr
	return cls
}

var xOptionMenuActivateItem func(uintptr, uint)

// Activates the #WebKitOptionMenuItem at @index in @menu.
//
// Activating an item changes the value
// of the element making the item the active one. You are expected to close the menu with
// webkit_option_menu_close() after activating an item, calling this function again will have no
// effect.
func (x *OptionMenu) ActivateItem(IndexVar uint) {
	core.LazyRegister(&xOptionMenuActivateItem, "WEBKIT", "webkit_option_menu_activate_item", false)

	xOptionMenuActivateItem(x.GoPointer(), IndexVar)
}

var xOptionMenuClose func(uintptr)

// Request to close a #WebKitOptionMenu.
//
// This emits WebKitOptionMenu::close signal.
// This function should always be called to notify WebKit that the associated
// menu has been closed. If the menu is closed and neither webkit_option_menu_select_item()
// nor webkit_option_menu_activate_item() have been called, the element value remains
// unchanged.
func (x *OptionMenu) Close() {
	core.LazyRegister(&xOptionMenuClose, "WEBKIT", "webkit_option_menu_close", false)

	xOptionMenuClose(x.GoPointer())
}

var xOptionMenuGetEvent func(uintptr) uintptr

// Gets the #GdkEvent that triggered the dropdown menu.
// If @menu was not triggered by a user interaction, like a mouse click,
// %NULL is returned.
func (x *OptionMenu) GetEvent() *gdk.Event {
	core.LazyRegister(&xOptionMenuGetEvent, "WEBKIT", "webkit_option_menu_get_event", false)
	var cls *gdk.Event

	cret := xOptionMenuGetEvent(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &gdk.Event{}
	cls.Ptr = cret
	return cls
}

var xOptionMenuGetItem func(uintptr, uint) uintptr

// Returns the #WebKitOptionMenuItem at @index in @menu.
func (x *OptionMenu) GetItem(IndexVar uint) *OptionMenuItem {
	core.LazyRegister(&xOptionMenuGetItem, "WEBKIT", "webkit_option_menu_get_item", false)

	cret := xOptionMenuGetItem(x.GoPointer(), IndexVar)
	if cret == 0 {
		return nil
	}
	return (*OptionMenuItem)(unsafe.Pointer(cret))
}

var xOptionMenuGetNItems func(uintptr) uint

// Gets the length of the @menu.
func (x *OptionMenu) GetNItems() uint {
	core.LazyRegister(&xOptionMenuGetNItems, "WEBKIT", "webkit_option_menu_get_n_items", false)

	cret := xOptionMenuGetNItems(x.GoPointer())
	return cret
}

var xOptionMenuSelectItem func(uintptr, uint)

// Selects the #WebKitOptionMenuItem at @index in @menu.
//
// Selecting an item changes the
// text shown by the combo button, but it doesn't change the value of the element. You need to
// explicitly activate the item with webkit_option_menu_select_item() or close the menu with
// webkit_option_menu_close() in which case the currently selected item will be activated.
func (x *OptionMenu) SelectItem(IndexVar uint) {
	core.LazyRegister(&xOptionMenuSelectItem, "WEBKIT", "webkit_option_menu_select_item", false)

	xOptionMenuSelectItem(x.GoPointer(), IndexVar)
}

func (c *OptionMenu) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *OptionMenu) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// Emitted when closing a #WebKitOptionMenu is requested. This can happen
// when the user explicitly calls webkit_option_menu_close() or when the
// element is detached from the current page.
func (x *OptionMenu) ConnectClose(cb *func(OptionMenu)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.OptionMenu.Close", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(OptionMenu))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := OptionMenu{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "close", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	OptionMenuGLibType()
}
