// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type BackForwardListItemClass struct {
	_ structs.HostLayout

	ParentClass gobject.InitiallyUnownedClass
}

func (x *BackForwardListItemClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func BackForwardListItemClassNewFromInternalPtr(ptr uintptr) *BackForwardListItemClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*BackForwardListItemClass)(rawPtr)
}

// One item of the #WebKitBackForwardList.
//
// A history item is part of the #WebKitBackForwardList and consists
// out of a title and a URI.
type BackForwardListItem struct {
	gobject.InitiallyUnowned
}

var xBackForwardListItemGLibType func() types.GType

func BackForwardListItemGLibType() types.GType {
	core.LazyRegister(&xBackForwardListItemGLibType, "WEBKIT", "webkit_back_forward_list_item_get_type", false)
	return xBackForwardListItemGLibType()
}

func BackForwardListItemNewFromInternalPtr(ptr uintptr) *BackForwardListItem {
	cls := &BackForwardListItem{}
	cls.Ptr = ptr
	return cls
}

var xBackForwardListItemGetOriginalUri func(uintptr) string

// Obtain the original URI of the item.
//
// See also webkit_back_forward_list_item_get_uri().
func (x *BackForwardListItem) GetOriginalUri() string {
	core.LazyRegister(&xBackForwardListItemGetOriginalUri, "WEBKIT", "webkit_back_forward_list_item_get_original_uri", false)

	cret := xBackForwardListItemGetOriginalUri(x.GoPointer())
	return cret
}

var xBackForwardListItemGetTitle func(uintptr) string

// Obtain the title of the item.
func (x *BackForwardListItem) GetTitle() string {
	core.LazyRegister(&xBackForwardListItemGetTitle, "WEBKIT", "webkit_back_forward_list_item_get_title", false)

	cret := xBackForwardListItemGetTitle(x.GoPointer())
	return cret
}

var xBackForwardListItemGetUri func(uintptr) string

// Obtain the URI of the item.
//
// This URI may differ from the original URI if the page was,
// for example, redirected to a new location.
// See also webkit_back_forward_list_item_get_original_uri().
func (x *BackForwardListItem) GetUri() string {
	core.LazyRegister(&xBackForwardListItemGetUri, "WEBKIT", "webkit_back_forward_list_item_get_uri", false)

	cret := xBackForwardListItemGetUri(x.GoPointer())
	return cret
}

func (c *BackForwardListItem) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *BackForwardListItem) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	BackForwardListItemGLibType()
}
