// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type WebInspectorClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *WebInspectorClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func WebInspectorClassNewFromInternalPtr(ptr uintptr) *WebInspectorClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*WebInspectorClass)(rawPtr)
}

// Access to the WebKit inspector.
//
// The WebKit Inspector is a graphical tool to inspect and change the
// content of a #WebKitWebView. It also includes an interactive
// JavaScript debugger. Using this class one can get a #GtkWidget
// which can be embedded into an application to show the inspector.
//
// The inspector is available when the #WebKitSettings of the
// #WebKitWebView has set the #WebKitSettings:enable-developer-extras
// to true, otherwise no inspector is available.
//
// ```c
// // Enable the developer extras
// WebKitSettings *settings = webkit_web_view_get_settings (WEBKIT_WEB_VIEW(my_webview));
// g_object_set (G_OBJECT(settings), "enable-developer-extras", TRUE, NULL);
//
// // Load some data or reload to be able to inspect the page
// webkit_web_view_load_uri (WEBKIT_WEB_VIEW(my_webview), "http://www.gnome.org");
//
// // Show the inspector
// WebKitWebInspector *inspector = webkit_web_view_get_inspector (WEBKIT_WEB_VIEW(my_webview));
// webkit_web_inspector_show (WEBKIT_WEB_INSPECTOR(inspector));
// ```
type WebInspector struct {
	gobject.Object
}

var xWebInspectorGLibType func() types.GType

func WebInspectorGLibType() types.GType {
	core.LazyRegister(&xWebInspectorGLibType, "WEBKIT", "webkit_web_inspector_get_type", false)
	return xWebInspectorGLibType()
}

func WebInspectorNewFromInternalPtr(ptr uintptr) *WebInspector {
	cls := &WebInspector{}
	cls.Ptr = ptr
	return cls
}

var xWebInspectorAttach func(uintptr)

// Request @inspector to be attached.
//
// The signal #WebKitWebInspector::attach
// will be emitted. If the inspector is already attached it does nothing.
func (x *WebInspector) Attach() {
	core.LazyRegister(&xWebInspectorAttach, "WEBKIT", "webkit_web_inspector_attach", false)

	xWebInspectorAttach(x.GoPointer())
}

var xWebInspectorClose func(uintptr)

// Request @inspector to be closed.
func (x *WebInspector) Close() {
	core.LazyRegister(&xWebInspectorClose, "WEBKIT", "webkit_web_inspector_close", false)

	xWebInspectorClose(x.GoPointer())
}

var xWebInspectorDetach func(uintptr)

// Request @inspector to be detached.
//
// The signal #WebKitWebInspector::detach
// will be emitted. If the inspector is already detached it does nothing.
func (x *WebInspector) Detach() {
	core.LazyRegister(&xWebInspectorDetach, "WEBKIT", "webkit_web_inspector_detach", false)

	xWebInspectorDetach(x.GoPointer())
}

var xWebInspectorGetAttachedHeight func(uintptr) uint

// Get the height that the inspector view when attached.
//
// Get the height that the inspector view should have when
// it's attached. If the inspector view is not attached this
// returns 0.
func (x *WebInspector) GetAttachedHeight() uint {
	core.LazyRegister(&xWebInspectorGetAttachedHeight, "WEBKIT", "webkit_web_inspector_get_attached_height", false)

	cret := xWebInspectorGetAttachedHeight(x.GoPointer())
	return cret
}

var xWebInspectorGetCanAttach func(uintptr) bool

// Whether the @inspector can be attached to the same window that contains
// the inspected view.
func (x *WebInspector) GetCanAttach() bool {
	core.LazyRegister(&xWebInspectorGetCanAttach, "WEBKIT", "webkit_web_inspector_get_can_attach", false)

	cret := xWebInspectorGetCanAttach(x.GoPointer())
	return cret
}

var xWebInspectorGetInspectedUri func(uintptr) string

// Get the URI that is currently being inspected.
//
// This can be %NULL if
// nothing has been loaded yet in the inspected view, if the inspector
// has been closed or when inspected view was loaded from a HTML string
// instead of a URI.
func (x *WebInspector) GetInspectedUri() string {
	core.LazyRegister(&xWebInspectorGetInspectedUri, "WEBKIT", "webkit_web_inspector_get_inspected_uri", false)

	cret := xWebInspectorGetInspectedUri(x.GoPointer())
	return cret
}

var xWebInspectorGetWebView func(uintptr) uintptr

// Get the #WebKitWebViewBase used to display the inspector.
//
// This might be %NULL if the inspector hasn't been loaded yet,
// or it has been closed.
func (x *WebInspector) GetWebView() *WebViewBase {
	core.LazyRegister(&xWebInspectorGetWebView, "WEBKIT", "webkit_web_inspector_get_web_view", false)
	var cls *WebViewBase

	cret := xWebInspectorGetWebView(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &WebViewBase{}
	cls.Ptr = cret
	return cls
}

var xWebInspectorIsAttached func(uintptr) bool

// Whether the @inspector view is currently attached to the same window that contains
// the inspected view.
func (x *WebInspector) IsAttached() bool {
	core.LazyRegister(&xWebInspectorIsAttached, "WEBKIT", "webkit_web_inspector_is_attached", false)

	cret := xWebInspectorIsAttached(x.GoPointer())
	return cret
}

var xWebInspectorShow func(uintptr)

// Request @inspector to be shown.
func (x *WebInspector) Show() {
	core.LazyRegister(&xWebInspectorShow, "WEBKIT", "webkit_web_inspector_show", false)

	xWebInspectorShow(x.GoPointer())
}

func (c *WebInspector) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *WebInspector) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// GetPropertyAttachedHeight gets the "attached-height" property.
// The height that the inspector view should have when it is attached.
func (x *WebInspector) GetPropertyAttachedHeight() uint {
	var v gobject.Value
	x.GetProperty("attached-height", &v)
	return v.GetUint()
}

// GetPropertyCanAttach gets the "can-attach" property.
// Whether the @inspector can be attached to the same window that contains
// the inspected view.
func (x *WebInspector) GetPropertyCanAttach() bool {
	var v gobject.Value
	x.GetProperty("can-attach", &v)
	return v.GetBoolean()
}

// GetPropertyInspectedUri gets the "inspected-uri" property.
// The URI that is currently being inspected.
func (x *WebInspector) GetPropertyInspectedUri() string {
	var v gobject.Value
	x.GetProperty("inspected-uri", &v)
	return v.GetString()
}

// Emitted when the inspector is requested to be attached to the window
// where the inspected web view is.
// If this signal is not handled the inspector view will be automatically
// attached to the inspected view, so you only need to handle this signal
// if you want to attach the inspector view yourself (for example, to add
// the inspector view to a browser tab).
//
// To prevent the inspector view from being attached you can connect to this
// signal and simply return %TRUE.
func (x *WebInspector) ConnectAttach(cb *func(WebInspector) bool) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.WebInspector.Attach", func(clsPtr uintptr, signalData uintptr) bool {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			var zero bool
			return zero
		}
		cb, ok := handler.(*func(WebInspector) bool)
		if !ok || cb == nil || *cb == nil {
			var zero bool
			return zero
		}
		fa := WebInspector{}
		fa.Ptr = clsPtr
		cbFn := *cb

		return cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "attach", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted when the inspector should be shown.
//
// If the inspector is not attached the inspector window should be shown
// on top of any other windows.
// If the inspector is attached the inspector view should be made visible.
// For example, if the inspector view is attached using a tab in a browser
// window, the browser window should be raised and the tab containing the
// inspector view should be the active one.
// In both cases, if this signal is not handled, the default implementation
// calls gtk_window_present() on the current toplevel #GtkWindow of the
// inspector view.
func (x *WebInspector) ConnectBringToFront(cb *func(WebInspector) bool) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.WebInspector.BringToFront", func(clsPtr uintptr, signalData uintptr) bool {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			var zero bool
			return zero
		}
		cb, ok := handler.(*func(WebInspector) bool)
		if !ok || cb == nil || *cb == nil {
			var zero bool
			return zero
		}
		fa := WebInspector{}
		fa.Ptr = clsPtr
		cbFn := *cb

		return cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "bring-to-front", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted when the inspector page is closed. If you are using your own
// inspector window, you should connect to this signal and destroy your
// window.
func (x *WebInspector) ConnectClosed(cb *func(WebInspector)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.WebInspector.Closed", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(WebInspector))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := WebInspector{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "closed", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted when the inspector is requested to be detached from the window
// it is currently attached to. The inspector is detached when the inspector page
// is about to be closed, and this signal is emitted right before
// #WebKitWebInspector::closed, or when the user clicks on the detach button
// in the inspector view to show the inspector in a separate window. In this case
// the signal #WebKitWebInspector::open-window is emitted after this one.
//
// To prevent the inspector view from being detached you can connect to this
// signal and simply return %TRUE.
func (x *WebInspector) ConnectDetach(cb *func(WebInspector) bool) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.WebInspector.Detach", func(clsPtr uintptr, signalData uintptr) bool {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			var zero bool
			return zero
		}
		cb, ok := handler.(*func(WebInspector) bool)
		if !ok || cb == nil || *cb == nil {
			var zero bool
			return zero
		}
		fa := WebInspector{}
		fa.Ptr = clsPtr
		cbFn := *cb

		return cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "detach", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted when the inspector is requested to open in a separate window.
// If this signal is not handled, a #GtkWindow with the inspector will be
// created and shown, so you only need to handle this signal if you want
// to use your own window.
// This signal is emitted after #WebKitWebInspector::detach to show
// the inspector in a separate window after being detached.
//
// To prevent the inspector from being shown you can connect to this
// signal and simply return %TRUE
func (x *WebInspector) ConnectOpenWindow(cb *func(WebInspector) bool) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.WebInspector.OpenWindow", func(clsPtr uintptr, signalData uintptr) bool {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			var zero bool
			return zero
		}
		cb, ok := handler.(*func(WebInspector) bool)
		if !ok || cb == nil || *cb == nil {
			var zero bool
			return zero
		}
		fa := WebInspector{}
		fa.Ptr = clsPtr
		cbFn := *cb

		return cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "open-window", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	WebInspectorGLibType()
}
