// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// Data stored locally by a web site.
//
// WebKitWebsiteData represents data stored in the client by a particular website.
// A website is normally a set of URLs grouped by domain name. You can get the website name,
// which is usually the domain, with webkit_website_data_get_name().
// Documents loaded from the file system, like file:// URIs, are all grouped in the same WebKitWebsiteData
// with the name "Local files".
//
// A website can store different types of data in the client side. #WebKitWebsiteDataTypes is an enum containing
// all the possible data types; use webkit_website_data_get_types() to get the bitmask of data types.
// It's also possible to know the size of the data stored for some of the #WebKitWebsiteDataTypes by using
// webkit_website_data_get_size().
//
// A list of WebKitWebsiteData can be retrieved with webkit_website_data_manager_fetch(). See #WebKitWebsiteDataManager
// for more information.
type WebsiteData struct {
	_ structs.HostLayout
}

var xWebsiteDataGLibType func() types.GType

func WebsiteDataGLibType() types.GType {
	core.LazyRegister(&xWebsiteDataGLibType, "WEBKIT", "webkit_website_data_get_type", false)
	return xWebsiteDataGLibType()
}

func (x *WebsiteData) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func WebsiteDataNewFromInternalPtr(ptr uintptr) *WebsiteData {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*WebsiteData)(rawPtr)
}

var xWebsiteDataGetName func(uintptr) string

// Gets the name of #WebKitWebsiteData.
//
// This is the website name, normally represented by
// a domain or host name. All local documents are grouped in the same #WebKitWebsiteData using
// the name "Local files".
func (x *WebsiteData) GetName() string {
	core.LazyRegister(&xWebsiteDataGetName, "WEBKIT", "webkit_website_data_get_name", false)

	cret := xWebsiteDataGetName(x.GoPointer())
	return cret
}

var xWebsiteDataGetSize func(uintptr, WebsiteDataTypes) uint64

// Gets the size of the data of types @types in a #WebKitWebsiteData.
//
// Note that currently the data size is only known for %WEBKIT_WEBSITE_DATA_DISK_CACHE data type
// so for all other types 0 will be returned.
func (x *WebsiteData) GetSize(TypesVar WebsiteDataTypes) uint64 {
	core.LazyRegister(&xWebsiteDataGetSize, "WEBKIT", "webkit_website_data_get_size", false)

	cret := xWebsiteDataGetSize(x.GoPointer(), TypesVar)
	return cret
}

var xWebsiteDataGetTypes func(uintptr) WebsiteDataTypes

// Gets the types of data stored in the client for a #WebKitWebsiteData.
//
// These are the
// types actually present, not the types queried with webkit_website_data_manager_fetch().
func (x *WebsiteData) GetTypes() WebsiteDataTypes {
	core.LazyRegister(&xWebsiteDataGetTypes, "WEBKIT", "webkit_website_data_get_types", false)

	cret := xWebsiteDataGetTypes(x.GoPointer())
	return cret
}

var xWebsiteDataRef func(uintptr) uintptr

// Atomically increments the reference count of @website_data by one.
//
// This function is MT-safe and may be called from any thread.
func (x *WebsiteData) Ref() *WebsiteData {
	core.LazyRegister(&xWebsiteDataRef, "WEBKIT", "webkit_website_data_ref", false)

	cret := xWebsiteDataRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*WebsiteData)(unsafe.Pointer(cret))
}

var xWebsiteDataUnref func(uintptr)

// Atomically decrements the reference count of @website_data by one.
//
// If the reference count drops to 0, all memory allocated by
// #WebKitWebsiteData is released. This function is MT-safe and may be
// called from any thread.
func (x *WebsiteData) Unref() {
	core.LazyRegister(&xWebsiteDataUnref, "WEBKIT", "webkit_website_data_unref", false)

	xWebsiteDataUnref(x.GoPointer())
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
}
