// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type PermissionRequestInterface struct {
	_ structs.HostLayout

	ParentInterface uintptr

	xAllow uintptr

	xDeny uintptr
}

func (x *PermissionRequestInterface) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func PermissionRequestInterfaceNewFromInternalPtr(ptr uintptr) *PermissionRequestInterface {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*PermissionRequestInterface)(rawPtr)
}

// OverrideAllow sets the "allow" callback function.
func (x *PermissionRequestInterface) OverrideAllow(cb func(PermissionRequest)) {
	if cb == nil {
		x.xAllow = 0
	} else {
		x.xAllow = purego.NewCallback(func(RequestVarp uintptr) {
			cb(&PermissionRequestBase{Ptr: RequestVarp})
		})
	}
}

// GetAllow gets the "allow" callback function.
func (x *PermissionRequestInterface) GetAllow() func(PermissionRequest) {
	if x.xAllow == 0 {
		return nil
	}
	var rawCallback func(RequestVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xAllow)
	return func(RequestVar PermissionRequest) {
		rawCallback(RequestVar.GoPointer())
	}
}

// OverrideDeny sets the "deny" callback function.
func (x *PermissionRequestInterface) OverrideDeny(cb func(PermissionRequest)) {
	if cb == nil {
		x.xDeny = 0
	} else {
		x.xDeny = purego.NewCallback(func(RequestVarp uintptr) {
			cb(&PermissionRequestBase{Ptr: RequestVarp})
		})
	}
}

// GetDeny gets the "deny" callback function.
func (x *PermissionRequestInterface) GetDeny() func(PermissionRequest) {
	if x.xDeny == 0 {
		return nil
	}
	var rawCallback func(RequestVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xDeny)
	return func(RequestVar PermissionRequest) {
		rawCallback(RequestVar.GoPointer())
	}
}

// A permission request.
//
// There are situations where an embedder would need to ask the user
// for permission to do certain types of operations, such as switching
// to fullscreen mode or reporting the user's location through the
// standard Geolocation API. In those cases, WebKit will emit a
// #WebKitWebView::permission-request signal with a
// #WebKitPermissionRequest object attached to it.
type PermissionRequest interface {
	GoPointer() uintptr
	SetGoPointer(uintptr)
	Allow()
	Deny()
}

var xPermissionRequestGLibType func() types.GType

func PermissionRequestGLibType() types.GType {
	core.LazyRegister(&xPermissionRequestGLibType, "WEBKIT", "webkit_permission_request_get_type", false)
	return xPermissionRequestGLibType()
}

type PermissionRequestBase struct {
	Ptr uintptr
}

func (x *PermissionRequestBase) GoPointer() uintptr {
	if x == nil {
		return 0
	}
	return x.Ptr
}

func (x *PermissionRequestBase) SetGoPointer(ptr uintptr) {
	x.Ptr = ptr
}

// Allow the action which triggered this request.
func (x *PermissionRequestBase) Allow() {
	XWebkitPermissionRequestAllow(x.GoPointer())
}

// Deny the action which triggered this request.
func (x *PermissionRequestBase) Deny() {
	XWebkitPermissionRequestDeny(x.GoPointer())
}

var XWebkitPermissionRequestAllow func(uintptr) = func(instance uintptr) {
	core.LazyRegister(&xXWebkitPermissionRequestAllow, "WEBKIT", "webkit_permission_request_allow", false)
	xXWebkitPermissionRequestAllow(instance)
}

var (
	xXWebkitPermissionRequestAllow func(uintptr)
	XWebkitPermissionRequestDeny   func(uintptr) = func(instance uintptr) {
		core.LazyRegister(&xXWebkitPermissionRequestDeny, "WEBKIT", "webkit_permission_request_deny", false)
		xXWebkitPermissionRequestDeny(instance)
	}
)
var xXWebkitPermissionRequestDeny func(uintptr)

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	PermissionRequestGLibType()
}
