// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type EditorStateClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *EditorStateClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func EditorStateClassNewFromInternalPtr(ptr uintptr) *EditorStateClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*EditorStateClass)(rawPtr)
}

// Enum values with flags representing typing attributes.
type EditorTypingAttributes int

var xEditorTypingAttributesGLibType func() types.GType

func EditorTypingAttributesGLibType() types.GType {
	core.LazyRegister(&xEditorTypingAttributesGLibType, "WEBKIT", "webkit_editor_typing_attributes_get_type", false)
	return xEditorTypingAttributesGLibType()
}

const (

	// No typing attributes.
	EditorTypingAttributeNoneValue EditorTypingAttributes = 2
	// Bold typing attribute.
	EditorTypingAttributeBoldValue EditorTypingAttributes = 4
	// Italic typing attribute.
	EditorTypingAttributeItalicValue EditorTypingAttributes = 8
	// Underline typing attribute.
	EditorTypingAttributeUnderlineValue EditorTypingAttributes = 16
	// Strikethrough typing attribute.
	EditorTypingAttributeStrikethroughValue EditorTypingAttributes = 32
)

// Web editor state.
//
// WebKitEditorState represents the state of a #WebKitWebView editor.
// Use webkit_web_view_get_editor_state() to get the WebKitEditorState
// of a #WebKitWebView.
type EditorState struct {
	gobject.Object
}

var xEditorStateGLibType func() types.GType

func EditorStateGLibType() types.GType {
	core.LazyRegister(&xEditorStateGLibType, "WEBKIT", "webkit_editor_state_get_type", false)
	return xEditorStateGLibType()
}

func EditorStateNewFromInternalPtr(ptr uintptr) *EditorState {
	cls := &EditorState{}
	cls.Ptr = ptr
	return cls
}

var xEditorStateGetTypingAttributes func(uintptr) uint

// Gets the typing attributes at the current cursor position.
//
// If there is a selection, this returns the typing attributes
// of the selected text. Note that in case of a selection,
// typing attributes are considered active only when they are
// present throughout the selection.
func (x *EditorState) GetTypingAttributes() uint {
	core.LazyRegister(&xEditorStateGetTypingAttributes, "WEBKIT", "webkit_editor_state_get_typing_attributes", false)

	cret := xEditorStateGetTypingAttributes(x.GoPointer())
	return cret
}

var xEditorStateIsCopyAvailable func(uintptr) bool

// Gets whether a copy command can be issued.
func (x *EditorState) IsCopyAvailable() bool {
	core.LazyRegister(&xEditorStateIsCopyAvailable, "WEBKIT", "webkit_editor_state_is_copy_available", false)

	cret := xEditorStateIsCopyAvailable(x.GoPointer())
	return cret
}

var xEditorStateIsCutAvailable func(uintptr) bool

// Gets whether a cut command can be issued.
func (x *EditorState) IsCutAvailable() bool {
	core.LazyRegister(&xEditorStateIsCutAvailable, "WEBKIT", "webkit_editor_state_is_cut_available", false)

	cret := xEditorStateIsCutAvailable(x.GoPointer())
	return cret
}

var xEditorStateIsPasteAvailable func(uintptr) bool

// Gets whether a paste command can be issued.
func (x *EditorState) IsPasteAvailable() bool {
	core.LazyRegister(&xEditorStateIsPasteAvailable, "WEBKIT", "webkit_editor_state_is_paste_available", false)

	cret := xEditorStateIsPasteAvailable(x.GoPointer())
	return cret
}

var xEditorStateIsRedoAvailable func(uintptr) bool

// Gets whether a redo command can be issued.
func (x *EditorState) IsRedoAvailable() bool {
	core.LazyRegister(&xEditorStateIsRedoAvailable, "WEBKIT", "webkit_editor_state_is_redo_available", false)

	cret := xEditorStateIsRedoAvailable(x.GoPointer())
	return cret
}

var xEditorStateIsUndoAvailable func(uintptr) bool

// Gets whether an undo command can be issued.
func (x *EditorState) IsUndoAvailable() bool {
	core.LazyRegister(&xEditorStateIsUndoAvailable, "WEBKIT", "webkit_editor_state_is_undo_available", false)

	cret := xEditorStateIsUndoAvailable(x.GoPointer())
	return cret
}

func (c *EditorState) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *EditorState) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// GetPropertyTypingAttributes gets the "typing-attributes" property.
// Bitmask of #WebKitEditorTypingAttributes flags.
// See webkit_editor_state_get_typing_attributes() for more information.
func (x *EditorState) GetPropertyTypingAttributes() uint {
	var v gobject.Value
	x.GetProperty("typing-attributes", &v)
	return v.GetUint()
}

// Emitted when the #WebKitEdtorState is changed.
func (x *EditorState) ConnectChanged(cb *func(EditorState)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.EditorState.Changed", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(EditorState))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := EditorState{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "changed", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	EditorStateGLibType()
}
