// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type NotificationPermissionRequestClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *NotificationPermissionRequestClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func NotificationPermissionRequestClassNewFromInternalPtr(ptr uintptr) *NotificationPermissionRequestClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*NotificationPermissionRequestClass)(rawPtr)
}

// A permission request for displaying web notifications.
//
// WebKitNotificationPermissionRequest represents a request for
// permission to decide whether WebKit should provide the user with
// notifications through the Web Notification API.
//
// When a WebKitNotificationPermissionRequest is not handled by the user,
// it is denied by default.
type NotificationPermissionRequest struct {
	gobject.Object
}

var xNotificationPermissionRequestGLibType func() types.GType

func NotificationPermissionRequestGLibType() types.GType {
	core.LazyRegister(&xNotificationPermissionRequestGLibType, "WEBKIT", "webkit_notification_permission_request_get_type", false)
	return xNotificationPermissionRequestGLibType()
}

func NotificationPermissionRequestNewFromInternalPtr(ptr uintptr) *NotificationPermissionRequest {
	cls := &NotificationPermissionRequest{}
	cls.Ptr = ptr
	return cls
}

func (c *NotificationPermissionRequest) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *NotificationPermissionRequest) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// Allow the action which triggered this request.
func (x *NotificationPermissionRequest) Allow() {
	XWebkitPermissionRequestAllow(x.GoPointer())
}

// Deny the action which triggered this request.
func (x *NotificationPermissionRequest) Deny() {
	XWebkitPermissionRequestDeny(x.GoPointer())
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	NotificationPermissionRequestGLibType()
}
