// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// Represents a way to specify a group of URLs for use in WebExtensions.
//
// All match patterns are specified as strings. Apart from the special `&lt;all_urls&gt;` pattern, match patterns
// consist of three parts: scheme, host, and path.
//
// Generally, match patterns are returned from a #WebKitWebExtension.
type WebExtensionMatchPattern struct {
	_ structs.HostLayout
}

var xWebExtensionMatchPatternGLibType func() types.GType

func WebExtensionMatchPatternGLibType() types.GType {
	core.LazyRegister(&xWebExtensionMatchPatternGLibType, "WEBKIT", "webkit_web_extension_match_pattern_get_type", false)
	return xWebExtensionMatchPatternGLibType()
}

func (x *WebExtensionMatchPattern) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func WebExtensionMatchPatternNewFromInternalPtr(ptr uintptr) *WebExtensionMatchPattern {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*WebExtensionMatchPattern)(rawPtr)
}

var xNewWebExtensionMatchPatternAllHostsAndSchemes func() uintptr

// Returns a new #WebKitWebExtensionMatchPattern that has `*` for scheme, host, and path.
func NewWebExtensionMatchPatternAllHostsAndSchemes() *WebExtensionMatchPattern {
	core.LazyRegister(&xNewWebExtensionMatchPatternAllHostsAndSchemes, "WEBKIT", "webkit_web_extension_match_pattern_new_all_hosts_and_schemes", false)

	cret := xNewWebExtensionMatchPatternAllHostsAndSchemes()
	if cret == 0 {
		return nil
	}
	return (*WebExtensionMatchPattern)(unsafe.Pointer(cret))
}

var xNewWebExtensionMatchPatternAllUrls func() uintptr

// Returns a new #WebKitWebExtensionMatchPattern for `&lt;all_urls&gt;`.
func NewWebExtensionMatchPatternAllUrls() *WebExtensionMatchPattern {
	core.LazyRegister(&xNewWebExtensionMatchPatternAllUrls, "WEBKIT", "webkit_web_extension_match_pattern_new_all_urls", false)

	cret := xNewWebExtensionMatchPatternAllUrls()
	if cret == 0 {
		return nil
	}
	return (*WebExtensionMatchPattern)(unsafe.Pointer(cret))
}

var xNewWebExtensionMatchPatternWithScheme func(string, string, string, **glib.Error) uintptr

// Returns a new #WebKitWebExtensionMatchPattern for the specified @scheme, @host, and @path strings.
func NewWebExtensionMatchPatternWithScheme(SchemeVar string, HostVar string, PathVar string) (*WebExtensionMatchPattern, error) {
	core.LazyRegister(&xNewWebExtensionMatchPatternWithScheme, "WEBKIT", "webkit_web_extension_match_pattern_new_with_scheme", false)
	var cerr *glib.Error

	cret := xNewWebExtensionMatchPatternWithScheme(SchemeVar, HostVar, PathVar, &cerr)
	if cerr != nil {
		return nil, cerr
	}
	if cret == 0 {
		return nil, nil
	}
	return (*WebExtensionMatchPattern)(unsafe.Pointer(cret)), nil
}

var xNewWebExtensionMatchPatternWithString func(string, **glib.Error) uintptr

// Returns a new #WebKitWebExtensionMatchPattern for the specified @string.
func NewWebExtensionMatchPatternWithString(StringVar string) (*WebExtensionMatchPattern, error) {
	core.LazyRegister(&xNewWebExtensionMatchPatternWithString, "WEBKIT", "webkit_web_extension_match_pattern_new_with_string", false)
	var cerr *glib.Error

	cret := xNewWebExtensionMatchPatternWithString(StringVar, &cerr)
	if cerr != nil {
		return nil, cerr
	}
	if cret == 0 {
		return nil, nil
	}
	return (*WebExtensionMatchPattern)(unsafe.Pointer(cret)), nil
}

var xWebExtensionMatchPatternGetHost func(uintptr) string

// Gets the host part of the pattern string, unless `webkit_web_extension_match_pattern_get_matches_all_urls` is %TRUE.
func (x *WebExtensionMatchPattern) GetHost() string {
	core.LazyRegister(&xWebExtensionMatchPatternGetHost, "WEBKIT", "webkit_web_extension_match_pattern_get_host", false)

	cret := xWebExtensionMatchPatternGetHost(x.GoPointer())
	return cret
}

var xWebExtensionMatchPatternGetMatchesAllHosts func(uintptr) bool

// Gets whether the match pattern matches all host. This happens when
// the pattern is `&lt;all_urls&gt;`, or if `*` is set as the host string.
func (x *WebExtensionMatchPattern) GetMatchesAllHosts() bool {
	core.LazyRegister(&xWebExtensionMatchPatternGetMatchesAllHosts, "WEBKIT", "webkit_web_extension_match_pattern_get_matches_all_hosts", false)

	cret := xWebExtensionMatchPatternGetMatchesAllHosts(x.GoPointer())
	return cret
}

var xWebExtensionMatchPatternGetMatchesAllUrls func(uintptr) bool

// Gets whether the match pattern matches all URLs, in other words, whether
// the pattern is `&lt;all_urls&gt;`.
func (x *WebExtensionMatchPattern) GetMatchesAllUrls() bool {
	core.LazyRegister(&xWebExtensionMatchPatternGetMatchesAllUrls, "WEBKIT", "webkit_web_extension_match_pattern_get_matches_all_urls", false)

	cret := xWebExtensionMatchPatternGetMatchesAllUrls(x.GoPointer())
	return cret
}

var xWebExtensionMatchPatternGetPath func(uintptr) string

// Gets the path part of the pattern string, unless [method@WebExtensionMatchPattern.get_matches_all_urls] is %TRUE.
func (x *WebExtensionMatchPattern) GetPath() string {
	core.LazyRegister(&xWebExtensionMatchPatternGetPath, "WEBKIT", "webkit_web_extension_match_pattern_get_path", false)

	cret := xWebExtensionMatchPatternGetPath(x.GoPointer())
	return cret
}

var xWebExtensionMatchPatternGetScheme func(uintptr) string

// Gets the scheme part of the pattern string, unless `webkit_web_extension_match_pattern_get_matches_all_urls` is %TRUE.
func (x *WebExtensionMatchPattern) GetScheme() string {
	core.LazyRegister(&xWebExtensionMatchPatternGetScheme, "WEBKIT", "webkit_web_extension_match_pattern_get_scheme", false)

	cret := xWebExtensionMatchPatternGetScheme(x.GoPointer())
	return cret
}

var xWebExtensionMatchPatternGetString func(uintptr) string

// Gets the original pattern string.
func (x *WebExtensionMatchPattern) GetString() string {
	core.LazyRegister(&xWebExtensionMatchPatternGetString, "WEBKIT", "webkit_web_extension_match_pattern_get_string", false)

	cret := xWebExtensionMatchPatternGetString(x.GoPointer())
	return cret
}

var xWebExtensionMatchPatternMatchesPattern func(uintptr, *WebExtensionMatchPattern, WebExtensionMatchPatternOptions) bool

// Matches the @matchPattern against the specified @pattern with options.
func (x *WebExtensionMatchPattern) MatchesPattern(PatternVar *WebExtensionMatchPattern, OptionsVar WebExtensionMatchPatternOptions) bool {
	core.LazyRegister(&xWebExtensionMatchPatternMatchesPattern, "WEBKIT", "webkit_web_extension_match_pattern_matches_pattern", false)

	cret := xWebExtensionMatchPatternMatchesPattern(x.GoPointer(), PatternVar, OptionsVar)
	return cret
}

var xWebExtensionMatchPatternMatchesUrl func(uintptr, string, WebExtensionMatchPatternOptions) bool

// Matches the @matchPattern against the specified URL with options.
func (x *WebExtensionMatchPattern) MatchesUrl(UrlVar string, OptionsVar WebExtensionMatchPatternOptions) bool {
	core.LazyRegister(&xWebExtensionMatchPatternMatchesUrl, "WEBKIT", "webkit_web_extension_match_pattern_matches_url", false)

	cret := xWebExtensionMatchPatternMatchesUrl(x.GoPointer(), UrlVar, OptionsVar)
	return cret
}

var xWebExtensionMatchPatternRef func(uintptr) uintptr

// Atomically acquires a reference on the given @matchPattern.
//
// This function is MT-safe and may be called from any thread.
func (x *WebExtensionMatchPattern) Ref() *WebExtensionMatchPattern {
	core.LazyRegister(&xWebExtensionMatchPatternRef, "WEBKIT", "webkit_web_extension_match_pattern_ref", false)

	cret := xWebExtensionMatchPatternRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*WebExtensionMatchPattern)(unsafe.Pointer(cret))
}

var xWebExtensionMatchPatternUnref func(uintptr)

// Atomically releases a reference on the given @matchPattern.
//
// If the reference was the last, the resources associated to the
// @matchPattern are freed. This function is MT-safe and may be called from
// any thread.
func (x *WebExtensionMatchPattern) Unref() {
	core.LazyRegister(&xWebExtensionMatchPatternUnref, "WEBKIT", "webkit_web_extension_match_pattern_unref", false)

	xWebExtensionMatchPatternUnref(x.GoPointer())
}

// Enum values representing matching options.
type WebExtensionMatchPatternOptions int

var xWebExtensionMatchPatternOptionsGLibType func() types.GType

func WebExtensionMatchPatternOptionsGLibType() types.GType {
	core.LazyRegister(&xWebExtensionMatchPatternOptionsGLibType, "WEBKIT", "webkit_web_extension_match_pattern_options_get_type", false)
	return xWebExtensionMatchPatternOptionsGLibType()
}

const (

	// No special matching options.
	WebExtensionMatchPatternOptionsNoneValue WebExtensionMatchPatternOptions = 1
	// The scheme components should be ignored while matching.
	WebExtensionMatchPatternOptionsIgnoreSchemesValue WebExtensionMatchPatternOptions = 2
	// The host components should be ignored while matching.
	WebExtensionMatchPatternOptionsIgnorePathsValue WebExtensionMatchPatternOptions = 4
	// Two patterns should be checked in either direction while matching (A matches B, or B matches A). Invalid for matching URLs.
	WebExtensionMatchPatternOptionsMatchBidirectionallyValue WebExtensionMatchPatternOptions = 8
)

var xWebExtensionMatchPatternRegisterCustomURLScheme func(string)

// Registers a custom URL scheme that can be used in match patterns.
//
// This method should be used to register any custom URL schemes used by the app for the extension base URLs,
// other than `webkit-extension`, or if extensions should have access to other supported URL schemes when using `&lt;all_urls&gt;`.
func WebExtensionMatchPatternRegisterCustomURLScheme(UrlSchemeVar string) {
	core.LazyRegister(&xWebExtensionMatchPatternRegisterCustomURLScheme, "WEBKIT", "webkit_web_extension_match_pattern_register_custom_URL_scheme", false)

	xWebExtensionMatchPatternRegisterCustomURLScheme(UrlSchemeVar)
}

var xWebExtensionMatchPatternRegisterCustomUrlScheme func(string)

// Registers a custom URL scheme that can be used in match patterns.
//
// This method should be used to register any custom URL schemes used by the app for the extension base URLs,
// other than `webkit-extension`, or if extensions should have access to other supported URL schemes when using `&lt;all_urls&gt;`.
func WebExtensionMatchPatternRegisterCustomUrlScheme(UrlSchemeVar string) {
	core.LazyRegister(&xWebExtensionMatchPatternRegisterCustomUrlScheme, "WEBKIT", "webkit_web_extension_match_pattern_register_custom_url_scheme", false)

	xWebExtensionMatchPatternRegisterCustomUrlScheme(UrlSchemeVar)
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
}
