// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gdk"
	"github.com/bnema/puregotk/v4/gio"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type FaviconDatabaseClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *FaviconDatabaseClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func FaviconDatabaseClassNewFromInternalPtr(ptr uintptr) *FaviconDatabaseClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*FaviconDatabaseClass)(rawPtr)
}

// Enum values used to denote the various errors related to the #WebKitFaviconDatabase.
type FaviconDatabaseError int

var xFaviconDatabaseErrorGLibType func() types.GType

func FaviconDatabaseErrorGLibType() types.GType {
	core.LazyRegister(&xFaviconDatabaseErrorGLibType, "WEBKIT", "webkit_favicon_database_error_get_type", false)
	return xFaviconDatabaseErrorGLibType()
}

const (

	// The #WebKitFaviconDatabase is closed
	FaviconDatabaseErrorNotInitializedValue FaviconDatabaseError = 0
	// There is not an icon available for the requested URL
	FaviconDatabaseErrorFaviconNotFoundValue FaviconDatabaseError = 1
	// There might be an icon for the requested URL, but its data is unknown at the moment
	FaviconDatabaseErrorFaviconUnknownValue FaviconDatabaseError = 2
)

var xFaviconDatabaseErrorQuark func() glib.Quark

// Gets the quark for the domain of favicon database errors.
func FaviconDatabaseErrorQuark() glib.Quark {
	core.LazyRegister(&xFaviconDatabaseErrorQuark, "WEBKIT", "webkit_favicon_database_error_quark", false)

	cret := xFaviconDatabaseErrorQuark()
	return cret
}

// Provides access to the icons associated with web sites.
//
// WebKit will automatically look for available icons in &lt;link&gt;
// elements on opened pages as well as an existing favicon.ico and
// load the images found into a memory cache if possible. That cache
// is frozen to an on-disk database for persistence.
//
// If #WebKitSettings:enable-private-browsing is %TRUE, new icons
// won't be added to the on-disk database and no existing icons will
// be deleted from it. Nevertheless, WebKit will still store them in
// the in-memory cache during the current execution.
type FaviconDatabase struct {
	gobject.Object
}

var xFaviconDatabaseGLibType func() types.GType

func FaviconDatabaseGLibType() types.GType {
	core.LazyRegister(&xFaviconDatabaseGLibType, "WEBKIT", "webkit_favicon_database_get_type", false)
	return xFaviconDatabaseGLibType()
}

func FaviconDatabaseNewFromInternalPtr(ptr uintptr) *FaviconDatabase {
	cls := &FaviconDatabase{}
	cls.Ptr = ptr
	return cls
}

var xFaviconDatabaseClear func(uintptr)

// Clears all icons from the database.
func (x *FaviconDatabase) Clear() {
	core.LazyRegister(&xFaviconDatabaseClear, "WEBKIT", "webkit_favicon_database_clear", false)

	xFaviconDatabaseClear(x.GoPointer())
}

var xFaviconDatabaseGetFavicon func(uintptr, string, uintptr, uintptr, uintptr)

// Asynchronously obtains a favicon image.
//
// Asynchronously obtains an image of the favicon for the
// given page URI. It returns the cached icon if it's in the database
// asynchronously waiting for the icon to be read from the database.
//
// This is an asynchronous method. When the operation is finished, callback will
// be invoked. You can then call webkit_favicon_database_get_favicon_finish()
// to get the result of the operation.
func (x *FaviconDatabase) GetFavicon(PageUriVar string, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
	core.LazyRegister(&xFaviconDatabaseGetFavicon, "WEBKIT", "webkit_favicon_database_get_favicon", false)

	xFaviconDatabaseGetFavicon(x.GoPointer(), PageUriVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
}

var xFaviconDatabaseGetFaviconFinish func(uintptr, uintptr, **glib.Error) uintptr

// Finishes an operation started with webkit_favicon_database_get_favicon().
func (x *FaviconDatabase) GetFaviconFinish(ResultVar gio.AsyncResult) (*gdk.Texture, error) {
	core.LazyRegister(&xFaviconDatabaseGetFaviconFinish, "WEBKIT", "webkit_favicon_database_get_favicon_finish", false)
	var cls *gdk.Texture
	var cerr *glib.Error

	cret := xFaviconDatabaseGetFaviconFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &gdk.Texture{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr
}

var xFaviconDatabaseGetFaviconUri func(uintptr, string) string

// Obtains the URI of the favicon for the given @page_uri.
func (x *FaviconDatabase) GetFaviconUri(PageUriVar string) string {
	core.LazyRegister(&xFaviconDatabaseGetFaviconUri, "WEBKIT", "webkit_favicon_database_get_favicon_uri", false)

	cret := xFaviconDatabaseGetFaviconUri(x.GoPointer(), PageUriVar)
	return cret
}

func (c *FaviconDatabase) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *FaviconDatabase) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// This signal is emitted when the favicon URI of @page_uri has
// been changed to @favicon_uri in the database. You can connect
// to this signal and call webkit_favicon_database_get_favicon()
// to get the favicon. If you are interested in the favicon of a
// #WebKitWebView it's easier to use the #WebKitWebView:favicon
// property. See webkit_web_view_get_favicon() for more details.
func (x *FaviconDatabase) ConnectFaviconChanged(cb *func(FaviconDatabase, string, string)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.FaviconDatabase.FaviconChanged", func(clsPtr uintptr, PageUriVarp string, FaviconUriVarp string, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(FaviconDatabase, string, string))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := FaviconDatabase{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa, PageUriVarp, FaviconUriVarp)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "favicon-changed", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	FaviconDatabaseGLibType()
}
