// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// A security boundary for websites.
//
// #WebKitSecurityOrigin is a representation of a security domain
// defined by websites. A security origin consists of a protocol, a
// hostname, and an optional port number.
//
// Resources with the same security origin can generally access each
// other for client-side scripting or database access. When comparing
// origins, beware that if both protocol and host are %NULL, the origins
// should not be treated as equal.
type SecurityOrigin struct {
	_ structs.HostLayout
}

var xSecurityOriginGLibType func() types.GType

func SecurityOriginGLibType() types.GType {
	core.LazyRegister(&xSecurityOriginGLibType, "WEBKIT", "webkit_security_origin_get_type", false)
	return xSecurityOriginGLibType()
}

func (x *SecurityOrigin) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func SecurityOriginNewFromInternalPtr(ptr uintptr) *SecurityOrigin {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*SecurityOrigin)(rawPtr)
}

var xNewSecurityOrigin func(string, string, uint16) uintptr

// Create a new security origin from the provided protocol, host and
// port.
func NewSecurityOrigin(ProtocolVar string, HostVar string, PortVar uint16) *SecurityOrigin {
	core.LazyRegister(&xNewSecurityOrigin, "WEBKIT", "webkit_security_origin_new", false)

	cret := xNewSecurityOrigin(ProtocolVar, HostVar, PortVar)
	if cret == 0 {
		return nil
	}
	return (*SecurityOrigin)(unsafe.Pointer(cret))
}

var xNewSecurityOriginForUri func(string) uintptr

// Create a new security origin from the provided.
//
// Create a new security origin from the provided URI. Components of
// @uri other than protocol, host, and port do not affect the created
// #WebKitSecurityOrigin.
func NewSecurityOriginForUri(UriVar string) *SecurityOrigin {
	core.LazyRegister(&xNewSecurityOriginForUri, "WEBKIT", "webkit_security_origin_new_for_uri", false)

	cret := xNewSecurityOriginForUri(UriVar)
	if cret == 0 {
		return nil
	}
	return (*SecurityOrigin)(unsafe.Pointer(cret))
}

var xSecurityOriginGetHost func(uintptr) string

// Gets the hostname of @origin.
//
// It is reasonable for this to be %NULL
// if its protocol does not require a host component.
func (x *SecurityOrigin) GetHost() string {
	core.LazyRegister(&xSecurityOriginGetHost, "WEBKIT", "webkit_security_origin_get_host", false)

	cret := xSecurityOriginGetHost(x.GoPointer())
	return cret
}

var xSecurityOriginGetPort func(uintptr) uint16

// Gets the port of @origin.
//
// This function will always return 0 if the
// port is the default port for the given protocol. For example,
// http://example.com has the same security origin as
// http://example.com:80, and this function will return 0 for a
// #WebKitSecurityOrigin constructed from either URI.
func (x *SecurityOrigin) GetPort() uint16 {
	core.LazyRegister(&xSecurityOriginGetPort, "WEBKIT", "webkit_security_origin_get_port", false)

	cret := xSecurityOriginGetPort(x.GoPointer())
	return cret
}

var xSecurityOriginGetProtocol func(uintptr) string

// Gets the protocol of @origin.
func (x *SecurityOrigin) GetProtocol() string {
	core.LazyRegister(&xSecurityOriginGetProtocol, "WEBKIT", "webkit_security_origin_get_protocol", false)

	cret := xSecurityOriginGetProtocol(x.GoPointer())
	return cret
}

var xSecurityOriginRef func(uintptr) uintptr

// Atomically increments the reference count of @origin by one.
//
// This function is MT-safe and may be called from any thread.
func (x *SecurityOrigin) Ref() *SecurityOrigin {
	core.LazyRegister(&xSecurityOriginRef, "WEBKIT", "webkit_security_origin_ref", false)

	cret := xSecurityOriginRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*SecurityOrigin)(unsafe.Pointer(cret))
}

var xSecurityOriginToString func(uintptr) string

// Gets a string representation of @origin.
//
// The string representation
// is a valid URI with only protocol, host, and port components, or
// %NULL.
func (x *SecurityOrigin) ToString() string {
	core.LazyRegister(&xSecurityOriginToString, "WEBKIT", "webkit_security_origin_to_string", false)

	cret := xSecurityOriginToString(x.GoPointer())
	return cret
}

var xSecurityOriginUnref func(uintptr)

// Atomically decrements the reference count of @origin by one.
//
// If the reference count drops to 0, all memory allocated by
// #WebKitSecurityOrigin is released. This function is MT-safe and may be
// called from any thread.
func (x *SecurityOrigin) Unref() {
	core.LazyRegister(&xSecurityOriginUnref, "WEBKIT", "webkit_security_origin_unref", false)

	xSecurityOriginUnref(x.GoPointer())
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
}
