// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import "github.com/bnema/puregotk/pkg/core"

var xUriForDisplay func(string) string

// Use this function to format a URI for display.
//
// The URIs used internally by
// WebKit may contain percent-encoded characters or Punycode, which are not
// generally suitable to display to users. This function provides protection
// against IDN homograph attacks, so in some cases the host part of the returned
// URI may be in Punycode if the safety check fails.
func UriForDisplay(UriVar string) string {
	core.LazyRegister(&xUriForDisplay, "WEBKIT", "webkit_uri_for_display", false)

	cret := xUriForDisplay(UriVar)
	return cret
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
}
