// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type AutomationSessionClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *AutomationSessionClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func AutomationSessionClassNewFromInternalPtr(ptr uintptr) *AutomationSessionClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*AutomationSessionClass)(rawPtr)
}

// Enum values used for determining the automation browsing context presentation.
type AutomationBrowsingContextPresentation int

var xAutomationBrowsingContextPresentationGLibType func() types.GType

func AutomationBrowsingContextPresentationGLibType() types.GType {
	core.LazyRegister(&xAutomationBrowsingContextPresentationGLibType, "WEBKIT", "webkit_automation_browsing_context_presentation_get_type", false)
	return xAutomationBrowsingContextPresentationGLibType()
}

const (

	// a window
	AutomationBrowsingContextPresentationWindowValue AutomationBrowsingContextPresentation = 0
	// a tab
	AutomationBrowsingContextPresentationTabValue AutomationBrowsingContextPresentation = 1
)

// Automation Session.
//
// WebKitAutomationSession represents an automation session of a WebKitWebContext.
// When a new session is requested, a WebKitAutomationSession is created and the signal
// WebKitWebContext::automation-started is emitted with the WebKitAutomationSession as
// argument. Then, the automation client can request the session to create a new
// #WebKitWebView to interact with it. When this happens the signal #WebKitAutomationSession::create-web-view
// is emitted.
type AutomationSession struct {
	gobject.Object
}

var xAutomationSessionGLibType func() types.GType

func AutomationSessionGLibType() types.GType {
	core.LazyRegister(&xAutomationSessionGLibType, "WEBKIT", "webkit_automation_session_get_type", false)
	return xAutomationSessionGLibType()
}

func AutomationSessionNewFromInternalPtr(ptr uintptr) *AutomationSession {
	cls := &AutomationSession{}
	cls.Ptr = ptr
	return cls
}

var xAutomationSessionGetApplicationInfo func(uintptr) uintptr

// Get the the previously set #WebKitAutomationSession.
//
// Get the #WebKitAutomationSession previously set with webkit_automation_session_set_application_info().
func (x *AutomationSession) GetApplicationInfo() *ApplicationInfo {
	core.LazyRegister(&xAutomationSessionGetApplicationInfo, "WEBKIT", "webkit_automation_session_get_application_info", false)

	cret := xAutomationSessionGetApplicationInfo(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*ApplicationInfo)(unsafe.Pointer(cret))
}

var xAutomationSessionGetId func(uintptr) string

// Get the unique identifier of a #WebKitAutomationSession
func (x *AutomationSession) GetId() string {
	core.LazyRegister(&xAutomationSessionGetId, "WEBKIT", "webkit_automation_session_get_id", false)

	cret := xAutomationSessionGetId(x.GoPointer())
	return cret
}

var xAutomationSessionSetApplicationInfo func(uintptr, *ApplicationInfo)

// Set the application information to @session.
//
// This information will be used by the driver service
// to match the requested capabilities with the actual application information. If this information
// is not provided to the session when a new automation session is requested, the creation might fail
// if the client requested a specific browser name or version. This will not have any effect when called
// after the automation session has been fully created, so this must be called in the callback of
// #WebKitWebContext::automation-started signal.
func (x *AutomationSession) SetApplicationInfo(InfoVar *ApplicationInfo) {
	core.LazyRegister(&xAutomationSessionSetApplicationInfo, "WEBKIT", "webkit_automation_session_set_application_info", false)

	xAutomationSessionSetApplicationInfo(x.GoPointer(), InfoVar)
}

func (c *AutomationSession) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *AutomationSession) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyId sets the "id" property.
// The session unique identifier.
func (x *AutomationSession) SetPropertyId(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(&value)
	x.SetProperty("id", &v)
}

// GetPropertyId gets the "id" property.
// The session unique identifier.
func (x *AutomationSession) GetPropertyId() string {
	var v gobject.Value
	x.GetProperty("id", &v)
	return v.GetString()
}

// This signal is emitted when the automation client requests a new
// browsing context to interact with it. The callback handler should
// return a #WebKitWebView created with #WebKitWebView:is-controlled-by-automation
// construct property enabled and #WebKitWebView:automation-presentation-type construct
// property set if needed.
//
// If the signal is emitted with "tab" detail, the returned #WebKitWebView should be
// a new web view added to a new tab of the current browsing context window.
// If the signal is emitted with "window" detail, the returned #WebKitWebView should be
// a new web view added to a new window.
// When creating a new web view and there's an active browsing context, the new window
// or tab shouldn't be focused.
func (x *AutomationSession) ConnectCreateWebView(cb *func(AutomationSession) WebView) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.AutomationSession.CreateWebView", func(clsPtr uintptr, signalData uintptr) uintptr {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			var zero uintptr
			return zero
		}
		cb, ok := handler.(*func(AutomationSession) WebView)
		if !ok || cb == nil || *cb == nil {
			var zero uintptr
			return zero
		}
		fa := AutomationSession{}
		fa.Ptr = clsPtr
		cbFn := *cb

		CreateWebViewCls := cbFn(fa)
		return CreateWebViewCls.Ptr
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "create-web-view", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// This signal is emitted when the given automation session is about to finish.
// It allows clients to perform any cleanup tasks before the session is destroyed.
func (x *AutomationSession) ConnectWillClose(cb *func(AutomationSession)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.AutomationSession.WillClose", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(AutomationSession))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := AutomationSession{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "will-close", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	AutomationSessionGLibType()
}
