// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type UserMediaPermissionRequestClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *UserMediaPermissionRequestClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func UserMediaPermissionRequestClassNewFromInternalPtr(ptr uintptr) *UserMediaPermissionRequestClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*UserMediaPermissionRequestClass)(rawPtr)
}

var xUserMediaPermissionIsForAudioDevice func(uintptr) bool

// Check whether the permission request is for an audio device.
func UserMediaPermissionIsForAudioDevice(RequestVar *UserMediaPermissionRequest) bool {
	core.LazyRegister(&xUserMediaPermissionIsForAudioDevice, "WEBKIT", "webkit_user_media_permission_is_for_audio_device", false)

	cret := xUserMediaPermissionIsForAudioDevice(RequestVar.GoPointer())
	return cret
}

var xUserMediaPermissionIsForDisplayDevice func(uintptr) bool

// Check whether the permission request is for a display device.
func UserMediaPermissionIsForDisplayDevice(RequestVar *UserMediaPermissionRequest) bool {
	core.LazyRegister(&xUserMediaPermissionIsForDisplayDevice, "WEBKIT", "webkit_user_media_permission_is_for_display_device", false)

	cret := xUserMediaPermissionIsForDisplayDevice(RequestVar.GoPointer())
	return cret
}

var xUserMediaPermissionIsForVideoDevice func(uintptr) bool

// Check whether the permission request is for a video device.
func UserMediaPermissionIsForVideoDevice(RequestVar *UserMediaPermissionRequest) bool {
	core.LazyRegister(&xUserMediaPermissionIsForVideoDevice, "WEBKIT", "webkit_user_media_permission_is_for_video_device", false)

	cret := xUserMediaPermissionIsForVideoDevice(RequestVar.GoPointer())
	return cret
}

// A permission request for accessing user's audio/video devices.
//
// WebKitUserMediaPermissionRequest represents a request for
// permission to decide whether WebKit should be allowed to access the user's
// audio and video source devices when requested through the getUserMedia API.
//
// When a WebKitUserMediaPermissionRequest is not handled by the user,
// it is denied by default.
type UserMediaPermissionRequest struct {
	gobject.Object
}

var xUserMediaPermissionRequestGLibType func() types.GType

func UserMediaPermissionRequestGLibType() types.GType {
	core.LazyRegister(&xUserMediaPermissionRequestGLibType, "WEBKIT", "webkit_user_media_permission_request_get_type", false)
	return xUserMediaPermissionRequestGLibType()
}

func UserMediaPermissionRequestNewFromInternalPtr(ptr uintptr) *UserMediaPermissionRequest {
	cls := &UserMediaPermissionRequest{}
	cls.Ptr = ptr
	return cls
}

func (c *UserMediaPermissionRequest) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *UserMediaPermissionRequest) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// GetPropertyIsForAudioDevice gets the "is-for-audio-device" property.
// Whether the media device to which the permission was requested has a microphone or not.
func (x *UserMediaPermissionRequest) GetPropertyIsForAudioDevice() bool {
	var v gobject.Value
	x.GetProperty("is-for-audio-device", &v)
	return v.GetBoolean()
}

// GetPropertyIsForVideoDevice gets the "is-for-video-device" property.
// Whether the media device to which the permission was requested has a video capture capability or not.
func (x *UserMediaPermissionRequest) GetPropertyIsForVideoDevice() bool {
	var v gobject.Value
	x.GetProperty("is-for-video-device", &v)
	return v.GetBoolean()
}

// Allow the action which triggered this request.
func (x *UserMediaPermissionRequest) Allow() {
	XWebkitPermissionRequestAllow(x.GoPointer())
}

// Deny the action which triggered this request.
func (x *UserMediaPermissionRequest) Deny() {
	XWebkitPermissionRequestDeny(x.GoPointer())
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	UserMediaPermissionRequestGLibType()
}
