// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gio"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// Describes a first party origin.
type ITPFirstParty struct {
	_ structs.HostLayout
}

var xITPFirstPartyGLibType func() types.GType

func ITPFirstPartyGLibType() types.GType {
	core.LazyRegister(&xITPFirstPartyGLibType, "WEBKIT", "webkit_itp_first_party_get_type", false)
	return xITPFirstPartyGLibType()
}

func (x *ITPFirstParty) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ITPFirstPartyNewFromInternalPtr(ptr uintptr) *ITPFirstParty {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ITPFirstParty)(rawPtr)
}

var xITPFirstPartyGetDomain func(uintptr) string

// Get the domain name of @itp_first_party.
func (x *ITPFirstParty) GetDomain() string {
	core.LazyRegister(&xITPFirstPartyGetDomain, "WEBKIT", "webkit_itp_first_party_get_domain", false)

	cret := xITPFirstPartyGetDomain(x.GoPointer())
	return cret
}

var xITPFirstPartyGetLastUpdateTime func(uintptr) uintptr

// Get the last time a #WebKitITPThirdParty has been seen under @itp_first_party.
//
// Each @WebKitITPFirstParty is created by webkit_itp_third_party_get_first_parties() and
// therefore corresponds to exactly one #WebKitITPThirdParty.
func (x *ITPFirstParty) GetLastUpdateTime() *glib.DateTime {
	core.LazyRegister(&xITPFirstPartyGetLastUpdateTime, "WEBKIT", "webkit_itp_first_party_get_last_update_time", false)

	cret := xITPFirstPartyGetLastUpdateTime(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*glib.DateTime)(unsafe.Pointer(cret))
}

var xITPFirstPartyGetWebsiteDataAccessAllowed func(uintptr) bool

// Get whether @itp_first_party has granted website data access to its #WebKitITPThirdParty.
//
// Each @WebKitITPFirstParty is created by webkit_itp_third_party_get_first_parties() and
// therefore corresponds to exactly one #WebKitITPThirdParty.
func (x *ITPFirstParty) GetWebsiteDataAccessAllowed() bool {
	core.LazyRegister(&xITPFirstPartyGetWebsiteDataAccessAllowed, "WEBKIT", "webkit_itp_first_party_get_website_data_access_allowed", false)

	cret := xITPFirstPartyGetWebsiteDataAccessAllowed(x.GoPointer())
	return cret
}

var xITPFirstPartyRef func(uintptr) uintptr

// Atomically increments the reference count of @itp_first_party by one.
//
// This function is MT-safe and may be called from any thread.
func (x *ITPFirstParty) Ref() *ITPFirstParty {
	core.LazyRegister(&xITPFirstPartyRef, "WEBKIT", "webkit_itp_first_party_ref", false)

	cret := xITPFirstPartyRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*ITPFirstParty)(unsafe.Pointer(cret))
}

var xITPFirstPartyUnref func(uintptr)

// Atomically decrements the reference count of @itp_first_party by one.
//
// If the reference count drops to 0, all memory allocated by
// #WebKitITPFirstParty is released. This function is MT-safe and may be
// called from any thread.
func (x *ITPFirstParty) Unref() {
	core.LazyRegister(&xITPFirstPartyUnref, "WEBKIT", "webkit_itp_first_party_unref", false)

	xITPFirstPartyUnref(x.GoPointer())
}

// Describes a third party origin.
type ITPThirdParty struct {
	_ structs.HostLayout
}

var xITPThirdPartyGLibType func() types.GType

func ITPThirdPartyGLibType() types.GType {
	core.LazyRegister(&xITPThirdPartyGLibType, "WEBKIT", "webkit_itp_third_party_get_type", false)
	return xITPThirdPartyGLibType()
}

func (x *ITPThirdParty) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ITPThirdPartyNewFromInternalPtr(ptr uintptr) *ITPThirdParty {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ITPThirdParty)(rawPtr)
}

var xITPThirdPartyGetDomain func(uintptr) string

// Get the domain name of @itp_third_party.
func (x *ITPThirdParty) GetDomain() string {
	core.LazyRegister(&xITPThirdPartyGetDomain, "WEBKIT", "webkit_itp_third_party_get_domain", false)

	cret := xITPThirdPartyGetDomain(x.GoPointer())
	return cret
}

var xITPThirdPartyGetFirstParties func(uintptr) uintptr

// Get the list of #WebKitITPFirstParty under which @itp_third_party has been seen.
func (x *ITPThirdParty) GetFirstParties() *glib.List {
	core.LazyRegister(&xITPThirdPartyGetFirstParties, "WEBKIT", "webkit_itp_third_party_get_first_parties", false)

	cret := xITPThirdPartyGetFirstParties(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*glib.List)(unsafe.Pointer(cret))
}

var xITPThirdPartyRef func(uintptr) uintptr

// Atomically increments the reference count of @itp_third_party by one.
//
// This function is MT-safe and may be called from any thread.
func (x *ITPThirdParty) Ref() *ITPThirdParty {
	core.LazyRegister(&xITPThirdPartyRef, "WEBKIT", "webkit_itp_third_party_ref", false)

	cret := xITPThirdPartyRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*ITPThirdParty)(unsafe.Pointer(cret))
}

var xITPThirdPartyUnref func(uintptr)

// Atomically decrements the reference count of @itp_third_party by one.
//
// If the reference count drops to 0, all memory allocated by
// #WebKitITPThirdParty is released. This function is MT-safe and may be
// called from any thread.
func (x *ITPThirdParty) Unref() {
	core.LazyRegister(&xITPThirdPartyUnref, "WEBKIT", "webkit_itp_third_party_unref", false)

	xITPThirdPartyUnref(x.GoPointer())
}

type WebsiteDataManagerClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *WebsiteDataManagerClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func WebsiteDataManagerClassNewFromInternalPtr(ptr uintptr) *WebsiteDataManagerClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*WebsiteDataManagerClass)(rawPtr)
}

// Enum values used to denote the TLS errors policy.
type TLSErrorsPolicy int

var xTLSErrorsPolicyGLibType func() types.GType

func TLSErrorsPolicyGLibType() types.GType {
	core.LazyRegister(&xTLSErrorsPolicyGLibType, "WEBKIT", "webkit_tls_errors_policy_get_type", false)
	return xTLSErrorsPolicyGLibType()
}

const (

	// Ignore TLS errors.
	TlsErrorsPolicyIgnoreValue TLSErrorsPolicy = 0
	// TLS errors will emit
	//   #WebKitWebView::load-failed-with-tls-errors and, if the signal is handled,
	//   finish the load. In case the signal is not handled,
	//   #WebKitWebView::load-failed is emitted before the load finishes.
	TlsErrorsPolicyFailValue TLSErrorsPolicy = 1
)

// Manages data stored locally by web sites.
//
// You can use WebKitWebsiteDataManager to configure the local directories
// where website data will be stored. Use #WebKitWebsiteDataManager:base-data-directory
// and #WebKitWebsiteDataManager:base-cache-directory set a common base directory for all
// website data and caches.
//
// A WebKitWebsiteDataManager can be ephemeral, in which case all the directory configuration
// is not needed because website data will never persist. You can create an ephemeral WebKitWebsiteDataManager
// with webkit_website_data_manager_new_ephemeral().
//
// WebKitWebsiteDataManager can also be used to fetch website data, remove data
// stored by particular websites, or clear data for all websites modified since a given
// period of time.
type WebsiteDataManager struct {
	gobject.Object
}

var xWebsiteDataManagerGLibType func() types.GType

func WebsiteDataManagerGLibType() types.GType {
	core.LazyRegister(&xWebsiteDataManagerGLibType, "WEBKIT", "webkit_website_data_manager_get_type", false)
	return xWebsiteDataManagerGLibType()
}

func WebsiteDataManagerNewFromInternalPtr(ptr uintptr) *WebsiteDataManager {
	cls := &WebsiteDataManager{}
	cls.Ptr = ptr
	return cls
}

var xWebsiteDataManagerClear func(uintptr, WebsiteDataTypes, glib.TimeSpan, uintptr, uintptr, uintptr)

// Asynchronously clear the website data of the given @types modified in the past @timespan.
//
// If @timespan is 0, all website data will be removed.
//
// When the operation is finished, @callback will be called. You can then call
// webkit_website_data_manager_clear_finish() to get the result of the operation.
//
// Due to implementation limitations, this function does not currently delete
// any stored cookies if @timespan is nonzero. This behavior may change in the
// future.
func (x *WebsiteDataManager) Clear(TypesVar WebsiteDataTypes, TimespanVar glib.TimeSpan, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
	core.LazyRegister(&xWebsiteDataManagerClear, "WEBKIT", "webkit_website_data_manager_clear", false)

	xWebsiteDataManagerClear(x.GoPointer(), TypesVar, TimespanVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
}

var xWebsiteDataManagerClearFinish func(uintptr, uintptr, **glib.Error) bool

// Finish an asynchronous operation started with webkit_website_data_manager_clear()
func (x *WebsiteDataManager) ClearFinish(ResultVar gio.AsyncResult) (bool, error) {
	core.LazyRegister(&xWebsiteDataManagerClearFinish, "WEBKIT", "webkit_website_data_manager_clear_finish", false)
	var cerr *glib.Error

	cret := xWebsiteDataManagerClearFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr
}

var xWebsiteDataManagerFetch func(uintptr, WebsiteDataTypes, uintptr, uintptr, uintptr)

// Asynchronously get the list of #WebKitWebsiteData for the given @types.
//
// When the operation is finished, @callback will be called. You can then call
// webkit_website_data_manager_fetch_finish() to get the result of the operation.
func (x *WebsiteDataManager) Fetch(TypesVar WebsiteDataTypes, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
	core.LazyRegister(&xWebsiteDataManagerFetch, "WEBKIT", "webkit_website_data_manager_fetch", false)

	xWebsiteDataManagerFetch(x.GoPointer(), TypesVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
}

var xWebsiteDataManagerFetchFinish func(uintptr, uintptr, **glib.Error) uintptr

// Finish an asynchronous operation started with webkit_website_data_manager_fetch().
func (x *WebsiteDataManager) FetchFinish(ResultVar gio.AsyncResult) (*glib.List, error) {
	core.LazyRegister(&xWebsiteDataManagerFetchFinish, "WEBKIT", "webkit_website_data_manager_fetch_finish", false)
	var cerr *glib.Error

	cret := xWebsiteDataManagerFetchFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr != nil {
		return nil, cerr
	}
	if cret == 0 {
		return nil, nil
	}
	return (*glib.List)(unsafe.Pointer(cret)), nil
}

var xWebsiteDataManagerGetBaseCacheDirectory func(uintptr) string

// Get the #WebKitWebsiteDataManager:base-cache-directory property.
func (x *WebsiteDataManager) GetBaseCacheDirectory() string {
	core.LazyRegister(&xWebsiteDataManagerGetBaseCacheDirectory, "WEBKIT", "webkit_website_data_manager_get_base_cache_directory", false)

	cret := xWebsiteDataManagerGetBaseCacheDirectory(x.GoPointer())
	return cret
}

var xWebsiteDataManagerGetBaseDataDirectory func(uintptr) string

// Get the #WebKitWebsiteDataManager:base-data-directory property.
func (x *WebsiteDataManager) GetBaseDataDirectory() string {
	core.LazyRegister(&xWebsiteDataManagerGetBaseDataDirectory, "WEBKIT", "webkit_website_data_manager_get_base_data_directory", false)

	cret := xWebsiteDataManagerGetBaseDataDirectory(x.GoPointer())
	return cret
}

var xWebsiteDataManagerGetFaviconDatabase func(uintptr) uintptr

// Get the #WebKitFaviconDatabase of @manager.
func (x *WebsiteDataManager) GetFaviconDatabase() *FaviconDatabase {
	core.LazyRegister(&xWebsiteDataManagerGetFaviconDatabase, "WEBKIT", "webkit_website_data_manager_get_favicon_database", false)
	var cls *FaviconDatabase

	cret := xWebsiteDataManagerGetFaviconDatabase(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &FaviconDatabase{}
	cls.Ptr = cret
	return cls
}

var xWebsiteDataManagerGetFaviconsEnabled func(uintptr) bool

// Get whether website icons are enabled.
func (x *WebsiteDataManager) GetFaviconsEnabled() bool {
	core.LazyRegister(&xWebsiteDataManagerGetFaviconsEnabled, "WEBKIT", "webkit_website_data_manager_get_favicons_enabled", false)

	cret := xWebsiteDataManagerGetFaviconsEnabled(x.GoPointer())
	return cret
}

var xWebsiteDataManagerGetItpSummary func(uintptr, uintptr, uintptr, uintptr)

// Asynchronously get the list of #WebKitITPThirdParty seen for @manager.
//
// Every #WebKitITPThirdParty
// contains the list of #WebKitITPFirstParty under which it has been seen.
//
// When the operation is finished, @callback will be called. You can then call
// webkit_website_data_manager_get_itp_summary_finish() to get the result of the operation.
func (x *WebsiteDataManager) GetItpSummary(CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
	core.LazyRegister(&xWebsiteDataManagerGetItpSummary, "WEBKIT", "webkit_website_data_manager_get_itp_summary", false)

	xWebsiteDataManagerGetItpSummary(x.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
}

var xWebsiteDataManagerGetItpSummaryFinish func(uintptr, uintptr, **glib.Error) uintptr

// Finish an asynchronous operation started with webkit_website_data_manager_get_itp_summary().
func (x *WebsiteDataManager) GetItpSummaryFinish(ResultVar gio.AsyncResult) (*glib.List, error) {
	core.LazyRegister(&xWebsiteDataManagerGetItpSummaryFinish, "WEBKIT", "webkit_website_data_manager_get_itp_summary_finish", false)
	var cerr *glib.Error

	cret := xWebsiteDataManagerGetItpSummaryFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr != nil {
		return nil, cerr
	}
	if cret == 0 {
		return nil, nil
	}
	return (*glib.List)(unsafe.Pointer(cret)), nil
}

var xWebsiteDataManagerIsEphemeral func(uintptr) bool

// Get whether a #WebKitWebsiteDataManager is ephemeral.
//
// See #WebKitWebsiteDataManager:is-ephemeral for more details.
func (x *WebsiteDataManager) IsEphemeral() bool {
	core.LazyRegister(&xWebsiteDataManagerIsEphemeral, "WEBKIT", "webkit_website_data_manager_is_ephemeral", false)

	cret := xWebsiteDataManagerIsEphemeral(x.GoPointer())
	return cret
}

var xWebsiteDataManagerRemove func(uintptr, WebsiteDataTypes, *glib.List, uintptr, uintptr, uintptr)

// Asynchronously removes the website data in the given @website_data list.
//
// Asynchronously removes the website data of the given @types for websites in the given @website_data list.
// Use webkit_website_data_manager_clear() if you want to remove the website data for all sites.
//
// When the operation is finished, @callback will be called. You can then call
// webkit_website_data_manager_remove_finish() to get the result of the operation.
func (x *WebsiteDataManager) Remove(TypesVar WebsiteDataTypes, WebsiteDataVar *glib.List, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
	core.LazyRegister(&xWebsiteDataManagerRemove, "WEBKIT", "webkit_website_data_manager_remove", false)

	xWebsiteDataManagerRemove(x.GoPointer(), TypesVar, WebsiteDataVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
}

var xWebsiteDataManagerRemoveFinish func(uintptr, uintptr, **glib.Error) bool

// Finish an asynchronous operation started with webkit_website_data_manager_remove().
func (x *WebsiteDataManager) RemoveFinish(ResultVar gio.AsyncResult) (bool, error) {
	core.LazyRegister(&xWebsiteDataManagerRemoveFinish, "WEBKIT", "webkit_website_data_manager_remove_finish", false)
	var cerr *glib.Error

	cret := xWebsiteDataManagerRemoveFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr
}

var xWebsiteDataManagerSetFaviconsEnabled func(uintptr, bool)

// Set whether website icons are enabled. Website icons are disabled by default.
// When website icons are disabled, the #WebKitFaviconDatabase of @manager is closed and
// its reference removed, so webkit_website_data_manager_get_favicon_database() will
// return %NULL. If website icons are enabled again, a new #WebKitFaviconDatabase will
// be created.
func (x *WebsiteDataManager) SetFaviconsEnabled(EnabledVar bool) {
	core.LazyRegister(&xWebsiteDataManagerSetFaviconsEnabled, "WEBKIT", "webkit_website_data_manager_set_favicons_enabled", false)

	xWebsiteDataManagerSetFaviconsEnabled(x.GoPointer(), EnabledVar)
}

func (c *WebsiteDataManager) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *WebsiteDataManager) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyBaseCacheDirectory sets the "base-cache-directory" property.
// The base directory for caches. If %NULL, a default location will be used.
func (x *WebsiteDataManager) SetPropertyBaseCacheDirectory(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(&value)
	x.SetProperty("base-cache-directory", &v)
}

// GetPropertyBaseCacheDirectory gets the "base-cache-directory" property.
// The base directory for caches. If %NULL, a default location will be used.
func (x *WebsiteDataManager) GetPropertyBaseCacheDirectory() string {
	var v gobject.Value
	x.GetProperty("base-cache-directory", &v)
	return v.GetString()
}

// SetPropertyBaseDataDirectory sets the "base-data-directory" property.
// The base directory for website data. If %NULL, a default location will be used.
func (x *WebsiteDataManager) SetPropertyBaseDataDirectory(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(&value)
	x.SetProperty("base-data-directory", &v)
}

// GetPropertyBaseDataDirectory gets the "base-data-directory" property.
// The base directory for website data. If %NULL, a default location will be used.
func (x *WebsiteDataManager) GetPropertyBaseDataDirectory() string {
	var v gobject.Value
	x.GetProperty("base-data-directory", &v)
	return v.GetString()
}

// SetPropertyIsEphemeral sets the "is-ephemeral" property.
// Whether the #WebKitWebsiteDataManager is ephemeral. An ephemeral #WebKitWebsiteDataManager
// handles all websites data as non-persistent, and nothing will be written to the client
// storage. Note that if you create an ephemeral #WebKitWebsiteDataManager all other construction
// parameters to configure data directories will be ignored.
func (x *WebsiteDataManager) SetPropertyIsEphemeral(value bool) {
	var v gobject.Value
	v.Init(gobject.TypeBooleanVal)
	v.SetBoolean(value)
	x.SetProperty("is-ephemeral", &v)
}

// GetPropertyIsEphemeral gets the "is-ephemeral" property.
// Whether the #WebKitWebsiteDataManager is ephemeral. An ephemeral #WebKitWebsiteDataManager
// handles all websites data as non-persistent, and nothing will be written to the client
// storage. Note that if you create an ephemeral #WebKitWebsiteDataManager all other construction
// parameters to configure data directories will be ignored.
func (x *WebsiteDataManager) GetPropertyIsEphemeral() bool {
	var v gobject.Value
	x.GetProperty("is-ephemeral", &v)
	return v.GetBoolean()
}

// SetPropertyOriginStorageRatio sets the "origin-storage-ratio" property.
// The percentage of volume space that can be used for data storage for every domain.
// If the maximum storage is reached the storage request will fail with a QuotaExceededError exception.
// A value of 0.0 means that data storage is not allowed. A value of -1.0, which is the default,
// means WebKit will use the default quota (1 GiB).
func (x *WebsiteDataManager) SetPropertyOriginStorageRatio(value float64) {
	var v gobject.Value
	v.Init(gobject.TypeDoubleVal)
	v.SetDouble(value)
	x.SetProperty("origin-storage-ratio", &v)
}

// SetPropertyTotalStorageRatio sets the "total-storage-ratio" property.
// The percentage of volume space that can be used for data storage for all domains.
// If the maximum storage is reached the eviction will happen.
// A value of 0.0 means that data storage is not allowed. A value of -1.0, which is the default,
// means there's no limit for the total storage.
func (x *WebsiteDataManager) SetPropertyTotalStorageRatio(value float64) {
	var v gobject.Value
	v.Init(gobject.TypeDoubleVal)
	v.SetDouble(value)
	x.SetProperty("total-storage-ratio", &v)
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	WebsiteDataManagerGLibType()
}
