// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type DeviceInfoPermissionRequestClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *DeviceInfoPermissionRequestClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func DeviceInfoPermissionRequestClassNewFromInternalPtr(ptr uintptr) *DeviceInfoPermissionRequestClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*DeviceInfoPermissionRequestClass)(rawPtr)
}

// A permission request for enumerating the user's media devices
//
// WebKitDeviceInfoPermissionRequest represents a request for
// permission to whether WebKit should be allowed to access the user's
// devices information when requested through the MediaDevices.enumerateDevices
// API.
//
// When a WebKitDeviceInfoPermissionRequest is not handled by the user,
// it is denied by default.
type DeviceInfoPermissionRequest struct {
	gobject.Object
}

var xDeviceInfoPermissionRequestGLibType func() types.GType

func DeviceInfoPermissionRequestGLibType() types.GType {
	core.LazyRegister(&xDeviceInfoPermissionRequestGLibType, "WEBKIT", "webkit_device_info_permission_request_get_type", false)
	return xDeviceInfoPermissionRequestGLibType()
}

func DeviceInfoPermissionRequestNewFromInternalPtr(ptr uintptr) *DeviceInfoPermissionRequest {
	cls := &DeviceInfoPermissionRequest{}
	cls.Ptr = ptr
	return cls
}

func (c *DeviceInfoPermissionRequest) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *DeviceInfoPermissionRequest) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// Allow the action which triggered this request.
func (x *DeviceInfoPermissionRequest) Allow() {
	XWebkitPermissionRequestAllow(x.GoPointer())
}

// Deny the action which triggered this request.
func (x *DeviceInfoPermissionRequest) Deny() {
	XWebkitPermissionRequestDeny(x.GoPointer())
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	DeviceInfoPermissionRequestGLibType()
}
