// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gio"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type WebExtensionClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *WebExtensionClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func WebExtensionClassNewFromInternalPtr(ptr uintptr) *WebExtensionClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*WebExtensionClass)(rawPtr)
}

// Represents a [WebExtension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions).
//
// A #WebKitWebExtension object encapsulates a web extension’s
// resources that are defined by a [`manifest.json` file](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json).
//
// This class handles the reading and parsing of the manifest file
// along with the supporting resources like icons and localizations.
type WebExtension struct {
	gobject.Object
}

var xWebExtensionGLibType func() types.GType

func WebExtensionGLibType() types.GType {
	core.LazyRegister(&xWebExtensionGLibType, "WEBKIT", "webkit_web_extension_get_type", false)
	return xWebExtensionGLibType()
}

func WebExtensionNewFromInternalPtr(ptr uintptr) *WebExtension {
	cls := &WebExtension{}
	cls.Ptr = ptr
	return cls
}

var xNewWebExtension func(string, **glib.Error) uintptr

// Creates a new WebKitWebExtension from a folder containing the extension contents. The folder must
// contain a `manifest.json` file. If the manifest is invalid or missing, an error will be returned.
func NewWebExtension(ExtensionPathVar string) (*WebExtension, error) {
	core.LazyRegister(&xNewWebExtension, "WEBKIT", "webkit_web_extension_new", false)
	var cls *WebExtension
	var cerr *glib.Error

	cret := xNewWebExtension(ExtensionPathVar, &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &WebExtension{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr
}

var xWebExtensionGetActionIcon func(uintptr, float64, float64) uintptr

// Returns the extension's default action icon image for the specified size.
// This icon serves as a default and should be used to represent the extension in contexts like action sheets or toolbars prior to
// the extension being loaded into an extension context. Once the extension is loaded, use the
// “actionForTab:“ API to get the tab-specific icon.
// The returned image will be the best match for the specified size that is available in the extension's action icon set. If no matching icon is available,
// the method will fall back to the extension's icon.
func (x *WebExtension) GetActionIcon(WidthVar float64, HeightVar float64) *gio.IconBase {
	core.LazyRegister(&xWebExtensionGetActionIcon, "WEBKIT", "webkit_web_extension_get_action_icon", false)
	var cls *gio.IconBase

	cret := xWebExtensionGetActionIcon(x.GoPointer(), WidthVar, HeightVar)

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &gio.IconBase{}
	cls.Ptr = cret
	return cls
}

var xWebExtensionGetAllRequestedMatchPatterns func(uintptr) uintptr

// Get the set of websites that the extension requires access to for injected content
// and for receiving messages from websites.
func (x *WebExtension) GetAllRequestedMatchPatterns() uintptr {
	core.LazyRegister(&xWebExtensionGetAllRequestedMatchPatterns, "WEBKIT", "webkit_web_extension_get_all_requested_match_patterns", false)

	cret := xWebExtensionGetAllRequestedMatchPatterns(x.GoPointer())
	return cret
}

var xWebExtensionGetDefaultLocale func(uintptr) string

// Get the default locale for the extension.
func (x *WebExtension) GetDefaultLocale() string {
	core.LazyRegister(&xWebExtensionGetDefaultLocale, "WEBKIT", "webkit_web_extension_get_default_locale", false)

	cret := xWebExtensionGetDefaultLocale(x.GoPointer())
	return cret
}

var xWebExtensionGetDisplayActionLabel func(uintptr) string

// Get the localized display action label for the extension.
//
// This label serves as a default and should be used to represent the extension in contexts like action sheets or toolbars prior to
// the extension being loaded into an extension context.
// Once the extension is loaded, use the “actionForTab:“ API to get the tab-specific label.
func (x *WebExtension) GetDisplayActionLabel() string {
	core.LazyRegister(&xWebExtensionGetDisplayActionLabel, "WEBKIT", "webkit_web_extension_get_display_action_label", false)

	cret := xWebExtensionGetDisplayActionLabel(x.GoPointer())
	return cret
}

var xWebExtensionGetDisplayDescription func(uintptr) string

// Get the localized display description for the extension.
func (x *WebExtension) GetDisplayDescription() string {
	core.LazyRegister(&xWebExtensionGetDisplayDescription, "WEBKIT", "webkit_web_extension_get_display_description", false)

	cret := xWebExtensionGetDisplayDescription(x.GoPointer())
	return cret
}

var xWebExtensionGetDisplayName func(uintptr) string

// Get the localized name for the extension.
func (x *WebExtension) GetDisplayName() string {
	core.LazyRegister(&xWebExtensionGetDisplayName, "WEBKIT", "webkit_web_extension_get_display_name", false)

	cret := xWebExtensionGetDisplayName(x.GoPointer())
	return cret
}

var xWebExtensionGetDisplayShortName func(uintptr) string

// Get the localized short name for the extension.
func (x *WebExtension) GetDisplayShortName() string {
	core.LazyRegister(&xWebExtensionGetDisplayShortName, "WEBKIT", "webkit_web_extension_get_display_short_name", false)

	cret := xWebExtensionGetDisplayShortName(x.GoPointer())
	return cret
}

var xWebExtensionGetDisplayVersion func(uintptr) string

// Get the localized display version for the extension.
func (x *WebExtension) GetDisplayVersion() string {
	core.LazyRegister(&xWebExtensionGetDisplayVersion, "WEBKIT", "webkit_web_extension_get_display_version", false)

	cret := xWebExtensionGetDisplayVersion(x.GoPointer())
	return cret
}

var xWebExtensionGetHasBackgroundContent func(uintptr) bool

// Get whether the extension has background content that can run when needed.
func (x *WebExtension) GetHasBackgroundContent() bool {
	core.LazyRegister(&xWebExtensionGetHasBackgroundContent, "WEBKIT", "webkit_web_extension_get_has_background_content", false)

	cret := xWebExtensionGetHasBackgroundContent(x.GoPointer())
	return cret
}

var xWebExtensionGetHasCommands func(uintptr) bool

// Get whether the extension includes commands that users can invoke.
//
// These commands should be accessible via keyboard shortcuts,
// menu items, or other user interface elements provided
// by the app. The list of commands can be accessed
// via “commands“ on an extension context, and
// invoked via “performCommand:“.
func (x *WebExtension) GetHasCommands() bool {
	core.LazyRegister(&xWebExtensionGetHasCommands, "WEBKIT", "webkit_web_extension_get_has_commands", false)

	cret := xWebExtensionGetHasCommands(x.GoPointer())
	return cret
}

var xWebExtensionGetHasContentModificationRules func(uintptr) bool

// Get whether the extension includes rules used for
// content modification or blocking.
func (x *WebExtension) GetHasContentModificationRules() bool {
	core.LazyRegister(&xWebExtensionGetHasContentModificationRules, "WEBKIT", "webkit_web_extension_get_has_content_modification_rules", false)

	cret := xWebExtensionGetHasContentModificationRules(x.GoPointer())
	return cret
}

var xWebExtensionGetHasInjectedContent func(uintptr) bool

// Get whether the extension has script or stylesheet content
// that can be injected into webpages.
//
// Once the extension is loaded, use the “hasInjectedContent“
// property on an extension context, as the injectable content
// can change after the extension is loaded.
func (x *WebExtension) GetHasInjectedContent() bool {
	core.LazyRegister(&xWebExtensionGetHasInjectedContent, "WEBKIT", "webkit_web_extension_get_has_injected_content", false)

	cret := xWebExtensionGetHasInjectedContent(x.GoPointer())
	return cret
}

var xWebExtensionGetHasOptionsPage func(uintptr) bool

// Get whether the extension has an options page.
//
// The app should provide access to this page through a
// user interface element, which can be accessed via
// “optionsPageURL“ on an extension context.
func (x *WebExtension) GetHasOptionsPage() bool {
	core.LazyRegister(&xWebExtensionGetHasOptionsPage, "WEBKIT", "webkit_web_extension_get_has_options_page", false)

	cret := xWebExtensionGetHasOptionsPage(x.GoPointer())
	return cret
}

var xWebExtensionGetHasOverrideNewTabPage func(uintptr) bool

// Get whether the extension provides an alternative to
// the default new tab page.
//
// The app should prompt the user for permission to use
// the extension's new tab page as the default, which can
// be accessed via “overrideNewTabPageURL“
// on an extension context.
func (x *WebExtension) GetHasOverrideNewTabPage() bool {
	core.LazyRegister(&xWebExtensionGetHasOverrideNewTabPage, "WEBKIT", "webkit_web_extension_get_has_override_new_tab_page", false)

	cret := xWebExtensionGetHasOverrideNewTabPage(x.GoPointer())
	return cret
}

var xWebExtensionGetHasPersistentBackgroundContent func(uintptr) bool

// Get whether the extension has background content that stays in memory as long
// as the extension is loaded.
func (x *WebExtension) GetHasPersistentBackgroundContent() bool {
	core.LazyRegister(&xWebExtensionGetHasPersistentBackgroundContent, "WEBKIT", "webkit_web_extension_get_has_persistent_background_content", false)

	cret := xWebExtensionGetHasPersistentBackgroundContent(x.GoPointer())
	return cret
}

var xWebExtensionGetIcon func(uintptr, float64, float64) uintptr

// Returns the extension's icon image for the specified size.
// This icon should represent the extension in settings or other areas that show the extension.
// The returned image will be the best match for the specified size that is available in the extension's
// icon set. If no matching icon can be found, the method will return %NULL.
func (x *WebExtension) GetIcon(WidthVar float64, HeightVar float64) *gio.IconBase {
	core.LazyRegister(&xWebExtensionGetIcon, "WEBKIT", "webkit_web_extension_get_icon", false)
	var cls *gio.IconBase

	cret := xWebExtensionGetIcon(x.GoPointer(), WidthVar, HeightVar)

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &gio.IconBase{}
	cls.Ptr = cret
	return cls
}

var xWebExtensionGetManifestVersion func(uintptr) float64

// Get the parsed manifest version, or `0` if there is no
// version specified in the manifest.
//
// A [error@WebKit.WebExtensionError.UNSUPPORTED_MANIFEST_VERSION] error will be
// reported if the manifest version isn't specified.
func (x *WebExtension) GetManifestVersion() float64 {
	core.LazyRegister(&xWebExtensionGetManifestVersion, "WEBKIT", "webkit_web_extension_get_manifest_version", false)

	cret := xWebExtensionGetManifestVersion(x.GoPointer())
	return cret
}

var xWebExtensionGetOptionalPermissionMatchPatterns func(uintptr) uintptr

// Get the set of websites that the extension may need access to for optional functionality.
// These match patterns can be requested by the extension at a later time.
func (x *WebExtension) GetOptionalPermissionMatchPatterns() uintptr {
	core.LazyRegister(&xWebExtensionGetOptionalPermissionMatchPatterns, "WEBKIT", "webkit_web_extension_get_optional_permission_match_patterns", false)

	cret := xWebExtensionGetOptionalPermissionMatchPatterns(x.GoPointer())
	return cret
}

var xWebExtensionGetOptionalPermissions func(uintptr) []string

// Get the set of permissions that the extension may need for
// optional functionality. These permissions can be requested
// by the extension at a later time.
func (x *WebExtension) GetOptionalPermissions() []string {
	core.LazyRegister(&xWebExtensionGetOptionalPermissions, "WEBKIT", "webkit_web_extension_get_optional_permissions", false)

	cret := xWebExtensionGetOptionalPermissions(x.GoPointer())
	return cret
}

var xWebExtensionGetPath func(uintptr) string

// Get the path pointing to the folder containing the extension manifest and resources
func (x *WebExtension) GetPath() string {
	core.LazyRegister(&xWebExtensionGetPath, "WEBKIT", "webkit_web_extension_get_path", false)

	cret := xWebExtensionGetPath(x.GoPointer())
	return cret
}

var xWebExtensionGetRequestedPermissionMatchPatterns func(uintptr) uintptr

// Get the set of websites that the extension requires access to for its base functionality.
func (x *WebExtension) GetRequestedPermissionMatchPatterns() uintptr {
	core.LazyRegister(&xWebExtensionGetRequestedPermissionMatchPatterns, "WEBKIT", "webkit_web_extension_get_requested_permission_match_patterns", false)

	cret := xWebExtensionGetRequestedPermissionMatchPatterns(x.GoPointer())
	return cret
}

var xWebExtensionGetRequestedPermissions func(uintptr) []string

// Get the set of permissions that the extension requires
// for its base functionality.
func (x *WebExtension) GetRequestedPermissions() []string {
	core.LazyRegister(&xWebExtensionGetRequestedPermissions, "WEBKIT", "webkit_web_extension_get_requested_permissions", false)

	cret := xWebExtensionGetRequestedPermissions(x.GoPointer())
	return cret
}

var xWebExtensionGetVersion func(uintptr) string

// Get the version for the extension.
func (x *WebExtension) GetVersion() string {
	core.LazyRegister(&xWebExtensionGetVersion, "WEBKIT", "webkit_web_extension_get_version", false)

	cret := xWebExtensionGetVersion(x.GoPointer())
	return cret
}

var xWebExtensionSupportsManifestVersion func(uintptr, float64) bool

// Checks if a manifest version is supported by the extension.
func (x *WebExtension) SupportsManifestVersion(ManifestVersionVar float64) bool {
	core.LazyRegister(&xWebExtensionSupportsManifestVersion, "WEBKIT", "webkit_web_extension_supports_manifest_version", false)

	cret := xWebExtensionSupportsManifestVersion(x.GoPointer(), ManifestVersionVar)
	return cret
}

func (c *WebExtension) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *WebExtension) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// GetPropertyDefaultLocale gets the "default-locale" property.
// The default locale for the #WebKitWebExtension.
// See webkit_web_extension_get_default_locale() for more details.
func (x *WebExtension) GetPropertyDefaultLocale() string {
	var v gobject.Value
	x.GetProperty("default-locale", &v)
	return v.GetString()
}

// GetPropertyDisplayActionLabel gets the "display-action-label" property.
// The localized extension action label of the #WebKitWebExtension.
// See webkit_web_extension_get_display_action_label() for more details.
func (x *WebExtension) GetPropertyDisplayActionLabel() string {
	var v gobject.Value
	x.GetProperty("display-action-label", &v)
	return v.GetString()
}

// GetPropertyDisplayDescription gets the "display-description" property.
// The localized description of the #WebKitWebExtension.
// See webkit_web_extension_get_display_description() for more details.
func (x *WebExtension) GetPropertyDisplayDescription() string {
	var v gobject.Value
	x.GetProperty("display-description", &v)
	return v.GetString()
}

// GetPropertyDisplayName gets the "display-name" property.
// The localized name of the #WebKitWebExtension.
// See webkit_web_extension_get_display_name() for more details.
func (x *WebExtension) GetPropertyDisplayName() string {
	var v gobject.Value
	x.GetProperty("display-name", &v)
	return v.GetString()
}

// GetPropertyDisplayShortName gets the "display-short-name" property.
// The localized short name of the #WebKitWebExtension.
// See webkit_web_extension_get_display_short_name() for more details.
func (x *WebExtension) GetPropertyDisplayShortName() string {
	var v gobject.Value
	x.GetProperty("display-short-name", &v)
	return v.GetString()
}

// GetPropertyDisplayVersion gets the "display-version" property.
// The localized display version of the #WebKitWebExtension.
// See webkit_web_extension_get_display_version() for more details.
func (x *WebExtension) GetPropertyDisplayVersion() string {
	var v gobject.Value
	x.GetProperty("display-version", &v)
	return v.GetString()
}

// GetPropertyHasBackgroundContent gets the "has-background-content" property.
// Whether the #WebKitWebExtension has background content that can run when needed.
// See webkit_web_extension_get_has_background_content() for more details.
func (x *WebExtension) GetPropertyHasBackgroundContent() bool {
	var v gobject.Value
	x.GetProperty("has-background-content", &v)
	return v.GetBoolean()
}

// GetPropertyHasCommands gets the "has-commands" property.
// Whether the #WebKitWebExtension includes commands that users can invoke.
// See webkit_web_extension_get_has_commands() for more details.
func (x *WebExtension) GetPropertyHasCommands() bool {
	var v gobject.Value
	x.GetProperty("has-commands", &v)
	return v.GetBoolean()
}

// GetPropertyHasContentModificationRules gets the "has-content-modification-rules" property.
// Whether the #WebKitWebExtension includes rules used for content modification or blocking.
// See webkit_web_extension_get_content_modification_rules() for more details.
func (x *WebExtension) GetPropertyHasContentModificationRules() bool {
	var v gobject.Value
	x.GetProperty("has-content-modification-rules", &v)
	return v.GetBoolean()
}

// GetPropertyHasInjectedContent gets the "has-injected-content" property.
// Whether the #WebKitWebExtension has script or stylesheet content that can be injected into webpages.
// See webkit_web_extension_get_has_injected_content() for more details.
func (x *WebExtension) GetPropertyHasInjectedContent() bool {
	var v gobject.Value
	x.GetProperty("has-injected-content", &v)
	return v.GetBoolean()
}

// GetPropertyHasOptionsPage gets the "has-options-page" property.
// Whether the #WebKitWebExtension has an options page.
// See webkit_web_extension_get_has_options_page() for more details.
func (x *WebExtension) GetPropertyHasOptionsPage() bool {
	var v gobject.Value
	x.GetProperty("has-options-page", &v)
	return v.GetBoolean()
}

// GetPropertyHasOverrideNewTabPage gets the "has-override-new-tab-page" property.
// Whether the #WebKitWebExtension provides an alternative to the default new tab page.
// See webkit_web_extension_get_has_override_new_tab_page() for more details.
func (x *WebExtension) GetPropertyHasOverrideNewTabPage() bool {
	var v gobject.Value
	x.GetProperty("has-override-new-tab-page", &v)
	return v.GetBoolean()
}

// GetPropertyHasPersistentBackgroundContent gets the "has-persistent-background-content" property.
// Whether the #WebKitWebExtension has background content that stays in memory as long as the extension is loaded.
// See webkit_web_extension_get_has_persistent_background_content() for more details.
func (x *WebExtension) GetPropertyHasPersistentBackgroundContent() bool {
	var v gobject.Value
	x.GetProperty("has-persistent-background-content", &v)
	return v.GetBoolean()
}

// GetPropertyManifestVersion gets the "manifest-version" property.
// The parsed manifest version of the #WebKitWebExtension.
// See webkit_web_extension_get_manifest_version() for more details.
func (x *WebExtension) GetPropertyManifestVersion() string {
	var v gobject.Value
	x.GetProperty("manifest-version", &v)
	return v.GetString()
}

// GetPropertyOptionalPermissions gets the "optional-permissions" property.
// The set of permissions that the #WebKitWebExtension may need for optional functionality.
// See webkit_web_extension_get_optional_permissions() for more details.
func (x *WebExtension) GetPropertyOptionalPermissions() []string {
	var v gobject.Value
	x.GetProperty("optional-permissions", &v)
	return core.GoStringSlice(v.GetBoxed())
}

// SetPropertyPath sets the "path" property.
// A string pointing to the folder containing the extension manifest and resources.
// See webkit_web_extension_get_path() for more details.
func (x *WebExtension) SetPropertyPath(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(&value)
	x.SetProperty("path", &v)
}

// GetPropertyPath gets the "path" property.
// A string pointing to the folder containing the extension manifest and resources.
// See webkit_web_extension_get_path() for more details.
func (x *WebExtension) GetPropertyPath() string {
	var v gobject.Value
	x.GetProperty("path", &v)
	return v.GetString()
}

// GetPropertyRequestedPermissions gets the "requested-permissions" property.
// The set of permissions that the #WebKitWebExtension requires for its base functionality.
// See webkit_web_extension_get_requested_permissions() for more details.
func (x *WebExtension) GetPropertyRequestedPermissions() []string {
	var v gobject.Value
	x.GetProperty("requested-permissions", &v)
	return core.GoStringSlice(v.GetBoxed())
}

// GetPropertyVersion gets the "version" property.
// The version of the #WebKitWebExtension.
// See webkit_web_extension_get_version() for more details.
func (x *WebExtension) GetPropertyVersion() string {
	var v gobject.Value
	x.GetProperty("version", &v)
	return v.GetString()
}

// Initializes the object implementing the interface.
//
// This method is intended for language bindings. If writing in C,
// g_initable_new() should typically be used instead.
//
// The object must be initialized before any real use after initial
// construction, either with this function or g_async_initable_init_async().
//
// Implementations may also support cancellation. If @cancellable is not %NULL,
// then initialization can be cancelled by triggering the cancellable object
// from another thread. If the operation was cancelled, the error
// %G_IO_ERROR_CANCELLED will be returned. If @cancellable is not %NULL and
// the object doesn't support cancellable initialization the error
// %G_IO_ERROR_NOT_SUPPORTED will be returned.
//
// If the object is not initialized, or initialization returns with an
// error, then all operations on the object except g_object_ref() and
// g_object_unref() are considered to be invalid, and have undefined
// behaviour. See the [description][iface@Gio.Initable#description] for more details.
//
// Callers should not assume that a class which implements #GInitable can be
// initialized multiple times, unless the class explicitly documents itself as
// supporting this. Generally, a class’ implementation of init() can assume
// (and assert) that it will only be called once. Previously, this documentation
// recommended all #GInitable implementations should be idempotent; that
// recommendation was relaxed in GLib 2.54.
//
// If a class explicitly supports being initialized multiple times, it is
// recommended that the method is idempotent: multiple calls with the same
// arguments should return the same results. Only the first call initializes
// the object; further calls return the result of the first call.
//
// One reason why a class might need to support idempotent initialization is if
// it is designed to be used via the singleton pattern, with a
// #GObjectClass.constructor that sometimes returns an existing instance.
// In this pattern, a caller would expect to be able to call g_initable_init()
// on the result of g_object_new(), regardless of whether it is in fact a new
// instance.
func (x *WebExtension) Init(CancellableVar *gio.Cancellable) (bool, error) {
	var cerr *glib.Error

	cret := gio.XGInitableInit(x.GoPointer(), CancellableVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	WebExtensionGLibType()
}
