// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type WebsitePoliciesClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *WebsitePoliciesClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func WebsitePoliciesClassNewFromInternalPtr(ptr uintptr) *WebsitePoliciesClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*WebsitePoliciesClass)(rawPtr)
}

// Enum values used to specify autoplay policies.
type AutoplayPolicy int

var xAutoplayPolicyGLibType func() types.GType

func AutoplayPolicyGLibType() types.GType {
	core.LazyRegister(&xAutoplayPolicyGLibType, "WEBKIT", "webkit_autoplay_policy_get_type", false)
	return xAutoplayPolicyGLibType()
}

const (

	// Do not restrict autoplay.
	AutoplayAllowValue AutoplayPolicy = 0
	// Allow videos to autoplay if
	//     they have no audio track, or if their audio track is muted.
	AutoplayAllowWithoutSoundValue AutoplayPolicy = 1
	// Never allow autoplay.
	AutoplayDenyValue AutoplayPolicy = 2
)

// View specific website policies.
//
// WebKitWebsitePolicies allows you to configure per-page policies,
// currently only autoplay policies are supported.
type WebsitePolicies struct {
	gobject.Object
}

var xWebsitePoliciesGLibType func() types.GType

func WebsitePoliciesGLibType() types.GType {
	core.LazyRegister(&xWebsitePoliciesGLibType, "WEBKIT", "webkit_website_policies_get_type", false)
	return xWebsitePoliciesGLibType()
}

func WebsitePoliciesNewFromInternalPtr(ptr uintptr) *WebsitePolicies {
	cls := &WebsitePolicies{}
	cls.Ptr = ptr
	return cls
}

var xNewWebsitePolicies func() uintptr

// Create a new #WebKitWebsitePolicies.
func NewWebsitePolicies() *WebsitePolicies {
	core.LazyRegister(&xNewWebsitePolicies, "WEBKIT", "webkit_website_policies_new", false)
	var cls *WebsitePolicies

	cret := xNewWebsitePolicies()

	if cret == 0 {
		return nil
	}
	cls = &WebsitePolicies{}
	cls.Ptr = cret
	return cls
}

var xNewWebsitePoliciesWithPolicies func(string, ...interface{}) uintptr

// Create a new #WebKitWebsitePolicies with given policies.
//
// Create a new #WebKitWebsitePolicies with policies given as variadic
// arguments.
func NewWebsitePoliciesWithPolicies(FirstPolicyNameVar string, varArgs ...interface{}) *WebsitePolicies {
	core.LazyRegister(&xNewWebsitePoliciesWithPolicies, "WEBKIT", "webkit_website_policies_new_with_policies", false)
	var cls *WebsitePolicies

	cret := xNewWebsitePoliciesWithPolicies(FirstPolicyNameVar, varArgs...)

	if cret == 0 {
		return nil
	}
	cls = &WebsitePolicies{}
	cls.Ptr = cret
	return cls
}

var xWebsitePoliciesGetAutoplayPolicy func(uintptr) AutoplayPolicy

// Get the #WebKitWebsitePolicies:autoplay property.
func (x *WebsitePolicies) GetAutoplayPolicy() AutoplayPolicy {
	core.LazyRegister(&xWebsitePoliciesGetAutoplayPolicy, "WEBKIT", "webkit_website_policies_get_autoplay_policy", false)

	cret := xWebsitePoliciesGetAutoplayPolicy(x.GoPointer())
	return cret
}

func (c *WebsitePolicies) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *WebsitePolicies) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	WebsitePoliciesGLibType()
}
