// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk-webkit/soup"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type URIRequestClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *URIRequestClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func URIRequestClassNewFromInternalPtr(ptr uintptr) *URIRequestClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*URIRequestClass)(rawPtr)
}

// Represents a URI request.
//
// A #WebKitURIRequest can be created with a URI using the
// webkit_uri_request_new() method, and you can get the URI of an
// existing request with the webkit_uri_request_get_uri() one.
type URIRequest struct {
	gobject.Object
}

var xURIRequestGLibType func() types.GType

func URIRequestGLibType() types.GType {
	core.LazyRegister(&xURIRequestGLibType, "WEBKIT", "webkit_uri_request_get_type", false)
	return xURIRequestGLibType()
}

func URIRequestNewFromInternalPtr(ptr uintptr) *URIRequest {
	cls := &URIRequest{}
	cls.Ptr = ptr
	return cls
}

var xNewURIRequest func(string) uintptr

// Creates a new #WebKitURIRequest for the given URI.
func NewURIRequest(UriVar string) *URIRequest {
	core.LazyRegister(&xNewURIRequest, "WEBKIT", "webkit_uri_request_new", false)
	var cls *URIRequest

	cret := xNewURIRequest(UriVar)

	if cret == 0 {
		return nil
	}
	cls = &URIRequest{}
	cls.Ptr = cret
	return cls
}

var xURIRequestGetHttpHeaders func(uintptr) uintptr

// Get the HTTP headers of a #WebKitURIRequest as a #SoupMessageHeaders.
func (x *URIRequest) GetHttpHeaders() *soup.MessageHeaders {
	core.LazyRegister(&xURIRequestGetHttpHeaders, "WEBKIT", "webkit_uri_request_get_http_headers", false)

	cret := xURIRequestGetHttpHeaders(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*soup.MessageHeaders)(unsafe.Pointer(cret))
}

var xURIRequestGetHttpMethod func(uintptr) string

// Get the HTTP method of the #WebKitURIRequest.
func (x *URIRequest) GetHttpMethod() string {
	core.LazyRegister(&xURIRequestGetHttpMethod, "WEBKIT", "webkit_uri_request_get_http_method", false)

	cret := xURIRequestGetHttpMethod(x.GoPointer())
	return cret
}

var xURIRequestGetUri func(uintptr) string

// Obtains the request URI.
func (x *URIRequest) GetUri() string {
	core.LazyRegister(&xURIRequestGetUri, "WEBKIT", "webkit_uri_request_get_uri", false)

	cret := xURIRequestGetUri(x.GoPointer())
	return cret
}

var xURIRequestSetUri func(uintptr, string)

// Set the URI of @request
func (x *URIRequest) SetUri(UriVar string) {
	core.LazyRegister(&xURIRequestSetUri, "WEBKIT", "webkit_uri_request_set_uri", false)

	xURIRequestSetUri(x.GoPointer(), UriVar)
}

func (c *URIRequest) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *URIRequest) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyUri sets the "uri" property.
// The URI to which the request will be made.
func (x *URIRequest) SetPropertyUri(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(&value)
	x.SetProperty("uri", &v)
}

// GetPropertyUri gets the "uri" property.
// The URI to which the request will be made.
func (x *URIRequest) GetPropertyUri() string {
	var v gobject.Value
	x.GetProperty("uri", &v)
	return v.GetString()
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	URIRequestGLibType()
}
