// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gdk"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type ColorChooserRequestClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *ColorChooserRequestClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ColorChooserRequestClassNewFromInternalPtr(ptr uintptr) *ColorChooserRequestClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ColorChooserRequestClass)(rawPtr)
}

// A request to open a color chooser.
//
// Whenever the user interacts with an &lt;input type='color' /&gt;
// HTML element, WebKit will need to show a dialog to choose a color. For that
// to happen in a general way, instead of just opening a #GtkColorChooser
// (which might be not desirable in some cases, which could prefer to use their
// own color chooser dialog), WebKit will fire the
// #WebKitWebView::run-color-chooser signal with a #WebKitColorChooserRequest
// object, which will allow the client application to specify the color to be
// selected, to inspect the details of the request (e.g. to get initial color)
// and to cancel the request, in case nothing was selected.
//
// In case the client application does not wish to handle this signal,
// WebKit will provide a default handler which will asynchronously run
// a regular #GtkColorChooserDialog for the user to interact with.
type ColorChooserRequest struct {
	gobject.Object
}

var xColorChooserRequestGLibType func() types.GType

func ColorChooserRequestGLibType() types.GType {
	core.LazyRegister(&xColorChooserRequestGLibType, "WEBKIT", "webkit_color_chooser_request_get_type", false)
	return xColorChooserRequestGLibType()
}

func ColorChooserRequestNewFromInternalPtr(ptr uintptr) *ColorChooserRequest {
	cls := &ColorChooserRequest{}
	cls.Ptr = ptr
	return cls
}

var xColorChooserRequestCancel func(uintptr)

// Cancels @request and the input element changes to use the initial color.
//
// Cancels @request and the input element changes to use the initial color
// it has before the request started.
// The signal #WebKitColorChooserRequest::finished
// is emitted to notify that the request has finished.
func (x *ColorChooserRequest) Cancel() {
	core.LazyRegister(&xColorChooserRequestCancel, "WEBKIT", "webkit_color_chooser_request_cancel", false)

	xColorChooserRequestCancel(x.GoPointer())
}

var xColorChooserRequestFinish func(uintptr)

// Finishes @request and the input element keeps the current value of
// #WebKitColorChooserRequest:rgba.
//
// Finishes @request and the input element keeps the current value of
// #WebKitColorChooserRequest:rgba.
// The signal #WebKitColorChooserRequest::finished
// is emitted to notify that the request has finished.
func (x *ColorChooserRequest) Finish() {
	core.LazyRegister(&xColorChooserRequestFinish, "WEBKIT", "webkit_color_chooser_request_finish", false)

	xColorChooserRequestFinish(x.GoPointer())
}

var xColorChooserRequestGetElementRectangle func(uintptr, *gdk.Rectangle)

// Gets the bounding box of the color input element.
func (x *ColorChooserRequest) GetElementRectangle(RectVar *gdk.Rectangle) {
	core.LazyRegister(&xColorChooserRequestGetElementRectangle, "WEBKIT", "webkit_color_chooser_request_get_element_rectangle", false)

	xColorChooserRequestGetElementRectangle(x.GoPointer(), RectVar)
}

var xColorChooserRequestGetRgba func(uintptr, *gdk.RGBA)

// Gets the current #GdkRGBA color of @request
func (x *ColorChooserRequest) GetRgba(RgbaVar *gdk.RGBA) {
	core.LazyRegister(&xColorChooserRequestGetRgba, "WEBKIT", "webkit_color_chooser_request_get_rgba", false)

	xColorChooserRequestGetRgba(x.GoPointer(), RgbaVar)
}

var xColorChooserRequestSetRgba func(uintptr, *gdk.RGBA)

// Sets the current #GdkRGBA color of @request
func (x *ColorChooserRequest) SetRgba(RgbaVar *gdk.RGBA) {
	core.LazyRegister(&xColorChooserRequestSetRgba, "WEBKIT", "webkit_color_chooser_request_set_rgba", false)

	xColorChooserRequestSetRgba(x.GoPointer(), RgbaVar)
}

func (c *ColorChooserRequest) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *ColorChooserRequest) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyRgba sets the "rgba" property.
// The #GdkRGBA color of the request
func (x *ColorChooserRequest) SetPropertyRgba(value uintptr) {
	var v gobject.Value
	v.Init(gobject.TypePointerVal)
	v.SetPointer(value)
	x.SetProperty("rgba", &v)
}

// GetPropertyRgba gets the "rgba" property.
// The #GdkRGBA color of the request
func (x *ColorChooserRequest) GetPropertyRgba() uintptr {
	var v gobject.Value
	x.GetProperty("rgba", &v)
	return v.GetPointer()
}

// Emitted when the @request finishes. This signal can be emitted because the
// user completed the @request calling webkit_color_chooser_request_finish(),
// or cancelled it with webkit_color_chooser_request_cancel() or because the
// color input element is removed from the DOM.
func (x *ColorChooserRequest) ConnectFinished(cb *func(ColorChooserRequest)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("webkit.ColorChooserRequest.Finished", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(ColorChooserRequest))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := ColorChooserRequest{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "finished", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
	ColorChooserRequestGLibType()
}
