// Package webkit was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package webkit

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// One item of a #WebKitOptionMenu.
//
// The #WebKitOptionMenu is composed of WebKitOptionMenuItem&lt;!-- --&gt;s.
// A WebKitOptionMenuItem always has a label and can contain a tooltip text.
// You can use the WebKitOptionMenuItem of a #WebKitOptionMenu to build your
// own menus.
type OptionMenuItem struct {
	_ structs.HostLayout
}

var xOptionMenuItemGLibType func() types.GType

func OptionMenuItemGLibType() types.GType {
	core.LazyRegister(&xOptionMenuItemGLibType, "WEBKIT", "webkit_option_menu_item_get_type", false)
	return xOptionMenuItemGLibType()
}

func (x *OptionMenuItem) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func OptionMenuItemNewFromInternalPtr(ptr uintptr) *OptionMenuItem {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*OptionMenuItem)(rawPtr)
}

var xOptionMenuItemCopy func(uintptr) uintptr

// Make a copy of the #WebKitOptionMenuItem.
func (x *OptionMenuItem) Copy() *OptionMenuItem {
	core.LazyRegister(&xOptionMenuItemCopy, "WEBKIT", "webkit_option_menu_item_copy", false)

	cret := xOptionMenuItemCopy(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*OptionMenuItem)(unsafe.Pointer(cret))
}

var xOptionMenuItemFree func(uintptr)

// Free the #WebKitOptionMenuItem.
func (x *OptionMenuItem) Free() {
	core.LazyRegister(&xOptionMenuItemFree, "WEBKIT", "webkit_option_menu_item_free", false)

	xOptionMenuItemFree(x.GoPointer())
}

var xOptionMenuItemGetLabel func(uintptr) string

// Get the label of a #WebKitOptionMenuItem.
func (x *OptionMenuItem) GetLabel() string {
	core.LazyRegister(&xOptionMenuItemGetLabel, "WEBKIT", "webkit_option_menu_item_get_label", false)

	cret := xOptionMenuItemGetLabel(x.GoPointer())
	return cret
}

var xOptionMenuItemGetTooltip func(uintptr) string

// Get the tooltip of a #WebKitOptionMenuItem.
func (x *OptionMenuItem) GetTooltip() string {
	core.LazyRegister(&xOptionMenuItemGetTooltip, "WEBKIT", "webkit_option_menu_item_get_tooltip", false)

	cret := xOptionMenuItemGetTooltip(x.GoPointer())
	return cret
}

var xOptionMenuItemIsEnabled func(uintptr) bool

// Whether a #WebKitOptionMenuItem is enabled.
func (x *OptionMenuItem) IsEnabled() bool {
	core.LazyRegister(&xOptionMenuItemIsEnabled, "WEBKIT", "webkit_option_menu_item_is_enabled", false)

	cret := xOptionMenuItemIsEnabled(x.GoPointer())
	return cret
}

var xOptionMenuItemIsGroupChild func(uintptr) bool

// Whether a #WebKitOptionMenuItem is a group child.
func (x *OptionMenuItem) IsGroupChild() bool {
	core.LazyRegister(&xOptionMenuItemIsGroupChild, "WEBKIT", "webkit_option_menu_item_is_group_child", false)

	cret := xOptionMenuItemIsGroupChild(x.GoPointer())
	return cret
}

var xOptionMenuItemIsGroupLabel func(uintptr) bool

// Whether a #WebKitOptionMenuItem is a group label.
func (x *OptionMenuItem) IsGroupLabel() bool {
	core.LazyRegister(&xOptionMenuItemIsGroupLabel, "WEBKIT", "webkit_option_menu_item_is_group_label", false)

	cret := xOptionMenuItemIsGroupLabel(x.GoPointer())
	return cret
}

var xOptionMenuItemIsSelected func(uintptr) bool

// Whether a #WebKitOptionMenuItem is the currently selected one.
func (x *OptionMenuItem) IsSelected() bool {
	core.LazyRegister(&xOptionMenuItemIsSelected, "WEBKIT", "webkit_option_menu_item_is_selected", false)

	cret := xOptionMenuItemIsSelected(x.GoPointer())
	return cret
}

func init() {
	core.SetPackageName("WEBKIT", "webkitgtk-6.0")
	core.SetSharedLibraries("WEBKIT", []string{"libwebkitgtk-6.0.so.4", "libjavascriptcoregtk-6.0.so.1", "libwebkitgtk-6.0.4.dylib", "libjavascriptcoregtk-6.0.1.dylib"})

	// Manually register types since they aren't automatically registered when
	// WebKit is loaded. See https://bugs.webkit.org/show_bug.cgi?id=175937.
}
