// Package javascriptcore was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package javascriptcore

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// Function used to handle JavaScript exceptions in a #JSCContext.
type ExceptionHandler func(uintptr, uintptr, uintptr)

type ContextClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *ContextClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ContextClassNewFromInternalPtr(ptr uintptr) *ContextClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ContextClass)(rawPtr)
}

// Enum values to specify a mode to check for syntax errors in jsc_context_check_syntax().
type CheckSyntaxMode int

const (

	// mode to check syntax of a script
	JscCheckSyntaxModeScriptValue CheckSyntaxMode = 0
	// mode to check syntax of a module
	JscCheckSyntaxModeModuleValue CheckSyntaxMode = 1
)

// Enum values to specify the result of jsc_context_check_syntax().
type CheckSyntaxResult int

const (

	// no errors
	JscCheckSyntaxResultSuccessValue CheckSyntaxResult = 0
	// recoverable syntax error
	JscCheckSyntaxResultRecoverableErrorValue CheckSyntaxResult = 1
	// irrecoverable syntax error
	JscCheckSyntaxResultIrrecoverableErrorValue CheckSyntaxResult = 2
	// unterminated literal error
	JscCheckSyntaxResultUnterminatedLiteralErrorValue CheckSyntaxResult = 3
	// out of memory error
	JscCheckSyntaxResultOutOfMemoryErrorValue CheckSyntaxResult = 4
	// stack overflow error
	JscCheckSyntaxResultStackOverflowErrorValue CheckSyntaxResult = 5
)

// JSCContext represents a JavaScript execution context, where all operations
// take place and where the values will be associated.
//
// When a new context is created, a global object is allocated and the built-in JavaScript
// objects (Object, Function, String, Array) are populated. You can execute JavaScript in
// the context by using jsc_context_evaluate() or jsc_context_evaluate_with_source_uri().
// It's also possible to register custom objects in the context with jsc_context_register_class().
type Context struct {
	gobject.Object
}

var xContextGLibType func() types.GType

func ContextGLibType() types.GType {
	core.LazyRegister(&xContextGLibType, "JAVASCRIPTCORE", "jsc_context_get_type", false)
	return xContextGLibType()
}

func ContextNewFromInternalPtr(ptr uintptr) *Context {
	cls := &Context{}
	cls.Ptr = ptr
	return cls
}

var xNewContext func() uintptr

// Create a new #JSCContext. The context is created in a new #JSCVirtualMachine.
// Use jsc_context_new_with_virtual_machine() to create a new #JSCContext in an
// existing #JSCVirtualMachine.
func NewContext() *Context {
	core.LazyRegister(&xNewContext, "JAVASCRIPTCORE", "jsc_context_new", false)
	var cls *Context

	cret := xNewContext()

	if cret == 0 {
		return nil
	}
	cls = &Context{}
	cls.Ptr = cret
	return cls
}

var xNewContextWithVirtualMachine func(uintptr) uintptr

// Create a new #JSCContext in @virtual_machine.
func NewContextWithVirtualMachine(VmVar *VirtualMachine) *Context {
	core.LazyRegister(&xNewContextWithVirtualMachine, "JAVASCRIPTCORE", "jsc_context_new_with_virtual_machine", false)
	var cls *Context

	cret := xNewContextWithVirtualMachine(VmVar.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &Context{}
	cls.Ptr = cret
	return cls
}

var xContextCheckSyntax func(uintptr, string, int, CheckSyntaxMode, string, uint, **Exception) CheckSyntaxResult

// Check the given @code in @context for syntax errors. The @line_number is the starting line number in @uri;
// the value is one-based so the first line is 1. @uri and @line_number are only used to fill the @exception.
// In case of errors @exception will be set to a new #JSCException with the details. You can pass %NULL to
// @exception to ignore the error details.
func (x *Context) CheckSyntax(CodeVar string, LengthVar int, ModeVar CheckSyntaxMode, UriVar string, LineNumberVar uint, ExceptionVar **Exception) CheckSyntaxResult {
	core.LazyRegister(&xContextCheckSyntax, "JAVASCRIPTCORE", "jsc_context_check_syntax", false)

	cret := xContextCheckSyntax(x.GoPointer(), CodeVar, LengthVar, ModeVar, UriVar, LineNumberVar, ExceptionVar)
	return cret
}

var xContextClearException func(uintptr)

// Clear the uncaught exception in @context if any.
func (x *Context) ClearException() {
	core.LazyRegister(&xContextClearException, "JAVASCRIPTCORE", "jsc_context_clear_exception", false)

	xContextClearException(x.GoPointer())
}

var xContextEvaluate func(uintptr, string, int) uintptr

// Evaluate @code in @context.
func (x *Context) Evaluate(CodeVar string, LengthVar int) *Value {
	core.LazyRegister(&xContextEvaluate, "JAVASCRIPTCORE", "jsc_context_evaluate", false)
	var cls *Value

	cret := xContextEvaluate(x.GoPointer(), CodeVar, LengthVar)

	if cret == 0 {
		return nil
	}
	cls = &Value{}
	cls.Ptr = cret
	return cls
}

var xContextEvaluateInObject func(uintptr, string, int, uintptr, uintptr, string, uint, **Value) uintptr

// Evaluate @code and create an new object where symbols defined in @code will be added as properties,
// instead of being added to @context global object. The new object is returned as @object parameter.
// Similar to how jsc_value_new_object() works, if @object_instance is not %NULL @object_class must be provided too.
// The @line_number is the starting line number in @uri; the value is one-based so the first line is 1.
// @uri and @line_number will be shown in exceptions and they don't affect the behavior of the script.
func (x *Context) EvaluateInObject(CodeVar string, LengthVar int, ObjectInstanceVar uintptr, ObjectClassVar *Class, UriVar string, LineNumberVar uint, ObjectVar **Value) *Value {
	core.LazyRegister(&xContextEvaluateInObject, "JAVASCRIPTCORE", "jsc_context_evaluate_in_object", false)
	var cls *Value

	cret := xContextEvaluateInObject(x.GoPointer(), CodeVar, LengthVar, ObjectInstanceVar, ObjectClassVar.GoPointer(), UriVar, LineNumberVar, ObjectVar)

	if cret == 0 {
		return nil
	}
	cls = &Value{}
	cls.Ptr = cret
	return cls
}

var xContextEvaluateWithSourceUri func(uintptr, string, int, string, uint) uintptr

// Evaluate @code in @context using @uri as the source URI. The @line_number is the starting line number
// in @uri; the value is one-based so the first line is 1. @uri and @line_number will be shown in exceptions and
// they don't affect the behavior of the script.
func (x *Context) EvaluateWithSourceUri(CodeVar string, LengthVar int, UriVar string, LineNumberVar uint) *Value {
	core.LazyRegister(&xContextEvaluateWithSourceUri, "JAVASCRIPTCORE", "jsc_context_evaluate_with_source_uri", false)
	var cls *Value

	cret := xContextEvaluateWithSourceUri(x.GoPointer(), CodeVar, LengthVar, UriVar, LineNumberVar)

	if cret == 0 {
		return nil
	}
	cls = &Value{}
	cls.Ptr = cret
	return cls
}

var xContextGetException func(uintptr) uintptr

// Get the last unhandled exception thrown in @context by API functions calls.
func (x *Context) GetException() *Exception {
	core.LazyRegister(&xContextGetException, "JAVASCRIPTCORE", "jsc_context_get_exception", false)
	var cls *Exception

	cret := xContextGetException(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &Exception{}
	cls.Ptr = cret
	return cls
}

var xContextGetGlobalObject func(uintptr) uintptr

// Get a #JSCValue referencing the @context global object
func (x *Context) GetGlobalObject() *Value {
	core.LazyRegister(&xContextGetGlobalObject, "JAVASCRIPTCORE", "jsc_context_get_global_object", false)
	var cls *Value

	cret := xContextGetGlobalObject(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &Value{}
	cls.Ptr = cret
	return cls
}

var xContextGetValue func(uintptr, string) uintptr

// Get a property of @context global object with @name.
func (x *Context) GetValue(NameVar string) *Value {
	core.LazyRegister(&xContextGetValue, "JAVASCRIPTCORE", "jsc_context_get_value", false)
	var cls *Value

	cret := xContextGetValue(x.GoPointer(), NameVar)

	if cret == 0 {
		return nil
	}
	cls = &Value{}
	cls.Ptr = cret
	return cls
}

var xContextGetVirtualMachine func(uintptr) uintptr

// Get the #JSCVirtualMachine where @context was created.
func (x *Context) GetVirtualMachine() *VirtualMachine {
	core.LazyRegister(&xContextGetVirtualMachine, "JAVASCRIPTCORE", "jsc_context_get_virtual_machine", false)
	var cls *VirtualMachine

	cret := xContextGetVirtualMachine(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &VirtualMachine{}
	cls.Ptr = cret
	return cls
}

var xContextPopExceptionHandler func(uintptr)

// Remove the last #JSCExceptionHandler previously pushed to @context with
// jsc_context_push_exception_handler().
func (x *Context) PopExceptionHandler() {
	core.LazyRegister(&xContextPopExceptionHandler, "JAVASCRIPTCORE", "jsc_context_pop_exception_handler", false)

	xContextPopExceptionHandler(x.GoPointer())
}

var xContextPushExceptionHandler func(uintptr, uintptr, uintptr, uintptr)

// Push an exception handler in @context. Whenever a JavaScript exception happens in
// the #JSCContext, the given @handler will be called. The default #JSCExceptionHandler
// simply calls jsc_context_throw_exception() to throw the exception to the #JSCContext.
// If you don't want to catch the exception, but only get notified about it, call
// jsc_context_throw_exception() in @handler like the default one does.
// The last exception handler pushed is the only one used by the #JSCContext, use
// jsc_context_pop_exception_handler() to remove it and set the previous one. When @handler
// is removed from the context, @destroy_notify is called with @user_data as parameter.
func (x *Context) PushExceptionHandler(HandlerVar *ExceptionHandler, UserDataVar uintptr, DestroyNotifyVar *glib.DestroyNotify) {
	core.LazyRegister(&xContextPushExceptionHandler, "JAVASCRIPTCORE", "jsc_context_push_exception_handler", false)

	xContextPushExceptionHandler(x.GoPointer(), glib.NewCallback(HandlerVar), UserDataVar, glib.NewCallbackNullable(DestroyNotifyVar))
}

var xContextRegisterClass func(uintptr, string, uintptr, *ClassVTable, uintptr) uintptr

// Register a custom class in @context using the given @name. If the new class inherits from
// another #JSCClass, the parent should be passed as @parent_class, otherwise %NULL should be
// used. The optional @vtable parameter allows to provide a custom implementation for handling
// the class, for example, to handle external properties not added to the prototype.
// When an instance of the #JSCClass is cleared in the context, @destroy_notify is called with
// the instance as parameter.
func (x *Context) RegisterClass(NameVar string, ParentClassVar *Class, VtableVar *ClassVTable, DestroyNotifyVar *glib.DestroyNotify) *Class {
	core.LazyRegister(&xContextRegisterClass, "JAVASCRIPTCORE", "jsc_context_register_class", false)
	var cls *Class

	cret := xContextRegisterClass(x.GoPointer(), NameVar, ParentClassVar.GoPointer(), VtableVar, glib.NewCallbackNullable(DestroyNotifyVar))

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &Class{}
	cls.Ptr = cret
	return cls
}

var xContextSetValue func(uintptr, string, uintptr)

// Set a property of @context global object with @name and @value.
func (x *Context) SetValue(NameVar string, ValueVar *Value) {
	core.LazyRegister(&xContextSetValue, "JAVASCRIPTCORE", "jsc_context_set_value", false)

	xContextSetValue(x.GoPointer(), NameVar, ValueVar.GoPointer())
}

var xContextThrow func(uintptr, string)

// Throw an exception to @context using the given error message. The created #JSCException
// can be retrieved with jsc_context_get_exception().
func (x *Context) Throw(ErrorMessageVar string) {
	core.LazyRegister(&xContextThrow, "JAVASCRIPTCORE", "jsc_context_throw", false)

	xContextThrow(x.GoPointer(), ErrorMessageVar)
}

var xContextThrowException func(uintptr, uintptr)

// Throw @exception to @context.
func (x *Context) ThrowException(ExceptionVar *Exception) {
	core.LazyRegister(&xContextThrowException, "JAVASCRIPTCORE", "jsc_context_throw_exception", false)

	xContextThrowException(x.GoPointer(), ExceptionVar.GoPointer())
}

var xContextThrowPrintf func(uintptr, string, ...interface{})

// Throw an exception to @context using the given formatted string as error message.
// The created #JSCException can be retrieved with jsc_context_get_exception().
func (x *Context) ThrowPrintf(FormatVar string, varArgs ...interface{}) {
	core.LazyRegister(&xContextThrowPrintf, "JAVASCRIPTCORE", "jsc_context_throw_printf", false)

	xContextThrowPrintf(x.GoPointer(), FormatVar, varArgs...)
}

var xContextThrowWithName func(uintptr, string, string)

// Throw an exception to @context using the given error name and message. The created #JSCException
// can be retrieved with jsc_context_get_exception().
func (x *Context) ThrowWithName(ErrorNameVar string, ErrorMessageVar string) {
	core.LazyRegister(&xContextThrowWithName, "JAVASCRIPTCORE", "jsc_context_throw_with_name", false)

	xContextThrowWithName(x.GoPointer(), ErrorNameVar, ErrorMessageVar)
}

var xContextThrowWithNamePrintf func(uintptr, string, string, ...interface{})

// Throw an exception to @context using the given error name and the formatted string as error message.
// The created #JSCException can be retrieved with jsc_context_get_exception().
func (x *Context) ThrowWithNamePrintf(ErrorNameVar string, FormatVar string, varArgs ...interface{}) {
	core.LazyRegister(&xContextThrowWithNamePrintf, "JAVASCRIPTCORE", "jsc_context_throw_with_name_printf", false)

	xContextThrowWithNamePrintf(x.GoPointer(), ErrorNameVar, FormatVar, varArgs...)
}

func (c *Context) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *Context) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

var xContextGetCurrent func() uintptr

// Get the #JSCContext that is currently executing a function. This should only be
// called within a function or method callback, otherwise %NULL will be returned.
func ContextGetCurrent() *Context {
	core.LazyRegister(&xContextGetCurrent, "JAVASCRIPTCORE", "jsc_context_get_current", false)
	var cls *Context

	cret := xContextGetCurrent()

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &Context{}
	cls.Ptr = cret
	return cls
}

func init() {
	core.SetPackageName("JAVASCRIPTCORE", "javascriptcoregtk-6.0")
	core.SetSharedLibraries("JAVASCRIPTCORE", []string{"libjavascriptcoregtk-6.0.so.1", "libjavascriptcoregtk-6.0.1.dylib"})
}
